load("@rules_rust//rust:defs.bzl", "rust_library")

exports_files(["Cargo.toml"])

rust_library(
    name = "ui",
    srcs = glob(["src/**/*.rs"]),
    crate_name = "artisan_ui",
    deps = [
        "//modules/assets:assets",
        "@crates//:gpui",
        "@crates//:pulldown-cmark",
        "@crates//:syntect",
        "@crates//:thiserror",
    ],
    edition = "2024",
    lint_config = "//:workspace_lints",
    visibility = ["//visibility:public"],
)
