[package]
name = "artisan-ui"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
artisan-assets = { path = "../assets" }
pulldown-cmark.workspace = true
syntect.workspace = true
thiserror.workspace = true

[lints]
workspace = true
