[workspace]
members = ["modules/broker", "modules/installer", "modules/cli", "crates/*"]
resolver = "2"

[workspace.package]
edition = "2024"
license = "BSD-3-Clause"
repository = "https://github.com/sandersonstabo/artisan-editor"
rust-version = "1.85"
version = "0.2.2"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = "deny"
pedantic = "deny"
