packages:
    - "modules/*"
allowBuilds:
    esbuild: true
    electron-winstaller: true
    koffi: true
    msgpackr-extract: false
    node-pty: true
minimumReleaseAgeExclude:
    - "@effect/sql-sqlite-node@4.0.0-beta.97"
    - effect@4.0.0-beta.97
    - "@koromix/koffi-darwin-arm64@3.1.1"
    - "@koromix/koffi-darwin-x64@3.1.1"
    - "@koromix/koffi-freebsd-arm64@3.1.1"
    - "@koromix/koffi-freebsd-ia32@3.1.1"
    - "@koromix/koffi-freebsd-x64@3.1.1"
    - "@koromix/koffi-linux-arm64@3.1.1"
    - "@koromix/koffi-linux-ia32@3.1.1"
    - "@koromix/koffi-linux-loong64@3.1.1"
    - "@koromix/koffi-linux-riscv64@3.1.1"
    - "@koromix/koffi-linux-x64@3.1.1"
    - "@koromix/koffi-openbsd-arm64@3.1.1"
    - "@koromix/koffi-openbsd-ia32@3.1.1"
    - "@koromix/koffi-openbsd-x64@3.1.1"
    - "@koromix/koffi-win32-arm64@3.1.1"
    - "@koromix/koffi-win32-ia32@3.1.1"
    - "@koromix/koffi-win32-x64@3.1.1"
    - koffi@3.1.1
