load("@rules_rust//rust:defs.bzl", "rust_library")

exports_files(["Cargo.toml"])

rust_library(
    name = "migrations",
    srcs = glob(["src/**/*.rs"]),
    crate_name = "artisan_migrations",
    edition = "2024",
    lint_config = "//:workspace_lints",
    visibility = ["//visibility:public"],
)
