export type FrontendContractState = "live" | "fixture" | "backend_moving" | "blocked";

export type FrontendContractOwner = "frontend" | "artisan_client" | "fixture" | "missing";

export type FrontendSurface = "left" | "main" | "right" | "connection" | "desktop_shell";

export interface FrontendContractEntry {
	readonly id: string;
	readonly state: FrontendContractState;
	readonly owner: FrontendContractOwner;
	readonly surface: FrontendSurface;
	readonly pane: string;
	readonly reason: string;
	readonly contract_names?: ReadonlyArray<string>;
	readonly guidance?: ReadonlyArray<string>;
}

export const FrontendContractRegistry: ReadonlyArray<FrontendContractEntry> = [
	{
		id: "left.thread-list",
		state: "live",
		owner: "artisan_client",
		surface: "left",
		pane: "thread-list",
		reason: "The typed client exposes a race-safe initial thread list and ordered list updates.",
		contract_names: ["ArtisanClient.ListThreads", "ArtisanClient.SubscribeThreadList"],
	},
	{
		id: "left.thread-create",
		state: "live",
		owner: "artisan_client",
		surface: "left",
		pane: "thread-actions",
		reason: "Thread creation is a durable public command whose retry identity belongs to the client.",
		contract_names: ["ArtisanClient.Command", "ThreadCreateCommand"],
	},
	{
		id: "left.thread-select",
		state: "live",
		owner: "frontend",
		surface: "left",
		pane: "thread-list",
		reason: "Selecting an already projected thread changes only renderer presentation state.",
	},
	{
		id: "left.thread-rename",
		state: "live",
		owner: "artisan_client",
		surface: "left",
		pane: "thread-row",
		reason: "Thread titles are backend-owned and renamed through the public command channel.",
		contract_names: ["ArtisanClient.Command", "ThreadRenameCommand"],
	},
	{
		id: "left.thread-pin",
		state: "live",
		owner: "artisan_client",
		surface: "left",
		pane: "thread-row",
		reason: "Pin and unpin state is durable thread metadata, never local component state.",
		contract_names: ["ArtisanClient.Command", "ThreadPinCommand", "ThreadUnpinCommand"],
	},
	{
		id: "left.thread-archive",
		state: "live",
		owner: "artisan_client",
		surface: "left",
		pane: "thread-row",
		reason: "Archive and restore are durable public thread commands.",
		contract_names: ["ArtisanClient.Command", "ThreadArchiveCommand", "ThreadRestoreCommand"],
	},
	{
		id: "left.thread-project",
		state: "live",
		owner: "artisan_client",
		surface: "left",
		pane: "thread-row",
		reason: "Project assignment, unlock, and accepted rehome suggestions update backend projections.",
		contract_names: [
			"ArtisanClient.Command",
			"ThreadProjectAssignCommand",
			"ThreadProjectUnlockCommand",
		],
	},
	{
		id: "left.thread-retention",
		state: "live",
		owner: "artisan_client",
		surface: "left",
		pane: "thread-settings",
		reason: "The canonical retention policy and its durable update are exposed by the typed client.",
		contract_names: [
			"ArtisanClient.GetThreadRetentionPolicy",
			"ArtisanClient.UpdateThreadRetentionPolicy",
		],
	},
	{
		id: "left.identity",
		state: "blocked",
		owner: "missing",
		surface: "left",
		pane: "identity-card",
		reason: "A visual placeholder may exist, but identity and account behavior is blocked without a public OS identity projection.",
	},
	{
		id: "left.marketplace",
		state: "blocked",
		owner: "missing",
		surface: "left",
		pane: "primary-actions",
		reason: "Routine and Capability registries, previews, approvals, sync, and lifecycle contracts are missing.",
	},
	{
		id: "main.workspace-modes",
		state: "live",
		owner: "frontend",
		surface: "main",
		pane: "mode-switcher",
		reason: "Text Editor, Chat, and Orchestrator selection is user-owned renderer state.",
	},
	{
		id: "main.file-tabs",
		state: "live",
		owner: "frontend",
		surface: "main",
		pane: "file-tab-strip",
		reason: "The open, preview, pinned, dirty, and selected tab model is user-owned renderer state.",
	},
	{
		id: "main.pane-behaviour",
		state: "live",
		owner: "frontend",
		surface: "main",
		pane: "editor-shell",
		reason: "Pane size, collapse state, overlays, scroll positions, and focus are local presentation state.",
	},
	{
		id: "main.current-work",
		state: "live",
		owner: "artisan_client",
		surface: "main",
		pane: "chat",
		reason: "The public query supplies compact current run and agent identity, not transcript history.",
		contract_names: ["ArtisanClient.GetThreadWork", "ThreadWorkItem"],
	},
	{
		id: "main.transcript",
		state: "live",
		owner: "artisan_client",
		surface: "main",
		pane: "chat",
		reason: "The typed client exposes a bounded, safe transcript projection with explicit erased and unavailable states.",
		contract_names: ["ArtisanClient.GetThreadTranscript", "ThreadTranscriptSnapshot"],
	},
	{
		id: "main.chat-send",
		state: "live",
		owner: "artisan_client",
		surface: "main",
		pane: "chat-composer",
		reason: "Message send and queued follow-up intent use the durable public command channel.",
		contract_names: ["ArtisanClient.Command", "ThreadSendMessageCommand"],
	},
	{
		id: "main.chat-steer",
		state: "live",
		owner: "artisan_client",
		surface: "main",
		pane: "chat-composer",
		reason: "An active run can be steered through its provider-neutral public command.",
		contract_names: ["ArtisanClient.Command", "RunSteerCommand"],
	},
	{
		id: "main.approval",
		state: "live",
		owner: "artisan_client",
		surface: "main",
		pane: "chat-interactions",
		reason: "Canonical events deliver approvals and the public command records the response.",
		contract_names: [
			"ArtisanClient.Events",
			"ApprovalInteractionEvent",
			"ArtisanClient.Command",
			"RunRespondApprovalCommand",
		],
	},
	{
		id: "main.question",
		state: "live",
		owner: "artisan_client",
		surface: "main",
		pane: "chat-interactions",
		reason: "Canonical events deliver questions and the public command records answers.",
		contract_names: [
			"ArtisanClient.Events",
			"QuestionInteractionEvent",
			"ArtisanClient.Command",
			"RunRespondQuestionCommand",
		],
	},
	{
		id: "main.orchestration-known-id",
		state: "live",
		owner: "artisan_client",
		surface: "main",
		pane: "orchestrator",
		reason: "A known group ID has a canonical graph snapshot, ordered patches, and public controls.",
		contract_names: [
			"ArtisanClient.GetOrchestrationGraph",
			"ArtisanClient.SubscribeOrchestrationGraph",
			"ArtisanClient.Command",
			"OrchestrationGraph",
		],
	},
	{
		id: "main.orchestration-start",
		state: "live",
		owner: "artisan_client",
		surface: "main",
		pane: "orchestrator",
		reason: "Starting a graph is public, but the UI may offer writes only in the one shared visible checkout.",
		contract_names: [
			"ArtisanClient.Command",
			"OrchestrationGroupStartCommand",
			"AssignmentSpec",
			"AssignmentWorkspace",
		],
		guidance: [
			"Offer write-capable assignments only with AssignmentWorkspace.isolation set to shared.",
			"Do not expose the isolated AssignmentWorkspace variant because Artisan guarantees one visible checkout.",
		],
	},
	{
		id: "main.orchestration-discovery",
		state: "live",
		owner: "artisan_client",
		surface: "main",
		pane: "orchestrator",
		reason: "A fresh renderer can list a thread's active or historic orchestration groups without a known group id.",
		contract_names: ["ArtisanClient.ListOrchestrationGroups"],
	},
	{
		id: "main.file-discovery",
		state: "blocked",
		owner: "missing",
		surface: "main",
		pane: "file-navigation",
		reason: "Quick open, recent files, breadcrumbs, and language-service discovery have no public contract.",
	},
	{
		id: "main.file-read",
		state: "backend_moving",
		owner: "missing",
		surface: "main",
		pane: "text-editor",
		reason: "Controlled reads exist in active backend work but are not a verified typed-client production checkpoint.",
	},
	{
		id: "main.file-replace",
		state: "backend_moving",
		owner: "missing",
		surface: "main",
		pane: "text-editor",
		reason: "Conditional replacement must wait for verified service, router, client, and production composition.",
	},
	{
		id: "main.change-diff",
		state: "backend_moving",
		owner: "missing",
		surface: "main",
		pane: "diff-view",
		reason: "Changed-file and diff projections are still moving with the controlled file backend slice.",
	},
	{
		id: "main.change-review",
		state: "backend_moving",
		owner: "missing",
		surface: "main",
		pane: "diff-view",
		reason: "Review intent is backend-owned and cannot be wired before the typed client checkpoint is verified.",
	},
	{
		id: "main.change-rollback",
		state: "backend_moving",
		owner: "missing",
		surface: "main",
		pane: "diff-view",
		reason: "Rollback is a controlled backend mutation and must never be simulated in the renderer.",
	},
	{
		id: "right.terminals",
		state: "live",
		owner: "artisan_client",
		surface: "right",
		pane: "terminals",
		reason: "Terminal projections, lifecycle commands, and bounded output bytes are public.",
		contract_names: [
			"ArtisanClient.ListTerminals",
			"ArtisanClient.OpenTerminalOutput",
			"ArtisanClient.Command",
			"TerminalOpenCommand",
			"TerminalWriteCommand",
			"TerminalResizeCommand",
			"TerminalClearCommand",
			"TerminalRestartCommand",
			"TerminalKillCommand",
			"TerminalCloseCommand",
		],
	},
	{
		id: "right.compact-agents",
		state: "live",
		owner: "artisan_client",
		surface: "right",
		pane: "agents",
		reason: "Known orchestration graph projections provide compact agent identity and status.",
		contract_names: [
			"ArtisanClient.GetOrchestrationGraph",
			"ArtisanClient.SubscribeOrchestrationGraph",
		],
	},
	{
		id: "right.session-policy",
		state: "blocked",
		owner: "missing",
		surface: "right",
		pane: "session-controls",
		reason: "Engine, model, effort, sandbox, permission, and web controls lack one canonical session policy.",
	},
	{
		id: "right.global-guidance",
		state: "live",
		owner: "artisan_client",
		surface: "right",
		pane: "settings",
		reason: "Canonical guidance state, updates, drift resolution, and retry are public typed-client operations.",
		contract_names: [
			"ArtisanClient.GetGlobalGuidance",
			"ArtisanClient.UpdateGlobalGuidance",
			"ArtisanClient.SelectGlobalGuidance",
			"ArtisanClient.ResolveGlobalGuidanceDrift",
			"ArtisanClient.RetryGlobalGuidanceSync",
		],
	},
	{
		id: "right.model-behaviour",
		state: "live",
		owner: "artisan_client",
		surface: "right",
		pane: "settings",
		reason: "Curated Model Behaviour state, updates, drift resolution, and retry are public typed-client operations.",
		contract_names: [
			"ArtisanClient.GetModelBehaviour",
			"ArtisanClient.UpdateModelBehaviour",
			"ArtisanClient.ResolveModelBehaviourDrift",
			"ArtisanClient.RetryModelBehaviourSync",
		],
	},
	{
		id: "right.git",
		state: "blocked",
		owner: "missing",
		surface: "right",
		pane: "branch-and-changes",
		reason: "The renderer has no authoritative Git read model, subscription, or approval-bearing mutation commands.",
	},
	{
		id: "right.processes-ports",
		state: "fixture",
		owner: "fixture",
		surface: "right",
		pane: "processes",
		reason: "Process and development-server rows may be designed from fixtures, but cannot inspect the host from the renderer.",
	},
	{
		id: "right.previews",
		state: "blocked",
		owner: "missing",
		surface: "right",
		pane: "previews",
		reason: "Production preview discovery, health, logs, URL state, and external launch routes are missing.",
	},
	{
		id: "right.permissions-usage",
		state: "blocked",
		owner: "missing",
		surface: "right",
		pane: "permissions-and-usage",
		reason: "Canonical permission summaries and usage aggregation are not public projections.",
	},
	{
		id: "connection.events",
		state: "live",
		owner: "artisan_client",
		surface: "connection",
		pane: "application",
		reason: "Canonical events and bounded client errors are public streams.",
		contract_names: ["ArtisanClient.Events", "ArtisanClient.Errors"],
	},
	{
		id: "connection.cursors",
		state: "live",
		owner: "artisan_client",
		surface: "connection",
		pane: "application",
		reason: "The typed client exposes applied cursors and owns correlation, ACK, retry, and replay bookkeeping.",
		contract_names: ["ArtisanClient.Cursors", "ArtisanClientCursors"],
	},
	{
		id: "connection.lifecycle",
		state: "fixture",
		owner: "fixture",
		surface: "connection",
		pane: "application",
		reason: "The client reconnects internally but exposes no authoritative negotiating, replaying, stale, or current lifecycle stream.",
	},
	{
		id: "desktop-shell.electron-bootstrap",
		state: "blocked",
		owner: "missing",
		surface: "desktop_shell",
		pane: "application",
		reason: "Electron main, utility, renderer bootstrap, packaging, and single-instance ownership are absent.",
	},
] as const;
