export type FrontendContractState = "live" | "fixture" | "backend_moving" | "blocked";

export type FrontendContractOwner = "frontend" | "artisan_client" | "fixture" | "missing";

export type FrontendSurface = "left" | "main" | "right" | "connection" | "desktop_shell";

export interface FrontendContractEntry {
	readonly id: string;
	readonly state: FrontendContractState;
	readonly owner: FrontendContractOwner;
	readonly surface: FrontendSurface;
	readonly pane: string;
	readonly reason: string;
	readonly contract_names?: ReadonlyArray<string>;
	readonly guidance?: ReadonlyArray<string>;
}

export const FrontendContractRegistry: ReadonlyArray<FrontendContractEntry> = [
	{
		id: "left.thread-list",
		state: "live",
		owner: "artisan_client",
		surface: "left",
		pane: "thread-list",
		reason: "The typed client exposes a race-safe initial thread list and ordered list updates.",
		contract_names: ["ArtisanClient.ListThreads", "ArtisanClient.SubscribeThreadList"],
	},
	{
		id: "left.thread-create",
		state: "live",
		owner: "artisan_client",
		surface: "left",
		pane: "thread-actions",
		reason: "Forge creates the durable thread identity and returns its authoritative projection through the dedicated client RPC.",
		contract_names: ["ArtisanClient.CreateThread", "ThreadCreateInput"],
	},
	{
		id: "left.thread-select",
		state: "live",
		owner: "frontend",
		surface: "left",
		pane: "thread-list",
		reason: "Selecting an already projected thread changes only renderer presentation state.",
	},
	{
		id: "left.thread-rename",
		state: "live",
		owner: "artisan_client",
		surface: "left",
		pane: "thread-row",
		reason: "Thread titles are backend-owned and renamed through the public command channel.",
		contract_names: ["ArtisanClient.Command", "ThreadRenameCommand"],
	},
	{
		id: "left.thread-pin",
		state: "live",
		owner: "artisan_client",
		surface: "left",
		pane: "thread-row",
		reason: "Pin and unpin state is durable thread metadata, never local component state.",
		contract_names: ["ArtisanClient.Command", "ThreadPinCommand", "ThreadUnpinCommand"],
	},
	{
		id: "left.thread-archive",
		state: "live",
		owner: "artisan_client",
		surface: "left",
		pane: "thread-row",
		reason: "Archive and restore are durable public thread commands.",
		contract_names: ["ArtisanClient.Command", "ThreadArchiveCommand", "ThreadRestoreCommand"],
	},
	{
		id: "left.thread-project",
		state: "live",
		owner: "artisan_client",
		surface: "left",
		pane: "thread-row",
		reason: "Project assignment, unlock, and accepted rehome suggestions update backend projections.",
		contract_names: [
			"ArtisanClient.Command",
			"ThreadProjectAssignCommand",
			"ThreadProjectUnlockCommand",
		],
	},
	{
		id: "left.thread-retention",
		state: "live",
		owner: "artisan_client",
		surface: "left",
		pane: "thread-settings",
		reason: "The canonical retention policy and its durable update are exposed by the typed client.",
		contract_names: [
			"ArtisanClient.GetThreadRetentionPolicy",
			"ArtisanClient.UpdateThreadRetentionPolicy",
		],
	},
	{
		id: "left.identity",
		state: "live",
		owner: "artisan_client",
		surface: "left",
		pane: "identity-card",
		reason: "Forge projects the signed-in host identity and per-engine provider usage through dedicated queries.",
		contract_names: ["ArtisanClient.GetHostIdentity", "ArtisanClient.GetEngineUsage"],
	},
	{
		id: "left.marketplace",
		state: "live",
		owner: "artisan_client",
		surface: "left",
		pane: "primary-actions",
		reason: "Routine and Capability registries, previews, approvals, OAuth, sync, drift, invocation, and lifecycle controls are rendered from the typed client.",
		contract_names: ["ArtisanClient.ListRoutines", "ArtisanClient.ListCapabilities"],
	},
	{
		id: "main.workspace-modes",
		state: "live",
		owner: "frontend",
		surface: "main",
		pane: "mode-switcher",
		reason: "Text Editor, Chat, and Orchestrator selection is user-owned renderer state.",
	},
	{
		id: "main.file-tabs",
		state: "live",
		owner: "frontend",
		surface: "main",
		pane: "file-tab-strip",
		reason: "The open, preview, pinned, dirty, and selected tab model is user-owned renderer state.",
	},
	{
		id: "main.pane-behaviour",
		state: "live",
		owner: "frontend",
		surface: "main",
		pane: "editor-shell",
		reason: "Pane size, collapse state, overlays, scroll positions, and focus are local presentation state.",
	},
	{
		id: "main.current-work",
		state: "live",
		owner: "artisan_client",
		surface: "main",
		pane: "chat",
		reason: "The public query supplies compact current run and agent identity, not transcript history.",
		contract_names: ["ArtisanClient.GetThreadWork", "ThreadWorkItem"],
	},
	{
		id: "main.activity-status",
		state: "live",
		owner: "frontend",
		surface: "main",
		pane: "chat",
		reason: "Canonical run, orchestration, permission, tool, and compaction projections drive the reduced-motion-aware working indicator without exposing private provider reasoning.",
	},
	{
		id: "main.transcript",
		state: "live",
		owner: "artisan_client",
		surface: "main",
		pane: "chat",
		reason: "The typed client exposes a bounded, safe transcript projection with explicit erased and unavailable states.",
		contract_names: ["ArtisanClient.GetThreadTranscript", "ThreadTranscriptSnapshot"],
	},
	{
		id: "main.chat-send",
		state: "live",
		owner: "artisan_client",
		surface: "main",
		pane: "chat-composer",
		reason: "Message send and queued follow-up intent use the durable public command channel.",
		contract_names: ["ArtisanClient.Command", "ThreadSendMessageCommand"],
	},
	{
		id: "main.chat-steer",
		state: "live",
		owner: "artisan_client",
		surface: "main",
		pane: "chat-composer",
		reason: "An active run can be steered through its provider-neutral public command.",
		contract_names: ["ArtisanClient.Command", "RunSteerCommand"],
	},
	{
		id: "main.approval",
		state: "live",
		owner: "artisan_client",
		surface: "main",
		pane: "chat-interactions",
		reason: "Canonical events deliver approvals and the public command records the response.",
		contract_names: [
			"ArtisanClient.Events",
			"ApprovalInteractionEvent",
			"ArtisanClient.Command",
			"RunRespondApprovalCommand",
		],
	},
	{
		id: "main.question",
		state: "live",
		owner: "artisan_client",
		surface: "main",
		pane: "chat-interactions",
		reason: "Canonical events deliver questions and the public command records answers.",
		contract_names: [
			"ArtisanClient.Events",
			"QuestionInteractionEvent",
			"ArtisanClient.Command",
			"RunRespondQuestionCommand",
		],
	},
	{
		id: "main.usage-activity",
		state: "live",
		owner: "artisan_client",
		surface: "main",
		pane: "landing",
		reason: "Persisted run totals roll up into UTC calendar days, so the landing grid reports recorded spend rather than an estimate.",
		contract_names: ["ArtisanClient.GetSurfaceUsageDaily", "SurfaceUsageDailyBucket"],
		guidance: [
			"Render an empty grid when no run has reported usage; never synthesize sample activity.",
		],
	},
	{
		id: "main.orchestration-known-id",
		state: "live",
		owner: "artisan_client",
		surface: "main",
		pane: "orchestrator",
		reason: "A known group ID has a canonical graph snapshot, ordered patches, and public controls.",
		contract_names: [
			"ArtisanClient.GetOrchestrationGraph",
			"ArtisanClient.SubscribeOrchestrationGraph",
			"ArtisanClient.Command",
			"OrchestrationGraph",
		],
	},
	{
		id: "main.orchestration-start",
		state: "live",
		owner: "artisan_client",
		surface: "main",
		pane: "orchestrator",
		reason: "Starting a graph is public, but the UI may offer writes only in the one shared visible checkout.",
		contract_names: [
			"ArtisanClient.Command",
			"OrchestrationGroupStartCommand",
			"AssignmentSpec",
			"AssignmentWorkspace",
		],
		guidance: [
			"Offer write-capable assignments only with AssignmentWorkspace.isolation set to shared.",
			"Do not expose the isolated AssignmentWorkspace variant because Artisan guarantees one visible checkout.",
		],
	},
	{
		id: "main.orchestration-discovery",
		state: "live",
		owner: "artisan_client",
		surface: "main",
		pane: "orchestrator",
		reason: "A fresh renderer can list a thread's active or historic orchestration groups without a known group id.",
		contract_names: ["ArtisanClient.ListOrchestrationGroups"],
	},
	{
		id: "main.file-discovery",
		state: "live",
		owner: "artisan_client",
		surface: "main",
		pane: "file-navigation",
		reason: "Quick open and Monaco navigation use the bounded authoritative workspace file discovery query.",
		contract_names: ["ArtisanClient.ListWorkspaceFiles", "WorkspaceFileDiscoveryQueryResult"],
	},
	{
		id: "main.file-read",
		state: "live",
		owner: "artisan_client",
		surface: "main",
		pane: "text-editor",
		reason: "Monaco opens content only through the bounded workspace read query and keeps workspace-qualified models.",
		contract_names: ["ArtisanClient.ReadWorkspaceFile", "WorkspaceFileReadQueryResult"],
	},
	{
		id: "main.file-replace",
		state: "live",
		owner: "artisan_client",
		surface: "main",
		pane: "text-editor",
		reason: "Editor saves use revision-bearing conditional replacement and reconcile saved or conflicting authoritative content.",
		contract_names: ["ArtisanClient.ReplaceWorkspaceFile", "WorkspaceFileReplaceCommand"],
	},
	{
		id: "main.change-diff",
		state: "live",
		owner: "artisan_client",
		surface: "main",
		pane: "diff-view",
		reason: "Attributed changes and immutable diffs are loaded through public query projections.",
		contract_names: [
			"ArtisanClient.ListWorkspaceChanges",
			"ArtisanClient.GetWorkspaceChangeDiff",
		],
	},
	{
		id: "main.change-review",
		state: "live",
		owner: "artisan_client",
		surface: "main",
		pane: "diff-view",
		reason: "Review outcomes are durable backend commands exposed in the Changes surface.",
		contract_names: ["ArtisanClient.ReviewWorkspaceChange", "WorkspaceChangeReviewCommand"],
	},
	{
		id: "main.change-rollback",
		state: "live",
		owner: "artisan_client",
		surface: "main",
		pane: "diff-view",
		reason: "Rollback remains a guarded authoritative mutation and is never simulated by the renderer.",
		contract_names: ["ArtisanClient.RollbackWorkspaceChange", "WorkspaceChangeRollbackCommand"],
	},
	{
		id: "right.terminals",
		state: "live",
		owner: "artisan_client",
		surface: "right",
		pane: "terminals",
		reason: "Terminal projections expose durable owner, pin, registered preview targets, lifecycle state, exit facts, and bounded output bytes through public contracts.",
		contract_names: [
			"ArtisanClient.ListTerminals",
			"ArtisanClient.OpenTerminalOutput",
			"ArtisanClient.Command",
			"TerminalOpenCommand",
			"TerminalWriteCommand",
			"TerminalResizeCommand",
			"TerminalClearCommand",
			"TerminalRestartCommand",
			"TerminalKillCommand",
			"TerminalCloseCommand",
			"TerminalPinCommand",
			"TerminalOwnership",
			"TerminalPreviewTarget",
		],
	},
	{
		id: "right.compact-agents",
		state: "live",
		owner: "artisan_client",
		surface: "right",
		pane: "agents",
		reason: "Known orchestration graph projections provide compact agent identity and status.",
		contract_names: [
			"ArtisanClient.GetOrchestrationGraph",
			"ArtisanClient.SubscribeOrchestrationGraph",
		],
	},
	{
		id: "right.session-policy",
		state: "live",
		owner: "artisan_client",
		surface: "right",
		pane: "session-controls",
		reason: "The durable Codex-only thread policy owns model, effort, sandbox, permissions, web search, and clarification behavior.",
		contract_names: ["ArtisanClient.UpdateThreadSessionPolicy", "ThreadSessionPolicy"],
	},
	{
		id: "right.global-guidance",
		state: "live",
		owner: "artisan_client",
		surface: "right",
		pane: "settings",
		reason: "Canonical guidance state, updates, drift resolution, and retry are public typed-client operations.",
		contract_names: [
			"ArtisanClient.GetGlobalGuidance",
			"ArtisanClient.UpdateGlobalGuidance",
			"ArtisanClient.SelectGlobalGuidance",
			"ArtisanClient.ResolveGlobalGuidanceDrift",
			"ArtisanClient.RetryGlobalGuidanceSync",
		],
	},
	{
		id: "right.model-behaviour",
		state: "live",
		owner: "artisan_client",
		surface: "right",
		pane: "settings",
		reason: "Curated Model Behaviour state, updates, drift resolution, and retry are public typed-client operations.",
		contract_names: [
			"ArtisanClient.GetModelBehaviour",
			"ArtisanClient.UpdateModelBehaviour",
			"ArtisanClient.ResolveModelBehaviourDrift",
			"ArtisanClient.RetryModelBehaviourSync",
		],
	},
	{
		id: "right.git",
		state: "live",
		owner: "artisan_client",
		surface: "right",
		pane: "branch-and-changes",
		reason: "The right pane renders authoritative Git state and diffs and sends approval-bearing stage or unstage requests.",
		contract_names: ["ArtisanClient.GetGitWorkspace", "ArtisanClient.RequestGitIndexMutation"],
	},
	{
		id: "right.processes-ports",
		state: "live",
		owner: "artisan_client",
		surface: "right",
		pane: "processes",
		reason: "Backend-owned terminal sessions and preview targets expose process, port, health, and exit facts without renderer host inspection.",
		contract_names: ["ArtisanClient.ListTerminals", "ArtisanClient.ListPreviewTargets"],
	},
	{
		id: "right.previews",
		state: "live",
		owner: "artisan_client",
		surface: "right",
		pane: "previews",
		reason: "Preview registration, health, state, inspection, external launch, and cleanup use backend-owned targets.",
		contract_names: [
			"ArtisanClient.RegisterPreviewTarget",
			"ArtisanClient.OpenPreviewInspectionSession",
		],
	},
	{
		id: "right.permissions-usage",
		state: "live",
		owner: "artisan_client",
		surface: "right",
		pane: "permissions-and-usage",
		reason: "Canonical approval, tool activity, and usage projections are rendered from the live session store.",
		contract_names: [
			"ArtisanClient.ListArtisanApprovals",
			"ArtisanClient.GetSurfaceUsageAggregate",
		],
	},
	{
		id: "connection.events",
		state: "live",
		owner: "artisan_client",
		surface: "connection",
		pane: "application",
		reason: "Canonical events and bounded client errors are public streams.",
		contract_names: ["ArtisanClient.Events", "ArtisanClient.Errors"],
	},
	{
		id: "connection.cursors",
		state: "live",
		owner: "artisan_client",
		surface: "connection",
		pane: "application",
		reason: "The typed client exposes applied cursors and owns correlation, ACK, retry, and replay bookkeeping.",
		contract_names: ["ArtisanClient.Cursors", "ArtisanClientCursors"],
	},
	{
		id: "connection.lifecycle",
		state: "live",
		owner: "frontend",
		surface: "connection",
		pane: "application",
		reason: "The renderer connector exposes connecting, ready, reconnecting, stale, and error state while retaining last-known projections.",
	},
	{
		id: "desktop-shell.electron-bootstrap",
		state: "live",
		owner: "frontend",
		surface: "desktop_shell",
		pane: "application",
		reason: "Electron is a single-instance sandboxed window that renders the bundled frontend from artisan://app and delegates Forge lifecycle and one-time pairing to ae; it has no preload or IPC, and its one narrow same-origin control persists the selected runtime app icon.",
	},
] as const;
