[package]
name = "artisan-backend"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
artisan-database = { path = "../database" }
artisan-domain = { path = "../domain" }
artisan-migrations = { path = "../migrations" }
artisan-protocol = { path = "../protocol" }
artisan-transport = { path = "../transport" }
getrandom.workspace = true
quinn.workspace = true
sea-orm.workspace = true
thiserror.workspace = true
zeroize.workspace = true

[dev-dependencies]
rcgen.workspace = true
rustls-pki-types.workspace = true
tokio = { workspace = true, features = ["macros", "net", "rt", "sync", "time"] }

[[test]]
name = "app_test"
path = "../../tests/backend/app.rs"

[[test]]
name = "connection"
path = "../../tests/backend/connection.rs"

[[test]]
name = "request_handler"
path = "../../tests/backend/request_handler.rs"

[lints]
workspace = true
