//! Atomic claim and recovery of durable message dispatches.
//!
//! Dispatch claim, lease, and lifecycle transitions over `message_dispatches`.
//!
//! The claim path lives in [`claim`], lease renewal in [`lease`], fenced
//! terminal transitions in [`transition`], and never-leased steer handling in
//! [`steered`]. This parent module owns the public command records and the
//! opaque lease-owner token.

#![forbid(unsafe_code)]

mod claim;
mod lease;
mod steered;
mod transition;

pub(crate) use self::steered::{
    COMPLETE_STEERED_SQL, SteeredRowTerminal, classify_steered_transition_miss,
};

use subtle::ConstantTimeEq;
use thiserror::Error;
use zeroize::Zeroize;

use artisan_domain::{MessageId, RequestId, UnixMillis};

const OWNER_BYTES: usize = 32;
const OWNER_STORAGE_BYTES: usize = OWNER_BYTES * 2;
const MAX_DISPATCH_ATTEMPTS: i32 = i32::MAX;

/// Maximum UTF-8 byte length accepted for one dispatch failure reason.
const FAILURE_REASON_MAX_BYTES: usize = 4096;

/// Failure to accept one dispatch failure reason.
///
/// Variants deliberately carry only lengths and bounds so raw failure text
/// cannot leak through repository error rendering.
#[derive(Clone, Copy, Debug, Error, Eq, PartialEq)]
pub enum DispatchFailureReasonError {
    /// The supplied reason was empty.
    #[error("dispatch failure reason must not be empty")]
    Empty,

    /// The supplied reason exceeded its UTF-8 byte ceiling.
    #[error("dispatch failure reason is {length} UTF-8 bytes; the maximum is {maximum}")]
    TooLong {
        /// Offending length in UTF-8 bytes.
        length: usize,
        /// The documented ceiling ([`DispatchFailureReason::MAX_BYTES`]).
        maximum: usize,
    },
}

/// Bounded failure explanation persisted with one failed or requeued dispatch.
///
/// The value is operator-facing diagnostic text rather than a credential, but
/// its contents stay out of repository error and log rendering; [`Debug`]
/// reports only the byte length and callers must opt into [`Self::as_str`].
#[derive(Clone, Eq, PartialEq)]
pub struct DispatchFailureReason(String);

impl DispatchFailureReason {
    /// Maximum UTF-8 byte length accepted for this value.
    pub const MAX_BYTES: usize = FAILURE_REASON_MAX_BYTES;

    /// Creates the reason after validating the external text without any
    /// truncation.
    ///
    /// # Errors
    ///
    /// Returns [`DispatchFailureReasonError::Empty`] for empty text or
    /// [`DispatchFailureReasonError::TooLong`] carrying only the offending
    /// length when the text exceeds `MAX_BYTES` UTF-8 bytes.
    pub fn parse(value: impl Into<String>) -> Result<Self, DispatchFailureReasonError> {
        let value = value.into();
        if value.is_empty() {
            return Err(DispatchFailureReasonError::Empty);
        }
        let length = value.len();
        if length > Self::MAX_BYTES {
            return Err(DispatchFailureReasonError::TooLong {
                length,
                maximum: Self::MAX_BYTES,
            });
        }
        Ok(Self(value))
    }

    /// Returns the validated failure reason exactly as supplied.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl std::fmt::Debug for DispatchFailureReason {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter
            .debug_struct("DispatchFailureReason")
            .field("length_bytes", &self.0.len())
            .finish()
    }
}

/// Failure to decode a persisted dispatch owner.
#[derive(Clone, Copy, Debug, Error, Eq, PartialEq)]
pub enum DispatchLeaseOwnerError {
    /// The encoded token was not exactly 32 bytes represented as lowercase hex.
    #[error("dispatch owner encoding is {actual} bytes; expected {expected}")]
    InvalidLength { actual: usize, expected: usize },

    /// The encoded token contained a byte outside lowercase hexadecimal.
    #[error("dispatch owner encoding contains a non-lowercase-hex byte at index {index}")]
    InvalidCharacter { index: usize },
}

/// Exact 32-byte ownership token for one dispatch lease.
///
/// The type deliberately implements neither formatting nor cloning traits,
/// and its bytes are cleared when the value is dropped.
pub struct DispatchLeaseOwner([u8; OWNER_BYTES]);

impl DispatchLeaseOwner {
    /// Creates an owner token from exactly 32 caller-generated bytes.
    #[must_use]
    pub const fn new(bytes: [u8; OWNER_BYTES]) -> Self {
        Self(bytes)
    }

    /// Compares two ownership tokens without data-dependent early exit.
    #[must_use]
    pub fn constant_time_eq(&self, other: &Self) -> bool {
        bool::from(self.0.ct_eq(&other.0))
    }

    pub(super) fn to_storage(&self) -> String {
        let mut encoded = String::with_capacity(OWNER_STORAGE_BYTES);
        for &byte in &self.0 {
            encoded.push(hex_digit(byte >> 4));
            encoded.push(hex_digit(byte & 0x0f));
        }
        encoded
    }

    pub(super) fn from_storage(encoded: &str) -> Result<Self, DispatchLeaseOwnerError> {
        if encoded.len() != OWNER_STORAGE_BYTES {
            return Err(DispatchLeaseOwnerError::InvalidLength {
                actual: encoded.len(),
                expected: OWNER_STORAGE_BYTES,
            });
        }

        let encoded = encoded.as_bytes();
        let mut bytes = [0_u8; OWNER_BYTES];
        let (pairs, remainder) = encoded.as_chunks::<2>();
        debug_assert!(remainder.is_empty());
        for (index, pair) in pairs.iter().enumerate() {
            let high = decode_nibble(pair[0], index * 2)?;
            let low = decode_nibble(pair[1], index * 2 + 1)?;
            bytes[index] = (high << 4) | low;
        }
        Ok(Self(bytes))
    }
}

impl Drop for DispatchLeaseOwner {
    fn drop(&mut self) {
        self.0.zeroize();
    }
}

/// One finite attempt to claim the next eligible dispatch.
pub struct ClaimMessageDispatch {
    pub owner: DispatchLeaseOwner,
    pub claimed_at: UnixMillis,
    pub lease_expires_at: UnixMillis,
}

/// A dispatch durably owned until its lease expiry.
pub struct ClaimedMessageDispatch {
    pub message_id: MessageId,
    pub correlation_id: RequestId,
    pub attempt_count: u32,
    pub queued_at: UnixMillis,
    pub available_at: UnixMillis,
    pub owner: DispatchLeaseOwner,
    pub lease_expires_at: UnixMillis,
    pub updated_at: UnixMillis,
}

/// Owner-fenced completion of one claimed dispatch.
pub struct CompleteMessageDispatch {
    /// The dispatch to complete.
    pub message_id: MessageId,
    /// The exact lease holder recorded by the live claim.
    pub owner: DispatchLeaseOwner,
    /// Operation time fencing the lease; the lease must outlive it.
    pub operated_at: UnixMillis,
}

/// Owner-fenced terminal failure of one claimed dispatch.
pub struct FailMessageDispatch {
    /// The dispatch to fail terminally.
    pub message_id: MessageId,
    /// The exact lease holder recorded by the live claim.
    pub owner: DispatchLeaseOwner,
    /// Operation time fencing the lease; the lease must outlive it.
    pub operated_at: UnixMillis,
    /// Bounded failure reason persisted verbatim with the row.
    pub reason: DispatchFailureReason,
}

/// Owner-fenced retryable requeue of one claimed dispatch.
pub struct RequeueMessageDispatch {
    /// The dispatch to requeue for retry.
    pub message_id: MessageId,
    /// The exact lease holder recorded by the live claim.
    pub owner: DispatchLeaseOwner,
    /// Operation time fencing the lease; the lease must outlive it.
    pub operated_at: UnixMillis,
    /// Absolute availability instant supplied by the caller. Every signed
    /// value is valid, including equality or earlier times for immediate
    /// retry.
    pub available_at: UnixMillis,
    /// Bounded failure reason persisted verbatim with the row.
    pub reason: DispatchFailureReason,
}

/// One durable lifecycle transition acknowledged by the store.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct TransitionedMessageDispatch {
    pub message_id: MessageId,
    pub updated_at: UnixMillis,
}

const fn hex_digit(nibble: u8) -> char {
    match nibble {
        0..=9 => (b'0' + nibble) as char,
        10..=15 => (b'a' + nibble - 10) as char,
        _ => unreachable!(),
    }
}

fn decode_nibble(byte: u8, index: usize) -> Result<u8, DispatchLeaseOwnerError> {
    match byte {
        b'0'..=b'9' => Ok(byte - b'0'),
        b'a'..=b'f' => Ok(byte - b'a' + 10),
        _ => Err(DispatchLeaseOwnerError::InvalidCharacter { index }),
    }
}
