//! Atomic claim and recovery of durable message dispatches.

use artisan_domain::{MessageId, RequestId, UnixMillis};
use sea_orm::{
    ColumnTrait, Condition, ConnectionTrait, DbBackend, EntityTrait, QueryFilter, QueryOrder,
    QueryResult, Statement, TransactionTrait,
};
use subtle::ConstantTimeEq;
use thiserror::Error;
use zeroize::Zeroize;

use crate::entities::{self, DispatchState};

use super::{Repository, RepositoryError, corrupt_data, database_error, millis};

const OWNER_BYTES: usize = 32;
const OWNER_STORAGE_BYTES: usize = OWNER_BYTES * 2;

const CLAIM_NEXT_SQL: &str = r"
UPDATE message_dispatches
SET state = 'leased',
    attempt_count = attempt_count + 1,
    lease_owner = ?,
    lease_expires_at_ms = ?,
    last_error = NULL,
    updated_at_ms = ?
WHERE message_id = (
    SELECT message_id
    FROM message_dispatches
    WHERE (state = 'queued' AND available_at_ms <= ?)
       OR (state = 'leased' AND lease_expires_at_ms <= ?)
    ORDER BY available_at_ms ASC, queued_at_ms ASC, message_id ASC
    LIMIT 1
)
  AND ((state = 'queued' AND available_at_ms <= ?)
    OR (state = 'leased' AND lease_expires_at_ms <= ?))
  AND attempt_count < ?
RETURNING message_id,
          correlation_id,
          attempt_count,
          queued_at_ms,
          available_at_ms,
          lease_owner,
          lease_expires_at_ms,
          updated_at_ms
";

/// Failure to decode a persisted dispatch owner.
#[derive(Clone, Copy, Debug, Error, Eq, PartialEq)]
pub enum DispatchLeaseOwnerError {
    /// The encoded token was not exactly 32 bytes represented as lowercase hex.
    #[error("dispatch owner encoding is {actual} bytes; expected {expected}")]
    InvalidLength { actual: usize, expected: usize },

    /// The encoded token contained a byte outside lowercase hexadecimal.
    #[error("dispatch owner encoding contains a non-lowercase-hex byte at index {index}")]
    InvalidCharacter { index: usize },
}

/// Exact 32-byte ownership token for one dispatch lease.
///
/// The type deliberately implements neither formatting nor cloning traits,
/// and its bytes are cleared when the value is dropped.
pub struct DispatchLeaseOwner([u8; OWNER_BYTES]);

impl DispatchLeaseOwner {
    /// Creates an owner token from exactly 32 caller-generated bytes.
    #[must_use]
    pub const fn new(bytes: [u8; OWNER_BYTES]) -> Self {
        Self(bytes)
    }

    /// Compares two ownership tokens without data-dependent early exit.
    #[must_use]
    pub fn constant_time_eq(&self, other: &Self) -> bool {
        bool::from(self.0.ct_eq(&other.0))
    }

    fn to_storage(&self) -> String {
        let mut encoded = String::with_capacity(OWNER_STORAGE_BYTES);
        for &byte in &self.0 {
            encoded.push(hex_digit(byte >> 4));
            encoded.push(hex_digit(byte & 0x0f));
        }
        encoded
    }

    fn from_storage(encoded: &str) -> Result<Self, DispatchLeaseOwnerError> {
        if encoded.len() != OWNER_STORAGE_BYTES {
            return Err(DispatchLeaseOwnerError::InvalidLength {
                actual: encoded.len(),
                expected: OWNER_STORAGE_BYTES,
            });
        }

        let encoded = encoded.as_bytes();
        let mut bytes = [0_u8; OWNER_BYTES];
        let (pairs, remainder) = encoded.as_chunks::<2>();
        debug_assert!(remainder.is_empty());
        for (index, pair) in pairs.iter().enumerate() {
            let high = decode_nibble(pair[0], index * 2)?;
            let low = decode_nibble(pair[1], index * 2 + 1)?;
            bytes[index] = (high << 4) | low;
        }
        Ok(Self(bytes))
    }
}

impl Drop for DispatchLeaseOwner {
    fn drop(&mut self) {
        self.0.zeroize();
    }
}

/// One finite attempt to claim the next eligible dispatch.
pub struct ClaimMessageDispatch {
    pub owner: DispatchLeaseOwner,
    pub claimed_at: UnixMillis,
    pub lease_expires_at: UnixMillis,
}

/// A dispatch durably owned until its lease expiry.
pub struct ClaimedMessageDispatch {
    pub message_id: MessageId,
    pub correlation_id: RequestId,
    pub attempt_count: u32,
    pub queued_at: UnixMillis,
    pub available_at: UnixMillis,
    pub owner: DispatchLeaseOwner,
    pub lease_expires_at: UnixMillis,
    pub updated_at: UnixMillis,
}

impl Repository {
    /// Atomically claims the oldest eligible queued or expired dispatch.
    ///
    /// The transaction's first statement both selects and updates one row.
    /// SQLite therefore serializes competing writers before either can
    /// observe a claimable result. A leased row becomes eligible again only
    /// when its persisted expiry is at or before `claimed_at`.
    ///
    /// # Errors
    ///
    /// Returns a typed lease-window error before opening a transaction. A
    /// database, corrupt-data, invariant, or exhausted-attempt error rolls
    /// back the claim before it is returned.
    pub async fn claim_next_message_dispatch(
        &self,
        claim: ClaimMessageDispatch,
    ) -> Result<Option<ClaimedMessageDispatch>, RepositoryError> {
        let claimed_at_ms = millis(claim.claimed_at);
        let lease_expires_at_ms = millis(claim.lease_expires_at);
        if lease_expires_at_ms <= claimed_at_ms {
            return Err(RepositoryError::InvalidDispatchLeaseWindow {
                claimed_at_ms,
                lease_expires_at_ms,
            });
        }

        let encoded_owner = claim.owner.to_storage();
        let transaction = self
            .database
            .begin()
            .await
            .map_err(|source| database_error("begin message-dispatch claim", source))?;
        let statement = Statement::from_sql_and_values(
            DbBackend::Sqlite,
            CLAIM_NEXT_SQL,
            [
                encoded_owner.into(),
                lease_expires_at_ms.into(),
                claimed_at_ms.into(),
                claimed_at_ms.into(),
                claimed_at_ms.into(),
                claimed_at_ms.into(),
                claimed_at_ms.into(),
                i64::from(i32::MAX).into(),
            ],
        );
        let returned = transaction
            .query_one_raw(statement)
            .await
            .map_err(|source| database_error("claim next message dispatch", source));
        let returned = match returned {
            Ok(returned) => returned,
            Err(error) => return rollback_claim(transaction, error).await,
        };

        let Some(row) = returned else {
            let result = classify_unclaimed(&transaction, claim.claimed_at).await;
            return finish_unclaimed(transaction, result).await;
        };
        let claimed = match claimed_from_row(&row, &claim.owner, claimed_at_ms, lease_expires_at_ms)
        {
            Ok(claimed) => claimed,
            Err(error) => return rollback_claim(transaction, error).await,
        };

        transaction
            .commit()
            .await
            .map_err(|source| database_error("commit message-dispatch claim", source))?;
        Ok(Some(claimed))
    }
}

fn claimed_from_row(
    row: &QueryResult,
    expected_owner: &DispatchLeaseOwner,
    claimed_at_ms: i64,
    lease_expires_at_ms: i64,
) -> Result<ClaimedMessageDispatch, RepositoryError> {
    let message_id = MessageId::parse(row_value::<String>(row, 0, "message_id")?)
        .map_err(|error| corrupt_data("message_dispatches", "message_id", &error))?;
    let correlation_id = RequestId::parse(row_value::<String>(row, 1, "correlation_id")?)
        .map_err(|error| corrupt_data("message_dispatches", "correlation_id", &error))?;
    let attempt_count = row_value::<i64>(row, 2, "attempt_count")?;
    let attempt_count = u32::try_from(attempt_count)
        .map_err(|error| corrupt_data("message_dispatches", "attempt_count", &error))?;
    if attempt_count == 0 {
        return Err(RepositoryError::Invariant {
            reason: "claimed dispatch retained a zero attempt count",
        });
    }
    let queued_at = UnixMillis::from_millis(row_value(row, 3, "queued_at_ms")?);
    let available_at = UnixMillis::from_millis(row_value(row, 4, "available_at_ms")?);
    let owner = DispatchLeaseOwner::from_storage(&row_value::<String>(row, 5, "lease_owner")?)
        .map_err(|error| corrupt_data("message_dispatches", "lease_owner", &error))?;
    if !owner.constant_time_eq(expected_owner) {
        return Err(RepositoryError::Invariant {
            reason: "claimed dispatch returned a different lease owner",
        });
    }
    let returned_expiry = row_value::<i64>(row, 6, "lease_expires_at_ms")?;
    let returned_update = row_value::<i64>(row, 7, "updated_at_ms")?;
    if returned_expiry != lease_expires_at_ms || returned_update != claimed_at_ms {
        return Err(RepositoryError::Invariant {
            reason: "claimed dispatch returned inconsistent lease timestamps",
        });
    }

    Ok(ClaimedMessageDispatch {
        message_id,
        correlation_id,
        attempt_count,
        queued_at,
        available_at,
        owner,
        lease_expires_at: UnixMillis::from_millis(returned_expiry),
        updated_at: UnixMillis::from_millis(returned_update),
    })
}

async fn classify_unclaimed(
    database: &impl ConnectionTrait,
    claimed_at: UnixMillis,
) -> Result<(), RepositoryError> {
    let claimed_at_ms = millis(claimed_at);
    let eligible = Condition::any()
        .add(
            Condition::all()
                .add(entities::message_dispatch::Column::State.eq(DispatchState::Queued))
                .add(entities::message_dispatch::Column::AvailableAtMs.lte(claimed_at_ms)),
        )
        .add(
            Condition::all()
                .add(entities::message_dispatch::Column::State.eq(DispatchState::Leased))
                .add(entities::message_dispatch::Column::LeaseExpiresAtMs.lte(claimed_at_ms)),
        );
    let candidate = entities::message_dispatch::Entity::find()
        .filter(eligible)
        .order_by_asc(entities::message_dispatch::Column::AvailableAtMs)
        .order_by_asc(entities::message_dispatch::Column::QueuedAtMs)
        .order_by_asc(entities::message_dispatch::Column::MessageId)
        .one(database)
        .await
        .map_err(|source| database_error("classify unclaimed message dispatch", source))?;

    let Some(candidate) = candidate else {
        return Ok(());
    };
    let message_id = MessageId::parse(candidate.message_id)
        .map_err(|error| corrupt_data("message_dispatches", "message_id", &error))?;
    if candidate.attempt_count == i32::MAX {
        return Err(RepositoryError::DispatchAttemptLimit { message_id });
    }
    Err(RepositoryError::Invariant {
        reason: "eligible dispatch was not changed by its atomic claim statement",
    })
}

async fn finish_unclaimed(
    transaction: sea_orm::DatabaseTransaction,
    result: Result<(), RepositoryError>,
) -> Result<Option<ClaimedMessageDispatch>, RepositoryError> {
    match result {
        Ok(()) => {
            transaction
                .commit()
                .await
                .map_err(|source| database_error("finish empty message-dispatch claim", source))?;
            Ok(None)
        }
        Err(error) => rollback_claim(transaction, error).await,
    }
}

async fn rollback_claim<T>(
    transaction: sea_orm::DatabaseTransaction,
    error: RepositoryError,
) -> Result<T, RepositoryError> {
    transaction
        .rollback()
        .await
        .map_err(|source| database_error("roll back message-dispatch claim", source))?;
    Err(error)
}

fn row_value<T>(row: &QueryResult, index: usize, field: &'static str) -> Result<T, RepositoryError>
where
    T: sea_orm::TryGetable,
{
    row.try_get_by_index(index)
        .map_err(|error| corrupt_data("message_dispatches", field, &error))
}

const fn hex_digit(nibble: u8) -> char {
    match nibble {
        0..=9 => (b'0' + nibble) as char,
        10..=15 => (b'a' + nibble - 10) as char,
        _ => unreachable!(),
    }
}

fn decode_nibble(byte: u8, index: usize) -> Result<u8, DispatchLeaseOwnerError> {
    match byte {
        b'0'..=b'9' => Ok(byte - b'0'),
        b'a'..=b'f' => Ok(byte - b'a' + 10),
        _ => Err(DispatchLeaseOwnerError::InvalidCharacter { index }),
    }
}
