//! Atomic launch of one claimed first message into its durable conversation
//! graph and assistant-run launching state.
//!
//! [`Repository::launch_claimed_run`] is the single transactional boundary
//! between a claimed dispatch and the run that will execute it: one
//! full-snapshot fenced dispatch transition plus the thread's conversation
//! state, two shared renderer ordinals, the initial pending turn, the
//! completed user item, two initial replay patches, and the `launching`
//! assistant-run row commit together or not at all. There is deliberately
//! no separate public mark-running step and no requeue API: a NULL provider
//! binding alone is NOT proof that no external effect occurred, and a failed
//! run paired with a requeued dispatch would contradict the permanent unique
//! origin indexes. Only the live dispatcher, after it has torn down a
//! provider that never started, may fail the pair terminally
//! ([`crate::Repository::fail_unstarted_run`]); unknown outcomes stay with
//! lease-expiry recovery.
//!
//! Every input is borrowed so a caller whose transaction outcome is unknown
//! may retry the identical call with the same identities, start key, and
//! credentials. An exact replay answers
//! [`LaunchClaimedRunOutcome::AlreadyStarted`] — durable receipt information
//! derived from the originally persisted rows, which must never be
//! interpreted as authority to contact a provider again.

mod launch;
mod replay;
mod steered;
mod unstarted;

use artisan_domain::{MessageId, PatchId, RunId};
use sea_orm::{ActiveModelTrait, ActiveValue::Set, EntityTrait};
use subtle::ConstantTimeEq;
use thiserror::Error;
use zeroize::Zeroize;

use crate::entities;
use crate::entities::{
    ConversationItemKind, ConversationPatchKind, EntityLifecycle, OpaqueBytes, OrdinalKind,
};

use super::{RepositoryError, database_error, negative_counter};

pub use launch::{LaunchClaimedRun, LaunchClaimedRunOutcome, LaunchedRunReceipt};
pub use steered::{ProjectSteeredMessage, ProjectSteeredMessageOutcome, SteeredMessageReceipt};
pub use unstarted::{FailUnstartedRun, FailUnstartedRunOutcome};

/// Exact byte length of every run-launch capability and of the start key.
pub(super) const RUN_CAPABILITY_BYTES: usize = 32;

/// First generation of a freshly launched assistant run.
const INITIAL_RUN_GENERATION: i64 = 1;

/// Exact 32-byte deduplication key of one assistant-run launch.
///
/// The wrapper deliberately implements neither formatting nor duplication
/// traits and exposes no public raw-byte accessor; its bytes are cleared
/// when the value is dropped.
pub struct RunStartKey([u8; RUN_CAPABILITY_BYTES]);

impl RunStartKey {
    /// Creates a start key from exactly 32 caller-generated bytes.
    #[must_use]
    pub const fn new(bytes: [u8; RUN_CAPABILITY_BYTES]) -> Self {
        Self(bytes)
    }

    /// Compares two start keys without data-dependent early exit.
    #[must_use]
    pub fn constant_time_eq(&self, other: &Self) -> bool {
        bool::from(self.0.ct_eq(&other.0))
    }

    pub(super) fn expose(&self) -> &[u8; RUN_CAPABILITY_BYTES] {
        &self.0
    }
}

impl Drop for RunStartKey {
    fn drop(&mut self) {
        self.0.zeroize();
    }
}

/// One exact 32-byte named run capability.
pub(super) struct RunCapability([u8; RUN_CAPABILITY_BYTES]);

impl RunCapability {
    const fn new(bytes: [u8; RUN_CAPABILITY_BYTES]) -> Self {
        Self(bytes)
    }

    pub(super) const fn expose(&self) -> &[u8; RUN_CAPABILITY_BYTES] {
        &self.0
    }

    pub(super) fn matches_stored(&self, stored: Option<&OpaqueBytes>) -> bool {
        stored.is_some_and(|stored| stored_bytes_match(stored, self.expose()))
    }
}

impl Drop for RunCapability {
    fn drop(&mut self) {
        self.0.zeroize();
    }
}

/// Named owner/lease/claim capabilities of one assistant-run launch.
///
/// The three arrays are exact 32-byte secrets persisted as raw BLOBs. The
/// aggregate implements neither formatting nor duplication traits, exposes
/// no public raw-byte accessor, and clears its bytes when dropped.
pub struct RunLaunchCredentials {
    owner: RunCapability,
    lease: RunCapability,
    claim_token: RunCapability,
}

impl RunLaunchCredentials {
    /// Creates the named capability trio from exactly sized caller arrays.
    #[must_use]
    pub const fn new(
        owner: [u8; RUN_CAPABILITY_BYTES],
        lease: [u8; RUN_CAPABILITY_BYTES],
        claim_token: [u8; RUN_CAPABILITY_BYTES],
    ) -> Self {
        Self {
            owner: RunCapability::new(owner),
            lease: RunCapability::new(lease),
            claim_token: RunCapability::new(claim_token),
        }
    }

    pub(super) fn parts(&self) -> (&RunCapability, &RunCapability, &RunCapability) {
        (&self.owner, &self.lease, &self.claim_token)
    }

    pub(super) fn matches_stored(
        &self,
        owner: Option<&OpaqueBytes>,
        lease: Option<&OpaqueBytes>,
        claim_token: Option<&OpaqueBytes>,
    ) -> bool {
        let (owner_capability, lease_capability, claim_capability) = self.parts();
        owner_capability.matches_stored(owner)
            && lease_capability.matches_stored(lease)
            && claim_capability.matches_stored(claim_token)
    }
}

/// Capability-specific failures of [`Repository::launch_claimed_run`].
///
/// Existing repository-layer rejections surface through
/// [`RunLaunchError::Repository`] with their original typed source; nothing
/// here leaks capability bytes or accepted bodies.
#[derive(Debug, Error)]
pub enum RunLaunchError {
    /// The supplied run identity does not exist.
    #[error("run `{run_id}` does not exist")]
    RunNotFound {
        /// Supplied run identity.
        run_id: RunId,
    },
    /// The run advanced beyond its launching state before this call.
    #[error("run `{run_id}` already advanced beyond its launching state")]
    RunNotLaunchable {
        /// Supplied run identity.
        run_id: RunId,
    },
    /// The stored start key or one of the three run tokens did not match.
    #[error("run `{run_id}` launch start key or tokens did not match")]
    CredentialMismatch {
        /// Supplied run identity.
        run_id: RunId,
    },
    /// The supplied claim snapshot no longer describes persisted state.
    #[error("claimed dispatch snapshot for `{message_id}` no longer matches")]
    SnapshotMismatch {
        /// Claimed message identity.
        message_id: MessageId,
    },
    /// A colliding or contradictory durable identity was found.
    #[error("launch identity conflict: {reason}")]
    IdentityConflict {
        /// Bounded payload-free reason label.
        reason: &'static str,
    },
    /// A shared counter could not advance within its checked range.
    #[error("{counter} allocation overflowed at {value}")]
    CounterOverflow {
        /// Counter that could not advance.
        counter: &'static str,
        /// Value at the boundary.
        value: i64,
    },
    /// An existing repository rejection surfaced unchanged.
    #[error(transparent)]
    Repository(#[from] RepositoryError),
}

struct InitialPatchProjection<'a> {
    patch_id: &'a PatchId,
    turn_id: &'a str,
    item_id: Option<&'a str>,
    ordinal: i64,
    lifecycle: EntityLifecycle,
    item_kind: Option<ConversationItemKind>,
    body: Option<String>,
}

/// Reads or creates the thread's conversation counters under the writer.
///
/// An absent row means this is the conversation's first launch: the initial
/// counters are zero and the row is created transactionally here. Existing
/// rows are validated (non-negative counters, chronology against the launch
/// observation) but never rewritten by this helper.
async fn obtain_conversation_state(
    transaction: &sea_orm::DatabaseTransaction,
    thread_id: &str,
    operated_at_ms: i64,
) -> Result<(i64, i64), RunLaunchError> {
    if let Some(state) = entities::conversation_state::Entity::find_by_id(thread_id)
        .one(transaction)
        .await
        .map_err(|source| {
            RunLaunchError::Repository(database_error("load conversation state", source))
        })?
    {
        if state.next_renderer_ordinal < 0 {
            return Err(RunLaunchError::Repository(negative_counter(
                "next_renderer_ordinal",
            )));
        }
        if state.last_patch_sequence < 0 {
            return Err(RunLaunchError::Repository(negative_counter(
                "last_patch_sequence",
            )));
        }
        if operated_at_ms < state.updated_at_ms {
            return Err(RunLaunchError::Repository(
                RepositoryError::InvalidChronology {
                    earlier_field: "conversation_state.updated_at_ms",
                    later_field: "launch operated_at",
                },
            ));
        }
        Ok((state.next_renderer_ordinal, state.last_patch_sequence))
    } else {
        entities::conversation_state::ActiveModel {
            thread_id: Set(thread_id.to_owned()),
            next_renderer_ordinal: Set(0),
            last_patch_sequence: Set(0),
            updated_at_ms: Set(operated_at_ms),
        }
        .insert(transaction)
        .await
        .map_err(|source| {
            RunLaunchError::Repository(database_error("create conversation state", source))
        })?;
        Ok((0, 0))
    }
}

/// Projection values shared by the launched turn and user item inserts.
struct LaunchedProjections<'a> {
    thread_id: &'a str,
    turn_id: &'a str,
    item_id: &'a str,
    message_id: &'a str,
    body: &'a str,
    turn_ordinal: i64,
    item_ordinal: i64,
}

async fn insert_item_projection(
    transaction: &sea_orm::DatabaseTransaction,
    projections: &LaunchedProjections<'_>,
    operated_at_ms: i64,
) -> Result<(), RunLaunchError> {
    entities::conversation_item::Entity::insert(entities::conversation_item::ActiveModel {
        item_id: Set(projections.item_id.to_owned()),
        thread_id: Set(projections.thread_id.to_owned()),
        turn_id: Set(projections.turn_id.to_owned()),
        ordinal: Set(projections.item_ordinal),
        kind: Set(OrdinalKind::Item),
        revision: Set(0),
        lifecycle: Set(EntityLifecycle::Completed),
        item_kind: Set(ConversationItemKind::UserMessage),
        source_message_id: Set(Some(projections.message_id.to_owned())),
        run_id: Set(None),
        native_item_key: Set(None),
        phase: Set(None),
        body: Set(projections.body.to_owned()),
        created_at_ms: Set(operated_at_ms),
        updated_at_ms: Set(operated_at_ms),
    })
    .exec(transaction)
    .await
    .map_err(|source| {
        RunLaunchError::Repository(database_error("insert launched user item", source))
    })?;
    Ok(())
}

async fn insert_initial_patch(
    transaction: &sea_orm::DatabaseTransaction,
    thread_id: &str,
    sequence: i64,
    kind: ConversationPatchKind,
    recorded_at_ms: i64,
    projection: InitialPatchProjection<'_>,
) -> Result<(), RunLaunchError> {
    entities::conversation_patch::Entity::insert(entities::conversation_patch::ActiveModel {
        patch_id: Set(projection.patch_id.as_str().to_owned()),
        thread_id: Set(thread_id.to_owned()),
        sequence: Set(sequence),
        kind: Set(kind),
        revision: Set(0),
        recorded_at_ms: Set(recorded_at_ms),
        turn_id: Set(Some(projection.turn_id.to_owned())),
        item_id: Set(projection.item_id.map(str::to_owned)),
        ordinal: Set(Some(projection.ordinal)),
        lifecycle: Set(Some(projection.lifecycle)),
        item_kind: Set(projection.item_kind),
        run_id: Set(None),
        phase: Set(None),
        body: Set(projection.body),
        fragment: Set(None),
        entity_created_at_ms: Set(Some(recorded_at_ms)),
        entity_updated_at_ms: Set(Some(recorded_at_ms)),
    })
    .exec(transaction)
    .await
    .map_err(|source| RunLaunchError::Repository(database_error("insert initial patch", source)))?;
    Ok(())
}

async fn insert_ordinal(
    transaction: &sea_orm::DatabaseTransaction,
    thread_id: &str,
    ordinal: i64,
    kind: OrdinalKind,
    entity_id: &str,
) -> Result<(), RunLaunchError> {
    entities::conversation_ordinal::Entity::insert(entities::conversation_ordinal::ActiveModel {
        thread_id: Set(thread_id.to_owned()),
        ordinal: Set(ordinal),
        kind: Set(kind),
        entity_id: Set(entity_id.to_owned()),
    })
    .exec(transaction)
    .await
    .map_err(|source| {
        RunLaunchError::Repository(database_error("insert shared ordinal", source))
    })?;
    Ok(())
}

pub(super) fn stored_bytes_match(
    stored: &OpaqueBytes,
    supplied: &[u8; RUN_CAPABILITY_BYTES],
) -> bool {
    stored.as_slice().len() == RUN_CAPABILITY_BYTES
        && bool::from(stored.as_slice().ct_eq(supplied.as_slice()))
}

fn counter_overflow(counter: &'static str, value: i64) -> RunLaunchError {
    RunLaunchError::CounterOverflow { counter, value }
}
