//! Atomic launch of one claimed first message into its durable conversation
//! graph and assistant-run launching state.
//!
//! [`Repository::launch_claimed_run`] is the single transactional boundary
//! between a claimed dispatch and the run that will execute it: one
//! full-snapshot fenced dispatch transition plus the thread's conversation
//! state, two shared renderer ordinals, the initial pending turn, the
//! completed user item, two initial replay patches, and the `launching`
//! assistant-run row commit together or not at all. There is deliberately
//! no separate public mark-running step and no launch-failure or requeue API
//! in this slice: a NULL provider binding is NOT proof that no external
//! effect occurred, and a failed run paired with a requeued dispatch would
//! contradict the permanent unique origin indexes. Unknown external
//! outcomes, recovery, and provider binding are later explicit transaction
//! designs.
//!
//! Every input is borrowed so a caller whose transaction outcome is unknown
//! may retry the identical call with the same identities, start key, and
//! credentials. An exact replay answers
//! [`LaunchClaimedRunOutcome::AlreadyStarted`] — durable receipt information
//! derived from the originally persisted rows, which must never be
//! interpreted as authority to contact a provider again.

use artisan_domain::{
    ConversationCursor, ItemId, MessageBody, MessageId, PatchId, RunId, ThreadId, TurnId,
    UnixMillis,
};
use sea_orm::{
    ActiveModelTrait, ActiveValue::Set, ColumnTrait, ConnectionTrait, DbBackend, EntityTrait,
    QueryFilter, Statement, TransactionTrait,
};
use subtle::ConstantTimeEq;
use thiserror::Error;
use zeroize::Zeroize;

use crate::entities;
use crate::entities::{
    AssistantRunLifecycle, ConversationItemKind, ConversationPatchKind, DispatchState,
    EntityLifecycle, OpaqueBytes, OrdinalKind,
};

use super::message_dispatch::DispatchLeaseOwner;
use super::{
    ClaimedMessageDispatch, Repository, RepositoryError, corrupt_data, database_error, millis,
};

/// Exact byte length of every run-launch capability and of the start key.
pub(super) const RUN_CAPABILITY_BYTES: usize = 32;

/// Shared renderer ordinals consumed by one launch (one turn, one item).
const LAUNCH_ORDINALS: i64 = 2;

/// Durable replay patches written by one launch.
const LAUNCH_PATCHES: i64 = 2;

/// First generation of a freshly launched assistant run.
const INITIAL_RUN_GENERATION: i64 = 1;

const LAUNCH_FENCE_SQL: &str = r"
UPDATE message_dispatches
SET state = 'running',
    updated_at_ms = ?
WHERE message_id = ?
  AND correlation_id = ?
  AND attempt_count = ?
  AND queued_at_ms = ?
  AND available_at_ms = ?
  AND state = 'leased'
  AND lease_owner = ?
  AND lease_expires_at_ms = ?
  AND updated_at_ms = ?
  AND updated_at_ms <= ?
  AND lease_expires_at_ms > ?
RETURNING message_id
";

/// Exact 32-byte deduplication key of one assistant-run launch.
///
/// The wrapper deliberately implements neither formatting nor duplication
/// traits and exposes no public raw-byte accessor; its bytes are cleared
/// when the value is dropped.
pub struct RunStartKey([u8; RUN_CAPABILITY_BYTES]);

impl RunStartKey {
    /// Creates a start key from exactly 32 caller-generated bytes.
    #[must_use]
    pub const fn new(bytes: [u8; RUN_CAPABILITY_BYTES]) -> Self {
        Self(bytes)
    }

    /// Compares two start keys without data-dependent early exit.
    #[must_use]
    pub fn constant_time_eq(&self, other: &Self) -> bool {
        bool::from(self.0.ct_eq(&other.0))
    }

    pub(super) fn expose(&self) -> &[u8; RUN_CAPABILITY_BYTES] {
        &self.0
    }
}

impl Drop for RunStartKey {
    fn drop(&mut self) {
        self.0.zeroize();
    }
}

/// One exact 32-byte named run capability.
pub(super) struct RunCapability([u8; RUN_CAPABILITY_BYTES]);

impl RunCapability {
    const fn new(bytes: [u8; RUN_CAPABILITY_BYTES]) -> Self {
        Self(bytes)
    }

    pub(super) const fn expose(&self) -> &[u8; RUN_CAPABILITY_BYTES] {
        &self.0
    }

    pub(super) fn matches_stored(&self, stored: Option<&OpaqueBytes>) -> bool {
        stored.is_some_and(|stored| stored_bytes_match(stored, self.expose()))
    }
}

impl Drop for RunCapability {
    fn drop(&mut self) {
        self.0.zeroize();
    }
}

/// Named owner/lease/claim capabilities of one assistant-run launch.
///
/// The three arrays are exact 32-byte secrets persisted as raw BLOBs. The
/// aggregate implements neither formatting nor duplication traits, exposes
/// no public raw-byte accessor, and clears its bytes when dropped.
pub struct RunLaunchCredentials {
    owner: RunCapability,
    lease: RunCapability,
    claim_token: RunCapability,
}

impl RunLaunchCredentials {
    /// Creates the named capability trio from exactly sized caller arrays.
    #[must_use]
    pub const fn new(
        owner: [u8; RUN_CAPABILITY_BYTES],
        lease: [u8; RUN_CAPABILITY_BYTES],
        claim_token: [u8; RUN_CAPABILITY_BYTES],
    ) -> Self {
        Self {
            owner: RunCapability::new(owner),
            lease: RunCapability::new(lease),
            claim_token: RunCapability::new(claim_token),
        }
    }

    pub(super) fn parts(&self) -> (&RunCapability, &RunCapability, &RunCapability) {
        (&self.owner, &self.lease, &self.claim_token)
    }

    pub(super) fn matches_stored(
        &self,
        owner: Option<&OpaqueBytes>,
        lease: Option<&OpaqueBytes>,
        claim_token: Option<&OpaqueBytes>,
    ) -> bool {
        let (owner_capability, lease_capability, claim_capability) = self.parts();
        owner_capability.matches_stored(owner)
            && lease_capability.matches_stored(lease)
            && claim_capability.matches_stored(claim_token)
    }
}

/// Borrowed inputs of one atomic claimed-dispatch launch.
///
/// Nothing here is cloned away from the caller: an unknown transaction
/// outcome can be retried verbatim with the same values.
pub struct LaunchClaimedRun<'a> {
    /// The exact live claim returned by the atomic dispatch claim.
    pub claimed: &'a ClaimedMessageDispatch,
    /// Caller-minted identity of the assistant run to launch.
    pub run_id: &'a RunId,
    /// Caller-minted identity of the launched turn.
    pub turn_id: &'a TurnId,
    /// Caller-minted identity of the completed user item.
    pub item_id: &'a ItemId,
    /// Caller-minted identity of the initial `turn_upsert` patch.
    pub first_patch_id: &'a PatchId,
    /// Caller-minted identity of the initial `item_upsert` patch.
    pub second_patch_id: &'a PatchId,
    /// Caller-owned monotonic operation time stamped on every effect.
    pub operated_at: UnixMillis,
    /// Exact 32-byte deduplication key for this launch.
    pub run_start_key: &'a RunStartKey,
    /// Named owner/lease/claim capabilities persisted as raw BLOBs.
    pub credentials: &'a RunLaunchCredentials,
}

/// Payload-free durable receipt of one launch attempt.
///
/// It carries identities and counters only — never the accepted body, never
/// a capability, and never any provider authority.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct LaunchedRunReceipt {
    /// Launched run identity.
    pub run_id: RunId,
    /// Thread owning the launched conversation graph.
    pub thread_id: ThreadId,
    /// Accepted message the run originates from.
    pub message_id: MessageId,
    /// Launched turn identity.
    pub turn_id: TurnId,
    /// Completed user item identity.
    pub item_id: ItemId,
    /// Generation recorded on the launching run.
    pub generation: i64,
    /// Patch cursor produced by the launch's own sequence allocation.
    pub resulting_cursor: ConversationCursor,
}

/// Typed outcome of one launch call.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum LaunchClaimedRunOutcome {
    /// This transaction created the graph and moved the dispatch to running.
    Started(LaunchedRunReceipt),
    /// An earlier identical transaction already launched exactly this run;
    /// durable receipt information only, never provider authority.
    AlreadyStarted(LaunchedRunReceipt),
}

/// Capability-specific failures of [`Repository::launch_claimed_run`].
///
/// Existing repository-layer rejections surface through
/// [`RunLaunchError::Repository`] with their original typed source; nothing
/// here leaks capability bytes or accepted bodies.
#[derive(Debug, Error)]
pub enum RunLaunchError {
    /// The supplied run identity does not exist.
    #[error("run `{run_id}` does not exist")]
    RunNotFound {
        /// Supplied run identity.
        run_id: RunId,
    },
    /// The run advanced beyond its launching state before this call.
    #[error("run `{run_id}` already advanced beyond its launching state")]
    RunNotLaunchable {
        /// Supplied run identity.
        run_id: RunId,
    },
    /// The stored start key or one of the three run tokens did not match.
    #[error("run `{run_id}` launch start key or tokens did not match")]
    CredentialMismatch {
        /// Supplied run identity.
        run_id: RunId,
    },
    /// The supplied claim snapshot no longer describes persisted state.
    #[error("claimed dispatch snapshot for `{message_id}` no longer matches")]
    SnapshotMismatch {
        /// Claimed message identity.
        message_id: MessageId,
    },
    /// A colliding or contradictory durable identity was found.
    #[error("launch identity conflict: {reason}")]
    IdentityConflict {
        /// Bounded payload-free reason label.
        reason: &'static str,
    },
    /// A shared counter could not advance within its checked range.
    #[error("{counter} allocation overflowed at {value}")]
    CounterOverflow {
        /// Counter that could not advance.
        counter: &'static str,
        /// Value at the boundary.
        value: i64,
    },
    /// An existing repository rejection surfaced unchanged.
    #[error(transparent)]
    Repository(#[from] RepositoryError),
}

struct InitialPatchProjection<'a> {
    patch_id: &'a PatchId,
    turn_id: &'a str,
    item_id: Option<&'a str>,
    ordinal: i64,
    lifecycle: EntityLifecycle,
    item_kind: Option<ConversationItemKind>,
    body: Option<String>,
}

impl Repository {
    /// Launches one claimed dispatch into its durable conversation graph.
    ///
    /// The transaction's first statement is one conditional UPDATE fencing
    /// the exact claimed snapshot — message id, correlation id, attempt
    /// count, queued/available times, hex-encoded owner, exact lease expiry,
    /// exact claimed update stamp, `updated_at <= operated_at`, and
    /// `lease_expiry > operated_at` — from `leased` to `running`. RUNNING
    /// keeps its owner and expiry; only the update stamp moves to
    /// `operated_at`. When the fence matches no row, the same transaction
    /// diagnoses an exact replay against the originally persisted graph,
    /// requiring the identical run identity, start key, origin tuple,
    /// projections, patch identities, launch-time stamps, still-launching
    /// lifecycle, generation 1, and all three matching tokens on a
    /// still-RUNNING dispatch with the matching claim identity, and answers
    /// [`LaunchClaimedRunOutcome::AlreadyStarted`]. Every other divergence is
    /// a typed conflict, and any failure rolls back the fenced write together
    /// with all graph effects.
    ///
    /// The accepted message's stored thread and body are loaded and used
    /// verbatim; chronology is checked against the message acceptance, thread
    /// creation, and existing conversation-state stamp. Counters advance by
    /// checked arithmetic only. This operation claims nothing about provider
    /// acceptance or UI visibility, and it offers no failure, requeue, or
    /// recovery path: unknown external outcomes stay a later explicit design.
    ///
    /// # Errors
    ///
    /// Returns [`RunLaunchError::Repository`] for existing typed repository
    /// rejections (unknown dispatch, wrong owner, expired lease, chronology,
    /// corrupt data), [`RunLaunchError::SnapshotMismatch`] for stale claim
    /// snapshots, [`RunLaunchError::CredentialMismatch`] for mismatching
    /// start keys or tokens, [`RunLaunchError::IdentityConflict`] for
    /// colliding durable identities, [`RunLaunchError::RunNotFound`] and
    /// [`RunLaunchError::RunNotLaunchable`] for unknown or already-advanced
    /// runs, and [`RunLaunchError::CounterOverflow`] when either shared
    /// counter lacks remaining range.
    pub async fn launch_claimed_run(
        &self,
        command: LaunchClaimedRun<'_>,
    ) -> Result<LaunchClaimedRunOutcome, RunLaunchError> {
        let operated_at_ms = millis(command.operated_at);
        let claimed = command.claimed;

        if claimed.attempt_count == 0 || i32::try_from(claimed.attempt_count).is_err() {
            return Err(RunLaunchError::SnapshotMismatch {
                message_id: claimed.message_id.clone(),
            });
        }
        if operated_at_ms < millis(claimed.updated_at) {
            return Err(RunLaunchError::Repository(
                RepositoryError::InvalidChronology {
                    earlier_field: "claimed dispatch updated_at",
                    later_field: "launch operated_at",
                },
            ));
        }
        // Same-call identity collisions are invisible to per-identity
        // vacancy queries: two individually vacant identities can still
        // collide with each other inside one launch. They are rejected
        // before any statement runs.
        if command.turn_id.as_str() == command.item_id.as_str() {
            return Err(RunLaunchError::IdentityConflict {
                reason: "turn and item identities collide within one launch",
            });
        }
        if command.first_patch_id.as_str() == command.second_patch_id.as_str() {
            return Err(RunLaunchError::IdentityConflict {
                reason: "initial patch identities collide within one launch",
            });
        }

        let encoded_owner = claimed.owner.to_storage();
        let transaction = self.database.begin().await.map_err(|source| {
            RunLaunchError::Repository(database_error("begin run launch", source))
        })?;

        let statement = Statement::from_sql_and_values(
            DbBackend::Sqlite,
            LAUNCH_FENCE_SQL,
            [
                operated_at_ms.into(),
                claimed.message_id.as_str().into(),
                claimed.correlation_id.as_str().into(),
                i64::from(claimed.attempt_count).into(),
                millis(claimed.queued_at).into(),
                millis(claimed.available_at).into(),
                encoded_owner.into(),
                millis(claimed.lease_expires_at).into(),
                millis(claimed.updated_at).into(),
                operated_at_ms.into(),
                operated_at_ms.into(),
            ],
        );
        let fenced = transaction
            .query_one_raw(statement)
            .await
            .map_err(|source| {
                RunLaunchError::Repository(database_error("fence run launch", source))
            });
        let fenced = match fenced {
            Ok(fenced) => fenced,
            Err(error) => return rollback_launch(transaction, error).await,
        };

        if fenced.is_none() {
            let diagnosed = classify_unfenced_launch(&transaction, &command, operated_at_ms).await;
            return finish_diagnosed_launch(transaction, diagnosed).await;
        }

        let launched = build_launched_graph(&transaction, &command, operated_at_ms).await;
        match launched {
            Ok(receipt) => {
                transaction.commit().await.map_err(|source| {
                    RunLaunchError::Repository(database_error("commit run launch", source))
                })?;
                Ok(LaunchClaimedRunOutcome::Started(receipt))
            }
            Err(error) => rollback_launch(transaction, error).await,
        }
    }
}

/// The accepted message's validated thread and body, loaded verbatim.
struct AcceptedMessageContext {
    thread_id: ThreadId,
    body: MessageBody,
}

/// Loads and revalidates the immutable accepted message for one launch.
///
/// Chronology against the message acceptance is checked here so no state is
/// mutated before the operation time is provably ordered.
async fn load_accepted_message(
    transaction: &sea_orm::DatabaseTransaction,
    message_id: &MessageId,
    operated_at_ms: i64,
) -> Result<AcceptedMessageContext, RunLaunchError> {
    let message = entities::message::Entity::find_by_id(message_id.as_str())
        .one(transaction)
        .await
        .map_err(|source| {
            RunLaunchError::Repository(database_error("load launched message", source))
        })?
        .ok_or(RunLaunchError::Repository(RepositoryError::Invariant {
            reason: "fenced launch lost its accepted message",
        }))?;
    if message.message_id != message_id.as_str() {
        return Err(RunLaunchError::Repository(RepositoryError::Invariant {
            reason: "fenced launch loaded a different message",
        }));
    }
    if operated_at_ms < message.accepted_at_ms {
        return Err(RunLaunchError::Repository(
            RepositoryError::InvalidChronology {
                earlier_field: "messages.accepted_at_ms",
                later_field: "launch operated_at",
            },
        ));
    }
    let thread_id = ThreadId::parse(message.thread_id.clone())
        .map_err(|error| corrupt_data_launch("messages", "thread_id", &error))?;
    let body = MessageBody::parse(message.body.clone())
        .map_err(|error| corrupt_data_launch("messages", "body", &error))?;
    Ok(AcceptedMessageContext { thread_id, body })
}

/// Confirms the owning thread exists and predates the launch operation.
async fn ensure_thread_admits_launch(
    transaction: &sea_orm::DatabaseTransaction,
    thread_id: &ThreadId,
    operated_at_ms: i64,
) -> Result<(), RunLaunchError> {
    let thread = entities::thread::Entity::find_by_id(thread_id.as_str())
        .one(transaction)
        .await
        .map_err(|source| {
            RunLaunchError::Repository(database_error("load launched thread", source))
        })?
        .ok_or(RunLaunchError::Repository(
            RepositoryError::ThreadNotFound {
                thread_id: thread_id.clone(),
            },
        ))?;
    if operated_at_ms < thread.created_at_ms {
        return Err(RunLaunchError::Repository(
            RepositoryError::InvalidChronology {
                earlier_field: "threads.created_at_ms",
                later_field: "launch operated_at",
            },
        ));
    }
    Ok(())
}

/// Reads or creates the thread's conversation counters under the writer.
///
/// An absent row means this is the conversation's first launch: the initial
/// counters are zero and the row is created transactionally here. Existing
/// rows are validated (non-negative counters, chronology against the launch
/// observation) but never rewritten by this helper.
async fn obtain_conversation_state(
    transaction: &sea_orm::DatabaseTransaction,
    thread_id: &str,
    operated_at_ms: i64,
) -> Result<(i64, i64), RunLaunchError> {
    if let Some(state) = entities::conversation_state::Entity::find_by_id(thread_id)
        .one(transaction)
        .await
        .map_err(|source| {
            RunLaunchError::Repository(database_error("load conversation state", source))
        })?
    {
        if state.next_renderer_ordinal < 0 {
            return Err(negative_counter("next_renderer_ordinal"));
        }
        if state.last_patch_sequence < 0 {
            return Err(negative_counter("last_patch_sequence"));
        }
        if operated_at_ms < state.updated_at_ms {
            return Err(RunLaunchError::Repository(
                RepositoryError::InvalidChronology {
                    earlier_field: "conversation_state.updated_at_ms",
                    later_field: "launch operated_at",
                },
            ));
        }
        Ok((state.next_renderer_ordinal, state.last_patch_sequence))
    } else {
        entities::conversation_state::ActiveModel {
            thread_id: Set(thread_id.to_owned()),
            next_renderer_ordinal: Set(0),
            last_patch_sequence: Set(0),
            updated_at_ms: Set(operated_at_ms),
        }
        .insert(transaction)
        .await
        .map_err(|source| {
            RunLaunchError::Repository(database_error("create conversation state", source))
        })?;
        Ok((0, 0))
    }
}

async fn build_launched_graph(
    transaction: &sea_orm::DatabaseTransaction,
    command: &LaunchClaimedRun<'_>,
    operated_at_ms: i64,
) -> Result<LaunchedRunReceipt, RunLaunchError> {
    let claimed = command.claimed;

    let AcceptedMessageContext { thread_id, body } =
        load_accepted_message(transaction, &claimed.message_id.clone(), operated_at_ms).await?;
    ensure_thread_admits_launch(transaction, &thread_id, operated_at_ms).await?;

    let (next_renderer_ordinal, last_patch_sequence) =
        obtain_conversation_state(transaction, thread_id.as_str(), operated_at_ms).await?;

    let turn_ordinal = next_renderer_ordinal;
    let item_ordinal = turn_ordinal
        .checked_add(1)
        .ok_or_else(|| counter_overflow("renderer ordinal", turn_ordinal))?;
    let final_renderer_ordinal = turn_ordinal
        .checked_add(LAUNCH_ORDINALS)
        .ok_or_else(|| counter_overflow("renderer ordinal", turn_ordinal))?;
    let first_patch_sequence = last_patch_sequence
        .checked_add(1)
        .ok_or_else(|| counter_overflow("patch sequence", last_patch_sequence))?;
    let second_patch_sequence = first_patch_sequence
        .checked_add(1)
        .ok_or_else(|| counter_overflow("patch sequence", first_patch_sequence))?;
    let final_patch_sequence = last_patch_sequence
        .checked_add(LAUNCH_PATCHES)
        .ok_or_else(|| counter_overflow("patch sequence", last_patch_sequence))?;

    ensure_launch_identity_vacancy(transaction, command).await?;

    insert_ordinal(
        transaction,
        thread_id.as_str(),
        turn_ordinal,
        OrdinalKind::Turn,
        command.turn_id.as_str(),
    )
    .await?;
    insert_ordinal(
        transaction,
        thread_id.as_str(),
        item_ordinal,
        OrdinalKind::Item,
        command.item_id.as_str(),
    )
    .await?;

    let projections = LaunchedProjections {
        thread_id: thread_id.as_str(),
        turn_id: command.turn_id.as_str(),
        item_id: command.item_id.as_str(),
        message_id: claimed.message_id.as_str(),
        body: body.as_str(),
        turn_ordinal,
        item_ordinal,
    };
    insert_turn_projection(transaction, &projections, operated_at_ms).await?;
    insert_item_projection(transaction, &projections, operated_at_ms).await?;
    insert_launched_run(transaction, command, thread_id.as_str(), operated_at_ms).await?;
    insert_initial_launch_patches(
        transaction,
        command,
        &projections,
        first_patch_sequence,
        second_patch_sequence,
        operated_at_ms,
    )
    .await?;

    entities::conversation_state::ActiveModel {
        thread_id: Set(thread_id.as_str().to_owned()),
        next_renderer_ordinal: Set(final_renderer_ordinal),
        last_patch_sequence: Set(final_patch_sequence),
        updated_at_ms: Set(operated_at_ms),
    }
    .update(transaction)
    .await
    .map_err(|source| {
        RunLaunchError::Repository(database_error("advance conversation counters", source))
    })?;

    let cursor_value = u64::try_from(second_patch_sequence)
        .map_err(|_| counter_overflow("patch sequence", second_patch_sequence))?;

    Ok(LaunchedRunReceipt {
        run_id: command.run_id.clone(),
        thread_id,
        message_id: claimed.message_id.clone(),
        turn_id: command.turn_id.clone(),
        item_id: command.item_id.clone(),
        generation: INITIAL_RUN_GENERATION,
        resulting_cursor: ConversationCursor::new(cursor_value),
    })
}

/// Projection values shared by the launched turn and user item inserts.
struct LaunchedProjections<'a> {
    thread_id: &'a str,
    turn_id: &'a str,
    item_id: &'a str,
    message_id: &'a str,
    body: &'a str,
    turn_ordinal: i64,
    item_ordinal: i64,
}

async fn insert_turn_projection(
    transaction: &sea_orm::DatabaseTransaction,
    projections: &LaunchedProjections<'_>,
    operated_at_ms: i64,
) -> Result<(), RunLaunchError> {
    entities::conversation_turn::Entity::insert(entities::conversation_turn::ActiveModel {
        turn_id: Set(projections.turn_id.to_owned()),
        thread_id: Set(projections.thread_id.to_owned()),
        ordinal: Set(projections.turn_ordinal),
        kind: Set(OrdinalKind::Turn),
        revision: Set(0),
        lifecycle: Set(EntityLifecycle::Pending),
        created_at_ms: Set(operated_at_ms),
        updated_at_ms: Set(operated_at_ms),
    })
    .exec(transaction)
    .await
    .map_err(|source| RunLaunchError::Repository(database_error("insert launched turn", source)))?;
    Ok(())
}

async fn insert_item_projection(
    transaction: &sea_orm::DatabaseTransaction,
    projections: &LaunchedProjections<'_>,
    operated_at_ms: i64,
) -> Result<(), RunLaunchError> {
    entities::conversation_item::Entity::insert(entities::conversation_item::ActiveModel {
        item_id: Set(projections.item_id.to_owned()),
        thread_id: Set(projections.thread_id.to_owned()),
        turn_id: Set(projections.turn_id.to_owned()),
        ordinal: Set(projections.item_ordinal),
        kind: Set(OrdinalKind::Item),
        revision: Set(0),
        lifecycle: Set(EntityLifecycle::Completed),
        item_kind: Set(ConversationItemKind::UserMessage),
        source_message_id: Set(Some(projections.message_id.to_owned())),
        run_id: Set(None),
        native_item_key: Set(None),
        phase: Set(None),
        body: Set(projections.body.to_owned()),
        created_at_ms: Set(operated_at_ms),
        updated_at_ms: Set(operated_at_ms),
    })
    .exec(transaction)
    .await
    .map_err(|source| {
        RunLaunchError::Repository(database_error("insert launched user item", source))
    })?;
    Ok(())
}

async fn insert_launched_run(
    transaction: &sea_orm::DatabaseTransaction,
    command: &LaunchClaimedRun<'_>,
    thread_id: &str,
    operated_at_ms: i64,
) -> Result<(), RunLaunchError> {
    let claimed = command.claimed;
    let (run_owner, run_lease, run_claim) = command.credentials.parts();
    entities::assistant_run::Entity::insert(entities::assistant_run::ActiveModel {
        run_id: Set(command.run_id.as_str().to_owned()),
        thread_id: Set(thread_id.to_owned()),
        run_start_key: Set(OpaqueBytes::new(command.run_start_key.expose().to_vec())),
        origin_message_id: Set(claimed.message_id.as_str().to_owned()),
        origin_turn_id: Set(command.turn_id.as_str().to_owned()),
        lifecycle: Set(AssistantRunLifecycle::Launching),
        generation: Set(INITIAL_RUN_GENERATION),
        owner: Set(Some(OpaqueBytes::new(run_owner.expose().to_vec()))),
        lease: Set(Some(OpaqueBytes::new(run_lease.expose().to_vec()))),
        claim_token: Set(Some(OpaqueBytes::new(run_claim.expose().to_vec()))),
        provider_binding_version: Set(None),
        provider_binding: Set(None),
        provider_bound_at_ms: Set(None),
        error_code: Set(None),
        error_message: Set(None),
        created_at_ms: Set(operated_at_ms),
        updated_at_ms: Set(operated_at_ms),
        terminal_at_ms: Set(None),
    })
    .exec(transaction)
    .await
    .map_err(|source| RunLaunchError::Repository(database_error("insert launching run", source)))?;
    Ok(())
}

async fn insert_initial_launch_patches(
    transaction: &sea_orm::DatabaseTransaction,
    command: &LaunchClaimedRun<'_>,
    projections: &LaunchedProjections<'_>,
    first_patch_sequence: i64,
    second_patch_sequence: i64,
    operated_at_ms: i64,
) -> Result<(), RunLaunchError> {
    insert_initial_patch(
        transaction,
        projections.thread_id,
        first_patch_sequence,
        ConversationPatchKind::TurnUpsert,
        operated_at_ms,
        InitialPatchProjection {
            patch_id: command.first_patch_id,
            turn_id: projections.turn_id,
            item_id: None,
            ordinal: projections.turn_ordinal,
            lifecycle: EntityLifecycle::Pending,
            item_kind: None,
            body: None,
        },
    )
    .await?;
    insert_initial_patch(
        transaction,
        projections.thread_id,
        second_patch_sequence,
        ConversationPatchKind::ItemUpsert,
        operated_at_ms,
        InitialPatchProjection {
            patch_id: command.second_patch_id,
            turn_id: projections.turn_id,
            item_id: Some(projections.item_id),
            ordinal: projections.item_ordinal,
            lifecycle: EntityLifecycle::Completed,
            item_kind: Some(ConversationItemKind::UserMessage),
            body: Some(projections.body.to_owned()),
        },
    )
    .await?;
    Ok(())
}

/// Diagnoses a launch whose fence matched no row inside its transaction.
///
/// An exact replay of the original launch answers `AlreadyStarted` derived
/// from the persisted rows; every other divergence is typed without writing
/// anything.
async fn classify_unfenced_launch(
    transaction: &sea_orm::DatabaseTransaction,
    command: &LaunchClaimedRun<'_>,
    operated_at_ms: i64,
) -> Result<LaunchClaimedRunOutcome, RunLaunchError> {
    let claimed = command.claimed;

    let dispatch = entities::message_dispatch::Entity::find_by_id(claimed.message_id.as_str())
        .one(transaction)
        .await
        .map_err(|source| {
            RunLaunchError::Repository(database_error("classify unfenced launch", source))
        })?
        .ok_or(RunLaunchError::Repository(
            RepositoryError::DispatchNotFound {
                message_id: claimed.message_id.clone(),
            },
        ))?;

    match dispatch.state {
        DispatchState::Running => {
            classify_running_replay(transaction, command, &dispatch, operated_at_ms)
                .await
                .map(LaunchClaimedRunOutcome::AlreadyStarted)
        }
        DispatchState::Leased => {
            if dispatch.updated_at_ms > operated_at_ms {
                return Err(RunLaunchError::Repository(
                    RepositoryError::InvalidChronology {
                        earlier_field: "message_dispatches.updated_at_ms",
                        later_field: "launch operated_at",
                    },
                ));
            }
            let persisted_expiry = dispatch.lease_expires_at_ms.ok_or_else(|| {
                corrupt_data_launch(
                    "message_dispatches",
                    "lease_expires_at_ms",
                    "required value is null",
                )
            })?;
            if persisted_expiry <= operated_at_ms {
                return Err(RunLaunchError::Repository(
                    RepositoryError::DispatchLeaseExpired {
                        message_id: claimed.message_id.clone(),
                        lease_expires_at_ms: persisted_expiry,
                        operated_at_ms,
                    },
                ));
            }
            let persisted_owner = dispatch
                .lease_owner
                .as_deref()
                .ok_or_else(|| {
                    corrupt_data_launch(
                        "message_dispatches",
                        "lease_owner",
                        "required value is null",
                    )
                })?
                .to_owned();
            let persisted_owner =
                DispatchLeaseOwner::from_storage(&persisted_owner).map_err(|error| {
                    corrupt_data_launch("message_dispatches", "lease_owner", &error)
                })?;
            if !persisted_owner.constant_time_eq(&claimed.owner) {
                return Err(RunLaunchError::Repository(
                    RepositoryError::DispatchOwnerMismatch {
                        message_id: claimed.message_id.clone(),
                    },
                ));
            }
            Err(RunLaunchError::SnapshotMismatch {
                message_id: claimed.message_id.clone(),
            })
        }
        other => Err(RunLaunchError::Repository(
            RepositoryError::InvalidDispatchState {
                message_id: claimed.message_id.clone(),
                state: dispatch_state_label(&other),
            },
        )),
    }
}

/// Validates one exact replay against the persisted launching graph.
///
/// Every originally persisted projection value — including timestamps,
/// revisions, lifecycles, bodies, NULL columns, the shared ordinal ledger,
/// and ordinal adjacency — must equal the launch's recorded shape, and the
/// receipt's cursor derives from the ORIGINAL second patch sequence rather
/// than any current counter.
/// Fences an exact replay's dispatch row against the claimed snapshot.
fn validate_running_dispatch_snapshot(
    dispatch: &entities::MessageDispatch,
    claimed: &ClaimedMessageDispatch,
    operated_at_ms: i64,
) -> Result<(), RunLaunchError> {
    if dispatch.correlation_id != claimed.correlation_id.as_str()
        || i64::from(dispatch.attempt_count) != i64::from(claimed.attempt_count)
        || dispatch.queued_at_ms != millis(claimed.queued_at)
        || dispatch.available_at_ms != millis(claimed.available_at)
        || dispatch.lease_expires_at_ms != Some(millis(claimed.lease_expires_at))
        || dispatch.updated_at_ms != operated_at_ms
    {
        return Err(RunLaunchError::SnapshotMismatch {
            message_id: claimed.message_id.clone(),
        });
    }
    let persisted_owner = dispatch
        .lease_owner
        .as_deref()
        .ok_or_else(|| {
            corrupt_data_launch(
                "message_dispatches",
                "lease_owner",
                "required value is null",
            )
        })?
        .to_owned();
    let persisted_owner = DispatchLeaseOwner::from_storage(&persisted_owner)
        .map_err(|error| corrupt_data_launch("message_dispatches", "lease_owner", &error))?;
    if !persisted_owner.constant_time_eq(&claimed.owner) {
        return Err(RunLaunchError::Repository(
            RepositoryError::DispatchOwnerMismatch {
                message_id: claimed.message_id.clone(),
            },
        ));
    }
    Ok(())
}

/// Loads the replayed run and validates its launch-state fences.
///
/// A missing run identity whose origin message already owns another run is
/// a typed identity conflict, never a fresh or missing run.
async fn load_validated_replayed_run(
    transaction: &sea_orm::DatabaseTransaction,
    command: &LaunchClaimedRun<'_>,
    operated_at_ms: i64,
) -> Result<entities::AssistantRun, RunLaunchError> {
    let claimed = command.claimed;

    let found = entities::assistant_run::Entity::find_by_id(command.run_id.as_str())
        .one(transaction)
        .await
        .map_err(|source| {
            RunLaunchError::Repository(database_error("load replayed run", source))
        })?;
    let Some(run) = found else {
        let origin_conflict = entities::assistant_run::Entity::find()
            .filter(
                entities::assistant_run::Column::OriginMessageId.eq(claimed.message_id.as_str()),
            )
            .one(transaction)
            .await
            .map_err(|source| {
                RunLaunchError::Repository(database_error("check replayed run origin", source))
            })?;
        return if origin_conflict.is_some() {
            Err(RunLaunchError::IdentityConflict {
                reason: "origin message already owns a different run identity",
            })
        } else {
            Err(RunLaunchError::RunNotFound {
                run_id: command.run_id.clone(),
            })
        };
    };

    if run.origin_message_id != claimed.message_id.as_str()
        || run.origin_turn_id != command.turn_id.as_str()
    {
        return Err(RunLaunchError::IdentityConflict {
            reason: "stored run originates from another message or turn",
        });
    }
    if run.lifecycle != AssistantRunLifecycle::Launching {
        return Err(RunLaunchError::RunNotLaunchable {
            run_id: command.run_id.clone(),
        });
    }
    if run.generation != INITIAL_RUN_GENERATION
        || run.created_at_ms != operated_at_ms
        || run.updated_at_ms != operated_at_ms
        || run.provider_binding_version.is_some()
        || run.provider_binding.is_some()
        || run.provider_bound_at_ms.is_some()
        || !stored_bytes_match(&run.run_start_key, command.run_start_key.expose())
        || !command.credentials.matches_stored(
            run.owner.as_ref(),
            run.lease.as_ref(),
            run.claim_token.as_ref(),
        )
    {
        return Err(RunLaunchError::CredentialMismatch {
            run_id: command.run_id.clone(),
        });
    }
    Ok(run)
}

/// Validates the replayed turn/item projections and their ordinal ledger.
async fn validate_replayed_turn_item(
    transaction: &sea_orm::DatabaseTransaction,
    command: &LaunchClaimedRun<'_>,
    run_thread_id: &str,
    persisted_body: &str,
    operated_at_ms: i64,
) -> Result<(entities::ConversationTurn, entities::ConversationItem), RunLaunchError> {
    let claimed = command.claimed;

    let turn = entities::conversation_turn::Entity::find_by_id(command.turn_id.as_str())
        .one(transaction)
        .await
        .map_err(|source| RunLaunchError::Repository(database_error("load replayed turn", source)))?
        .ok_or(RunLaunchError::IdentityConflict {
            reason: "launched turn projection is missing",
        })?;
    let item = entities::conversation_item::Entity::find_by_id(command.item_id.as_str())
        .one(transaction)
        .await
        .map_err(|source| RunLaunchError::Repository(database_error("load replayed item", source)))?
        .ok_or(RunLaunchError::IdentityConflict {
            reason: "launched user item projection is missing",
        })?;

    if turn.thread_id != run_thread_id
        || item.thread_id != run_thread_id
        || item.turn_id != turn.turn_id
        || turn.ordinal.checked_add(1) != Some(item.ordinal)
        || turn.kind != OrdinalKind::Turn
        || turn.revision != 0
        || turn.lifecycle != EntityLifecycle::Pending
        || turn.created_at_ms != operated_at_ms
        || turn.updated_at_ms != operated_at_ms
        || item.kind != OrdinalKind::Item
        || item.revision != 0
        || item.lifecycle != EntityLifecycle::Completed
        || item.item_kind != ConversationItemKind::UserMessage
        || item.source_message_id.as_deref() != Some(claimed.message_id.as_str())
        || item.run_id.is_some()
        || item.native_item_key.is_some()
        || item.phase.is_some()
        || item.body != persisted_body
        || item.created_at_ms != operated_at_ms
        || item.updated_at_ms != operated_at_ms
    {
        return Err(RunLaunchError::IdentityConflict {
            reason: "stored turn and user item projections contradict the launch",
        });
    }

    let turn_ledger =
        entities::conversation_ordinal::Entity::find_by_id((turn.thread_id.clone(), turn.ordinal))
            .one(transaction)
            .await
            .map_err(|source| {
                RunLaunchError::Repository(database_error("load replayed turn ordinal", source))
            })?
            .ok_or(RunLaunchError::IdentityConflict {
                reason: "turn ordinal ledger entry is missing",
            })?;
    let item_ledger =
        entities::conversation_ordinal::Entity::find_by_id((item.thread_id.clone(), item.ordinal))
            .one(transaction)
            .await
            .map_err(|source| {
                RunLaunchError::Repository(database_error("load replayed item ordinal", source))
            })?
            .ok_or(RunLaunchError::IdentityConflict {
                reason: "item ordinal ledger entry is missing",
            })?;
    if turn_ledger.entity_id != turn.turn_id
        || turn_ledger.kind != OrdinalKind::Turn
        || item_ledger.entity_id != item.item_id
        || item_ledger.kind != OrdinalKind::Item
        || turn_ledger.ordinal.checked_add(1) != Some(item_ledger.ordinal)
    {
        return Err(RunLaunchError::IdentityConflict {
            reason: "shared ordinal ledger contradicts the launch",
        });
    }

    Ok((turn, item))
}

/// Validates the two initial replay patches against their recorded shape.
///
/// Returns the ORIGINAL second patch sequence, from which the replay
/// receipt's cursor is derived.
async fn validate_replayed_initial_patches(
    transaction: &sea_orm::DatabaseTransaction,
    command: &LaunchClaimedRun<'_>,
    turn: &entities::ConversationTurn,
    item: &entities::ConversationItem,
    persisted_body: &str,
    operated_at_ms: i64,
) -> Result<i64, RunLaunchError> {
    let first_patch =
        entities::conversation_patch::Entity::find_by_id(command.first_patch_id.as_str())
            .one(transaction)
            .await
            .map_err(|source| {
                RunLaunchError::Repository(database_error("load replayed first patch", source))
            })?
            .ok_or(RunLaunchError::IdentityConflict {
                reason: "initial turn-upsert patch is missing",
            })?;
    let second_patch =
        entities::conversation_patch::Entity::find_by_id(command.second_patch_id.as_str())
            .one(transaction)
            .await
            .map_err(|source| {
                RunLaunchError::Repository(database_error("load replayed second patch", source))
            })?
            .ok_or(RunLaunchError::IdentityConflict {
                reason: "initial item-upsert patch is missing",
            })?;

    if first_patch.thread_id != turn.thread_id
        || first_patch.kind != ConversationPatchKind::TurnUpsert
        || first_patch.turn_id.as_deref() != Some(turn.turn_id.as_str())
        || first_patch.item_id.is_some()
        || first_patch.ordinal != Some(turn.ordinal)
        || first_patch.lifecycle != Some(EntityLifecycle::Pending)
        || first_patch.item_kind.is_some()
        || first_patch.run_id.is_some()
        || first_patch.phase.is_some()
        || first_patch.body.is_some()
        || first_patch.fragment.is_some()
        || first_patch.revision != 0
        || first_patch.recorded_at_ms != operated_at_ms
        || first_patch.entity_created_at_ms != Some(operated_at_ms)
        || first_patch.entity_updated_at_ms != Some(operated_at_ms)
        || second_patch.thread_id != turn.thread_id
        || second_patch.kind != ConversationPatchKind::ItemUpsert
        || second_patch.turn_id.as_deref() != Some(turn.turn_id.as_str())
        || second_patch.item_id.as_deref() != Some(item.item_id.as_str())
        || second_patch.ordinal != Some(item.ordinal)
        || second_patch.lifecycle != Some(EntityLifecycle::Completed)
        || second_patch.item_kind != Some(ConversationItemKind::UserMessage)
        || second_patch.run_id.is_some()
        || second_patch.phase.is_some()
        || second_patch.fragment.is_some()
        || second_patch.body.as_deref() != Some(persisted_body)
        || second_patch.revision != 0
        || second_patch.recorded_at_ms != operated_at_ms
        || second_patch.entity_created_at_ms != Some(operated_at_ms)
        || second_patch.entity_updated_at_ms != Some(operated_at_ms)
        || first_patch.sequence.checked_add(1) != Some(second_patch.sequence)
    {
        return Err(RunLaunchError::IdentityConflict {
            reason: "stored initial patches contradict the launch",
        });
    }
    Ok(second_patch.sequence)
}

/// Validates one exact replay against the persisted launching graph.
///
/// Every originally persisted projection value — including timestamps,
/// revisions, lifecycles, bodies, NULL columns, the shared ordinal ledger,
/// and ordinal adjacency — must equal the launch's recorded shape, and the
/// receipt's cursor derives from the ORIGINAL second patch sequence rather
/// than any current counter.
async fn classify_running_replay(
    transaction: &sea_orm::DatabaseTransaction,
    command: &LaunchClaimedRun<'_>,
    dispatch: &entities::MessageDispatch,
    operated_at_ms: i64,
) -> Result<LaunchedRunReceipt, RunLaunchError> {
    validate_running_dispatch_snapshot(dispatch, command.claimed, operated_at_ms)?;
    let run = load_validated_replayed_run(transaction, command, operated_at_ms).await?;
    let persisted_body =
        MessageBody::parse(message_body_of_replay(transaction, command.claimed).await?)
            .map_err(|error| corrupt_data_launch("messages", "body", &error))?;
    let (turn, item) = validate_replayed_turn_item(
        transaction,
        command,
        run.thread_id.as_str(),
        persisted_body.as_str(),
        operated_at_ms,
    )
    .await?;

    let second_sequence = validate_replayed_initial_patches(
        transaction,
        command,
        &turn,
        &item,
        persisted_body.as_str(),
        operated_at_ms,
    )
    .await?;

    let cursor_value = u64::try_from(second_sequence)
        .map_err(|_| counter_overflow("patch sequence", second_sequence))?;

    Ok(LaunchedRunReceipt {
        run_id: command.run_id.clone(),
        thread_id: ThreadId::parse(run.thread_id.clone())
            .map_err(|error| corrupt_data_launch("assistant_runs", "thread_id", &error))?,
        message_id: command.claimed.message_id.clone(),
        turn_id: command.turn_id.clone(),
        item_id: command.item_id.clone(),
        generation: INITIAL_RUN_GENERATION,
        resulting_cursor: ConversationCursor::new(cursor_value),
    })
}

async fn message_body_of_replay(
    transaction: &sea_orm::DatabaseTransaction,
    claimed: &ClaimedMessageDispatch,
) -> Result<String, RunLaunchError> {
    let message = entities::message::Entity::find_by_id(claimed.message_id.as_str())
        .one(transaction)
        .await
        .map_err(|source| {
            RunLaunchError::Repository(database_error("load replayed message", source))
        })?
        .ok_or(RunLaunchError::Repository(RepositoryError::Invariant {
            reason: "replayed launch lost its accepted message",
        }))?;
    Ok(message.body)
}

/// Rejects fresh launches whose identities already exist durably.
///
/// The writer position is already held, so these lookups see a stable view:
/// any hit means the supplied identities contradict a genuinely fresh
/// launch and the whole transaction rolls back afterwards. Every uniqueness
/// surface this operation can touch is probed explicitly — run identity,
/// start key, both origins, user-item source message, turn and item
/// identities, both patch identities, and the globally unique ordinal
/// entity ids — so no database error string ever needs interpreting.
async fn ensure_launch_identity_vacancy(
    transaction: &sea_orm::DatabaseTransaction,
    command: &LaunchClaimedRun<'_>,
) -> Result<(), RunLaunchError> {
    let claimed_message = command.claimed.message_id.as_str().to_owned();
    let run_start_key = command.run_start_key.expose().to_vec();

    macro_rules! reject_if_present {
        ($reason:expr, $query:expr) => {
            let existing = $query.await.map_err(|source| {
                RunLaunchError::Repository(database_error("check launch identity vacancy", source))
            })?;
            if existing.is_some() {
                return Err(RunLaunchError::IdentityConflict { reason: $reason });
            }
        };
    }

    reject_if_present!(
        "origin message already owns a run",
        entities::assistant_run::Entity::find()
            .filter(entities::assistant_run::Column::OriginMessageId.eq(claimed_message.clone()))
            .one(transaction)
    );
    reject_if_present!(
        "run identity already exists",
        entities::assistant_run::Entity::find_by_id(command.run_id.as_str()).one(transaction)
    );
    reject_if_present!(
        "run start key already exists",
        entities::assistant_run::Entity::find()
            .filter(entities::assistant_run::Column::RunStartKey.eq(run_start_key))
            .one(transaction)
    );
    reject_if_present!(
        "origin turn already owns a run",
        entities::assistant_run::Entity::find()
            .filter(entities::assistant_run::Column::OriginTurnId.eq(command.turn_id.as_str()))
            .one(transaction)
    );
    reject_if_present!(
        "turn identity already exists",
        entities::conversation_turn::Entity::find_by_id(command.turn_id.as_str()).one(transaction)
    );
    reject_if_present!(
        "user item identity already exists",
        entities::conversation_item::Entity::find_by_id(command.item_id.as_str()).one(transaction)
    );
    reject_if_present!(
        "accepted message already has a conversation item",
        entities::conversation_item::Entity::find()
            .filter(
                entities::conversation_item::Column::SourceMessageId.eq(claimed_message.clone()),
            )
            .one(transaction)
    );
    reject_if_present!(
        "turn ordinal entity already exists",
        entities::conversation_ordinal::Entity::find()
            .filter(entities::conversation_ordinal::Column::EntityId.eq(command.turn_id.as_str()),)
            .one(transaction)
    );
    reject_if_present!(
        "item ordinal entity already exists",
        entities::conversation_ordinal::Entity::find()
            .filter(entities::conversation_ordinal::Column::EntityId.eq(command.item_id.as_str()),)
            .one(transaction)
    );
    reject_if_present!(
        "first patch identity already exists",
        entities::conversation_patch::Entity::find_by_id(command.first_patch_id.as_str())
            .one(transaction)
    );
    reject_if_present!(
        "second patch identity already exists",
        entities::conversation_patch::Entity::find_by_id(command.second_patch_id.as_str())
            .one(transaction)
    );

    Ok(())
}

async fn insert_initial_patch(
    transaction: &sea_orm::DatabaseTransaction,
    thread_id: &str,
    sequence: i64,
    kind: ConversationPatchKind,
    recorded_at_ms: i64,
    projection: InitialPatchProjection<'_>,
) -> Result<(), RunLaunchError> {
    entities::conversation_patch::Entity::insert(entities::conversation_patch::ActiveModel {
        patch_id: Set(projection.patch_id.as_str().to_owned()),
        thread_id: Set(thread_id.to_owned()),
        sequence: Set(sequence),
        kind: Set(kind),
        revision: Set(0),
        recorded_at_ms: Set(recorded_at_ms),
        turn_id: Set(Some(projection.turn_id.to_owned())),
        item_id: Set(projection.item_id.map(str::to_owned)),
        ordinal: Set(Some(projection.ordinal)),
        lifecycle: Set(Some(projection.lifecycle)),
        item_kind: Set(projection.item_kind),
        run_id: Set(None),
        phase: Set(None),
        body: Set(projection.body),
        fragment: Set(None),
        entity_created_at_ms: Set(Some(recorded_at_ms)),
        entity_updated_at_ms: Set(Some(recorded_at_ms)),
    })
    .exec(transaction)
    .await
    .map_err(|source| RunLaunchError::Repository(database_error("insert initial patch", source)))?;
    Ok(())
}

async fn insert_ordinal(
    transaction: &sea_orm::DatabaseTransaction,
    thread_id: &str,
    ordinal: i64,
    kind: OrdinalKind,
    entity_id: &str,
) -> Result<(), RunLaunchError> {
    entities::conversation_ordinal::Entity::insert(entities::conversation_ordinal::ActiveModel {
        thread_id: Set(thread_id.to_owned()),
        ordinal: Set(ordinal),
        kind: Set(kind),
        entity_id: Set(entity_id.to_owned()),
    })
    .exec(transaction)
    .await
    .map_err(|source| {
        RunLaunchError::Repository(database_error("insert shared ordinal", source))
    })?;
    Ok(())
}

pub(super) fn stored_bytes_match(
    stored: &OpaqueBytes,
    supplied: &[u8; RUN_CAPABILITY_BYTES],
) -> bool {
    stored.as_slice().len() == RUN_CAPABILITY_BYTES
        && bool::from(stored.as_slice().ct_eq(supplied.as_slice()))
}

fn dispatch_state_label(state: &DispatchState) -> &'static str {
    match state {
        DispatchState::Queued => "queued",
        DispatchState::Leased => "leased",
        DispatchState::Running => "running",
        DispatchState::Completed => "completed",
        DispatchState::Failed => "failed",
    }
}

fn counter_overflow(counter: &'static str, value: i64) -> RunLaunchError {
    RunLaunchError::CounterOverflow { counter, value }
}

fn negative_counter(column: &'static str) -> RunLaunchError {
    RunLaunchError::Repository(RepositoryError::CorruptData {
        table: "conversation_state",
        field: column,
        reason: "counter is negative".to_owned(),
    })
}

fn corrupt_data_launch(
    table: &'static str,
    field: &'static str,
    reason: &(impl ToString + ?Sized),
) -> RunLaunchError {
    RunLaunchError::Repository(corrupt_data(table, field, reason))
}

async fn rollback_launch<T>(
    transaction: sea_orm::DatabaseTransaction,
    error: RunLaunchError,
) -> Result<T, RunLaunchError> {
    transaction.rollback().await.map_err(|source| {
        RunLaunchError::Repository(database_error("roll back run launch", source))
    })?;
    Err(error)
}

/// Rolls back the read-only diagnosis and returns its outcome unchanged.
async fn finish_diagnosed_launch(
    transaction: sea_orm::DatabaseTransaction,
    diagnosed: Result<LaunchClaimedRunOutcome, RunLaunchError>,
) -> Result<LaunchClaimedRunOutcome, RunLaunchError> {
    transaction.rollback().await.map_err(|source| {
        RunLaunchError::Repository(database_error("roll back run launch diagnosis", source))
    })?;
    diagnosed
}
