import { Schema } from "effect";

import { ModelManifest, SpeedOption, ThinkingLevel, ThinkingOption } from "./schema";

export const thinking_level_labels = Schema.decodeUnknownSync(
	Schema.Record(ThinkingLevel, Schema.String),
)({
	light: "Light",
	medium: "Medium",
	high: "High",
	xhigh: "Extra High",
	max: "Max",
});

const unavailable = Schema.decodeUnknownSync(
	Schema.Struct({ availability: Schema.Literal("unavailable") }),
)({ availability: "unavailable" });

const standard_speed = Schema.decodeUnknownSync(SpeedOption)({
	default: true,
	description: "Standard service tier.",
	id: "standard",
	label: "Standard",
	native_value: "standard",
});

const fast_speed = Schema.decodeUnknownSync(SpeedOption)({
	default: false,
	description: "Prioritizes lower latency through the provider's fast service tier.",
	id: "fast",
	label: "Fast",
	native_value: "fast",
});

const native_thinking = (description: string) =>
	Schema.decodeUnknownSync(
		Schema.Struct({
			availability: Schema.Literal("native"),
			description: Schema.String,
		}),
	)({ availability: "native", description });

const standard = (id: ThinkingOption["id"], native_value: string) =>
	Schema.decodeUnknownSync(ThinkingOption)({ economics: "standard", id, native_value });

const exceptional = (id: ThinkingOption["id"], native_value: string) =>
	Schema.decodeUnknownSync(ThinkingOption)({
		economics: "diminishing-returns",
		id,
		native_value,
	});

export const model_manifest = Schema.decodeUnknownSync(ModelManifest)({
	revision: "2026-07-26.1",
	providers: [
		{ id: "openai", label: "OpenAI" },
		{ id: "anthropic", label: "Anthropic" },
		{ id: "xai", label: "xAI" },
		{ id: "opencode", label: "OpenCode" },
		{ id: "google", label: "Google" },
		{ id: "zai", label: "Z.ai" },
		{ id: "alibaba", label: "Alibaba" },
		{ id: "moonshot", label: "Moonshot AI" },
		{ id: "deepseek", label: "DeepSeek" },
	],
	harnesses: [
		{
			id: "codex",
			gateways: [],
			label: "Codex",
			permission_modes: ["read-only", "workspace-write", "full-access"],
			workflow_modes: [],
		},
		{
			id: "claude",
			gateways: [],
			label: "Claude Code",
			permission_modes: ["default", "accept-edits", "plan", "bypass-permissions"],
			workflow_modes: [],
		},
		{
			id: "grok",
			gateways: [],
			label: "Grok Build",
			permission_modes: ["runtime-managed"],
			workflow_modes: [],
		},
		{
			id: "opencode",
			gateways: [
				{ id: "zen", kind: "managed", label: "Zen" },
				{ id: "go", kind: "managed", label: "Go" },
				{ id: "black", kind: "managed", label: "Black" },
				{ id: "alibaba", kind: "provider-direct", label: "Alibaba" },
				{ id: "moonshot", kind: "provider-direct", label: "Moonshot AI" },
				{ id: "deepseek", kind: "provider-direct", label: "DeepSeek" },
			],
			label: "OpenCode",
			permission_modes: ["ask", "allow", "deny"],
			workflow_modes: ["plan", "build"],
		},
		{
			id: "antigravity",
			gateways: [],
			label: "Antigravity",
			permission_modes: [],
			workflow_modes: [],
		},
	],
	models: [
		{
			id: "codex-sol",
			name: "GPT 5.6 Sol",
			native_model_id: "gpt-5.6-sol",
			harness: "codex",
			provider: "openai",
			routing: { kind: "default" },
			status: "prototype",
			capabilities: {
				thinking: {
					availability: "supported",
					default: "high",
					options: [
						standard("light", "low"),
						standard("medium", "medium"),
						standard("high", "high"),
						standard("xhigh", "xhigh"),
						exceptional("max", "max"),
					],
				},
				speed_options: [standard_speed, fast_speed],
				image_input: true,
				local_tools: true,
				mcp: true,
				web_search: true,
			},
		},
		{
			id: "codex-terra",
			name: "GPT 5.6 Terra",
			native_model_id: "gpt-5.6-terra",
			harness: "codex",
			provider: "openai",
			routing: { kind: "default" },
			status: "prototype",
			capabilities: {
				thinking: {
					availability: "supported",
					default: "high",
					options: [
						standard("light", "low"),
						standard("medium", "medium"),
						standard("high", "high"),
						standard("xhigh", "xhigh"),
						exceptional("max", "max"),
					],
				},
				speed_options: [standard_speed],
				image_input: true,
				local_tools: true,
				mcp: true,
				web_search: true,
			},
		},
		{
			id: "codex-luna",
			name: "GPT 5.6 Luna",
			native_model_id: "gpt-5.6-luna",
			harness: "codex",
			provider: "openai",
			routing: { kind: "default" },
			status: "prototype",
			capabilities: {
				thinking: {
					availability: "supported",
					default: "medium",
					options: [
						standard("light", "low"),
						standard("medium", "medium"),
						standard("high", "high"),
						standard("xhigh", "xhigh"),
						exceptional("max", "max"),
					],
				},
				speed_options: [standard_speed],
				image_input: true,
				local_tools: true,
				mcp: true,
				web_search: true,
			},
		},
		{
			id: "codex-gpt-5-5",
			name: "GPT 5.5",
			native_model_id: "gpt-5.5",
			harness: "codex",
			provider: "openai",
			routing: { kind: "default" },
			status: "prototype",
			capabilities: {
				thinking: {
					availability: "supported",
					default: "high",
					options: [
						standard("light", "low"),
						standard("medium", "medium"),
						standard("high", "high"),
						standard("xhigh", "xhigh"),
					],
				},
				speed_options: [standard_speed],
				image_input: true,
				local_tools: true,
				mcp: true,
				web_search: true,
			},
		},
		{
			id: "codex-gpt-5-4",
			name: "GPT 5.4",
			native_model_id: "gpt-5.4",
			harness: "codex",
			provider: "openai",
			routing: { kind: "default" },
			status: "prototype",
			capabilities: {
				thinking: {
					availability: "supported",
					default: "high",
					options: [
						standard("light", "low"),
						standard("medium", "medium"),
						standard("high", "high"),
						standard("xhigh", "xhigh"),
					],
				},
				speed_options: [standard_speed],
				image_input: true,
				local_tools: true,
				mcp: true,
				web_search: true,
			},
		},
		{
			id: "codex-gpt-5-4-mini",
			name: "GPT 5.4 Mini",
			native_model_id: "gpt-5.4-mini",
			harness: "codex",
			provider: "openai",
			routing: { kind: "default" },
			status: "prototype",
			capabilities: {
				thinking: {
					availability: "supported",
					default: "medium",
					options: [
						standard("light", "low"),
						standard("medium", "medium"),
						standard("high", "high"),
						standard("xhigh", "xhigh"),
					],
				},
				speed_options: [standard_speed],
				image_input: true,
				local_tools: true,
				mcp: true,
				web_search: true,
			},
		},
		{
			id: "codex-spark",
			name: "GPT 5.3 Codex Spark",
			native_model_id: "gpt-5.3-codex-spark",
			harness: "codex",
			provider: "openai",
			routing: { kind: "default" },
			status: "prototype",
			capabilities: {
				thinking: {
					availability: "supported",
					default: "medium",
					options: [
						standard("light", "low"),
						standard("medium", "medium"),
						standard("high", "high"),
						standard("xhigh", "xhigh"),
					],
				},
				speed_options: [standard_speed],
				image_input: false,
				local_tools: true,
				mcp: true,
				web_search: true,
			},
		},
		{
			id: "claude-fable",
			name: "Claude Fable 5",
			native_model_id: "claude-fable-5",
			harness: "claude",
			provider: "anthropic",
			routing: { kind: "default" },
			status: "prototype",
			capabilities: {
				thinking: {
					availability: "supported",
					default: "high",
					options: [
						standard("light", "low"),
						standard("medium", "medium"),
						standard("high", "high"),
						standard("xhigh", "xhigh"),
						exceptional("max", "max"),
					],
				},
				speed_options: [standard_speed],
				image_input: true,
				local_tools: true,
				mcp: true,
				web_search: true,
			},
		},
		{
			id: "claude-opus",
			name: "Claude Opus 5",
			native_model_id: "claude-opus-5",
			harness: "claude",
			provider: "anthropic",
			routing: { kind: "default" },
			status: "prototype",
			capabilities: {
				thinking: {
					availability: "supported",
					default: "high",
					options: [
						standard("light", "low"),
						standard("medium", "medium"),
						standard("high", "high"),
						standard("xhigh", "xhigh"),
						exceptional("max", "max"),
					],
				},
				speed_options: [standard_speed],
				image_input: true,
				local_tools: true,
				mcp: true,
				web_search: true,
			},
		},
		{
			id: "claude-sonnet",
			name: "Claude Sonnet 5",
			native_model_id: "claude-sonnet-5",
			harness: "claude",
			provider: "anthropic",
			routing: { kind: "default" },
			status: "prototype",
			capabilities: {
				thinking: {
					availability: "supported",
					default: "high",
					options: [
						standard("light", "low"),
						standard("medium", "medium"),
						standard("high", "high"),
						standard("xhigh", "xhigh"),
						exceptional("max", "max"),
					],
				},
				speed_options: [standard_speed],
				image_input: true,
				local_tools: true,
				mcp: true,
				web_search: true,
			},
		},
		{
			id: "claude-haiku",
			name: "Claude Haiku 4.5",
			native_model_id: "claude-haiku-4-5",
			harness: "claude",
			provider: "anthropic",
			routing: { kind: "default" },
			status: "prototype",
			capabilities: {
				thinking: unavailable,
				speed_options: [standard_speed],
				image_input: true,
				local_tools: true,
				mcp: true,
				web_search: true,
			},
		},
		{
			id: "grok-4-5",
			name: "Grok 4.5",
			native_model_id: "grok-4.5",
			harness: "grok",
			provider: "xai",
			routing: { kind: "default" },
			status: "prototype",
			capabilities: {
				thinking: native_thinking("Reported by the active ACP runtime when available."),
				speed_options: [standard_speed],
				image_input: true,
				local_tools: true,
				mcp: false,
				web_search: true,
			},
		},
		{
			id: "opencode-zen-sol",
			name: "GPT 5.6 Sol",
			native_model_id: "openai/gpt-5.6-sol",
			harness: "opencode",
			provider: "openai",
			routing: { gateway_id: "zen", kind: "gateway" },
			status: "prototype",
			capabilities: {
				thinking: native_thinking("Defined by the selected provider and model route."),
				speed_options: [standard_speed],
				image_input: false,
				local_tools: true,
				mcp: true,
				web_search: false,
			},
		},
		{
			id: "opencode-go-sonnet",
			name: "Claude Sonnet 4.6",
			native_model_id: "anthropic/claude-sonnet-4-6",
			harness: "opencode",
			provider: "anthropic",
			routing: { gateway_id: "go", kind: "gateway" },
			status: "prototype",
			capabilities: {
				thinking: native_thinking("Defined by the selected provider and model route."),
				speed_options: [standard_speed],
				image_input: false,
				local_tools: true,
				mcp: true,
				web_search: false,
			},
		},
		{
			id: "opencode-black-grok",
			name: "Grok 4.5",
			native_model_id: "xai/grok-4-5",
			harness: "opencode",
			provider: "xai",
			routing: { gateway_id: "black", kind: "gateway" },
			status: "prototype",
			capabilities: {
				thinking: native_thinking("Defined by the selected provider and model route."),
				speed_options: [standard_speed],
				image_input: false,
				local_tools: true,
				mcp: true,
				web_search: false,
			},
		},
		{
			id: "opencode-qwen",
			name: "Qwen Coder",
			native_model_id: "qwen/qwen-coder",
			harness: "opencode",
			provider: "alibaba",
			routing: { gateway_id: "alibaba", kind: "gateway" },
			status: "prototype",
			capabilities: {
				thinking: native_thinking("Defined by the configured OpenCode provider route."),
				speed_options: [standard_speed],
				image_input: false,
				local_tools: true,
				mcp: true,
				web_search: false,
			},
		},
		{
			id: "opencode-kimi",
			name: "Kimi K3",
			native_model_id: "moonshot/kimi-k3",
			harness: "opencode",
			provider: "moonshot",
			routing: { gateway_id: "moonshot", kind: "gateway" },
			status: "prototype",
			capabilities: {
				thinking: native_thinking("Defined by the configured OpenCode provider route."),
				speed_options: [standard_speed],
				image_input: false,
				local_tools: true,
				mcp: true,
				web_search: false,
			},
		},
		{
			id: "opencode-deepseek",
			name: "DeepSeek V4",
			native_model_id: "deepseek/deepseek-v4",
			harness: "opencode",
			provider: "deepseek",
			routing: { gateway_id: "deepseek", kind: "gateway" },
			status: "prototype",
			capabilities: {
				thinking: native_thinking("Defined by the configured OpenCode provider route."),
				speed_options: [standard_speed],
				image_input: false,
				local_tools: true,
				mcp: true,
				web_search: false,
			},
		},
		{
			id: "antigravity-pro",
			name: "Gemini 3.1 Pro High",
			native_model_id: "gemini-3.1-pro-high",
			harness: "antigravity",
			provider: "google",
			routing: { kind: "default" },
			status: "prototype",
			capabilities: {
				thinking: native_thinking("Pending an Antigravity adapter contract."),
				speed_options: [standard_speed],
				image_input: true,
				local_tools: false,
				mcp: false,
				web_search: true,
			},
		},
	],
});
