[package]
name = "artisan-transport"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
artisan-domain = { path = "../domain" }
artisan-protocol = { path = "../protocol" }
quinn.workspace = true
rustls.workspace = true
rustls-pki-types.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["macros", "net", "rt", "sync", "time"] }

[dev-dependencies]
rcgen.workspace = true

[lints]
workspace = true
