// @generated by the capnpc-rust plugin to the Cap'n Proto schema compiler.
// DO NOT EDIT.
// source: stream.capnp
// capnp binary version: 1.1.0
// capnpc crate version: 0.27.0

pub mod stream_frame {
    pub use self::Which::{Bind, Chunk, End, Ready};

    #[derive(Copy, Clone)]
    pub struct Owned(());
    impl ::capnp::introspect::Introspect for Owned {
        fn introspect() -> ::capnp::introspect::Type {
            ::capnp::introspect::TypeVariant::Struct(::capnp::introspect::RawBrandedStructSchema {
                generic: &_private::RAW_SCHEMA,
                field_types: _private::get_field_types,
                annotation_types: _private::get_annotation_types,
                type_id: ::core::any::TypeId::of::<Owned>(),
            })
            .into()
        }
    }
    impl ::capnp::traits::Owned for Owned {
        type Reader<'a> = Reader<'a>;
        type Builder<'a> = Builder<'a>;
    }
    impl ::capnp::traits::OwnedStruct for Owned {
        type Reader<'a> = Reader<'a>;
        type Builder<'a> = Builder<'a>;
    }
    impl ::capnp::traits::Pipelined for Owned {
        type Pipeline = Pipeline;
    }

    pub struct Reader<'a> {
        reader: ::capnp::private::layout::StructReader<'a>,
    }
    impl ::core::marker::Copy for Reader<'_> {}
    impl ::core::clone::Clone for Reader<'_> {
        fn clone(&self) -> Self {
            *self
        }
    }

    impl ::capnp::traits::HasTypeId for Reader<'_> {
        const TYPE_ID: u64 = _private::TYPE_ID;
    }
    impl<'a> ::core::convert::From<::capnp::private::layout::StructReader<'a>> for Reader<'a> {
        fn from(reader: ::capnp::private::layout::StructReader<'a>) -> Self {
            Self { reader }
        }
    }

    impl<'a> ::core::convert::From<Reader<'a>> for ::capnp::dynamic_value::Reader<'a> {
        fn from(reader: Reader<'a>) -> Self {
            Self::Struct(::capnp::dynamic_struct::Reader::new(
                reader.reader,
                ::capnp::schema::StructSchema::new(::capnp::introspect::RawBrandedStructSchema {
                    generic: &_private::RAW_SCHEMA,
                    field_types: _private::get_field_types,
                    annotation_types: _private::get_annotation_types,
                    type_id: ::core::any::TypeId::of::<Owned>(),
                }),
            ))
        }
    }

    impl ::core::fmt::Debug for Reader<'_> {
        fn fmt(
            &self,
            f: &mut ::core::fmt::Formatter<'_>,
        ) -> ::core::result::Result<(), ::core::fmt::Error> {
            core::fmt::Debug::fmt(
                &::core::convert::Into::<::capnp::dynamic_value::Reader<'_>>::into(*self),
                f,
            )
        }
    }

    impl<'a> ::capnp::traits::FromPointerReader<'a> for Reader<'a> {
        fn get_from_pointer(
            reader: &::capnp::private::layout::PointerReader<'a>,
            default: ::core::option::Option<&'a [::capnp::Word]>,
        ) -> ::capnp::Result<Self> {
            ::core::result::Result::Ok(reader.get_struct(default)?.into())
        }
    }

    impl<'a> ::capnp::traits::IntoInternalStructReader<'a> for Reader<'a> {
        fn into_internal_struct_reader(self) -> ::capnp::private::layout::StructReader<'a> {
            self.reader
        }
    }

    impl<'a> ::capnp::traits::Imbue<'a> for Reader<'a> {
        fn imbue(&mut self, cap_table: &'a ::capnp::private::layout::CapTable) {
            self.reader
                .imbue(::capnp::private::layout::CapTableReader::from_ref(
                    cap_table,
                ))
        }
    }

    impl<'a> Reader<'a> {
        pub fn reborrow(&self) -> Reader<'_> {
            Self { ..*self }
        }

        pub fn total_size(&self) -> ::capnp::Result<::capnp::MessageSize> {
            self.reader.total_size()
        }
        #[inline]
        pub fn get_message_id(self) -> ::capnp::Result<::capnp::text::Reader<'a>> {
            ::capnp::traits::FromPointerReader::get_from_pointer(
                &self.reader.get_pointer_field(0),
                ::core::option::Option::None,
            )
        }
        #[inline]
        pub fn has_message_id(&self) -> bool {
            !self.reader.get_pointer_field(0).is_null()
        }
        #[inline]
        pub fn get_origin(
            self,
        ) -> ::core::result::Result<crate::common_capnp::Origin, ::capnp::NotInSchema> {
            ::core::convert::TryFrom::try_from(self.reader.get_data_field::<u16>(0))
        }
        #[inline]
        pub fn get_protocol_version(self) -> u16 {
            self.reader.get_data_field::<u16>(1)
        }
        #[inline]
        pub fn get_schema_version(self) -> u16 {
            self.reader.get_data_field::<u16>(2)
        }
        #[inline]
        pub fn get_sent_at(self) -> ::capnp::Result<::capnp::text::Reader<'a>> {
            ::capnp::traits::FromPointerReader::get_from_pointer(
                &self.reader.get_pointer_field(1),
                ::core::option::Option::None,
            )
        }
        #[inline]
        pub fn has_sent_at(&self) -> bool {
            !self.reader.get_pointer_field(1).is_null()
        }
        #[inline]
        pub fn get_channel_id(self) -> ::capnp::Result<::capnp::text::Reader<'a>> {
            ::capnp::traits::FromPointerReader::get_from_pointer(
                &self.reader.get_pointer_field(2),
                ::core::option::Option::None,
            )
        }
        #[inline]
        pub fn has_channel_id(&self) -> bool {
            !self.reader.get_pointer_field(2).is_null()
        }
        #[inline]
        pub fn get_channel_sequence(self) -> u64 {
            self.reader.get_data_field::<u64>(1)
        }
        #[inline]
        pub fn get_stream_id(self) -> ::capnp::Result<::capnp::text::Reader<'a>> {
            ::capnp::traits::FromPointerReader::get_from_pointer(
                &self.reader.get_pointer_field(3),
                ::core::option::Option::None,
            )
        }
        #[inline]
        pub fn has_stream_id(&self) -> bool {
            !self.reader.get_pointer_field(3).is_null()
        }
        #[inline]
        pub fn which(self) -> ::core::result::Result<WhichReader<'a>, ::capnp::NotInSchema> {
            match self.reader.get_data_field::<u16>(3) {
                0 => ::core::result::Result::Ok(Bind(self.reader.into())),
                1 => ::core::result::Result::Ok(Ready(self.reader.into())),
                2 => ::core::result::Result::Ok(Chunk(self.reader.into())),
                3 => ::core::result::Result::Ok(End(self.reader.into())),
                x => ::core::result::Result::Err(::capnp::NotInSchema(x)),
            }
        }
    }

    pub struct Builder<'a> {
        builder: ::capnp::private::layout::StructBuilder<'a>,
    }
    impl ::capnp::traits::HasStructSize for Builder<'_> {
        const STRUCT_SIZE: ::capnp::private::layout::StructSize =
            ::capnp::private::layout::StructSize {
                data: 3,
                pointers: 5,
            };
    }
    impl ::capnp::traits::HasTypeId for Builder<'_> {
        const TYPE_ID: u64 = _private::TYPE_ID;
    }
    impl<'a> ::core::convert::From<::capnp::private::layout::StructBuilder<'a>> for Builder<'a> {
        fn from(builder: ::capnp::private::layout::StructBuilder<'a>) -> Self {
            Self { builder }
        }
    }

    impl<'a> ::core::convert::From<Builder<'a>> for ::capnp::dynamic_value::Builder<'a> {
        fn from(builder: Builder<'a>) -> Self {
            Self::Struct(::capnp::dynamic_struct::Builder::new(
                builder.builder,
                ::capnp::schema::StructSchema::new(::capnp::introspect::RawBrandedStructSchema {
                    generic: &_private::RAW_SCHEMA,
                    field_types: _private::get_field_types,
                    annotation_types: _private::get_annotation_types,
                    type_id: ::core::any::TypeId::of::<Owned>(),
                }),
            ))
        }
    }

    impl<'a> ::capnp::traits::ImbueMut<'a> for Builder<'a> {
        fn imbue_mut(&mut self, cap_table: &'a mut ::capnp::private::layout::CapTable) {
            self.builder
                .imbue(::capnp::private::layout::CapTableBuilder::from_ref(
                    cap_table,
                ))
        }
    }

    impl<'a> ::capnp::traits::FromPointerBuilder<'a> for Builder<'a> {
        fn init_pointer(builder: ::capnp::private::layout::PointerBuilder<'a>, _size: u32) -> Self {
            builder
                .init_struct(<Self as ::capnp::traits::HasStructSize>::STRUCT_SIZE)
                .into()
        }
        fn get_from_pointer(
            builder: ::capnp::private::layout::PointerBuilder<'a>,
            default: ::core::option::Option<&'a [::capnp::Word]>,
        ) -> ::capnp::Result<Self> {
            ::core::result::Result::Ok(
                builder
                    .get_struct(
                        <Self as ::capnp::traits::HasStructSize>::STRUCT_SIZE,
                        default,
                    )?
                    .into(),
            )
        }
    }

    impl ::capnp::traits::SetterInput<Owned> for Reader<'_> {
        fn set_pointer_builder(
            mut pointer: ::capnp::private::layout::PointerBuilder<'_>,
            value: Self,
            canonicalize: bool,
        ) -> ::capnp::Result<()> {
            pointer.set_struct(&value.reader, canonicalize)
        }
    }

    impl<'a> Builder<'a> {
        pub fn into_reader(self) -> Reader<'a> {
            self.builder.into_reader().into()
        }
        pub fn reborrow(&mut self) -> Builder<'_> {
            Builder {
                builder: self.builder.reborrow(),
            }
        }
        pub fn reborrow_as_reader(&self) -> Reader<'_> {
            self.builder.as_reader().into()
        }

        pub fn total_size(&self) -> ::capnp::Result<::capnp::MessageSize> {
            self.builder.as_reader().total_size()
        }
        #[inline]
        pub fn get_message_id(self) -> ::capnp::Result<::capnp::text::Builder<'a>> {
            ::capnp::traits::FromPointerBuilder::get_from_pointer(
                self.builder.get_pointer_field(0),
                ::core::option::Option::None,
            )
        }
        #[inline]
        pub fn set_message_id(
            &mut self,
            value: impl ::capnp::traits::SetterInput<::capnp::text::Owned>,
        ) {
            ::capnp::traits::SetterInput::set_pointer_builder(
                self.builder.reborrow().get_pointer_field(0),
                value,
                false,
            )
            .unwrap()
        }
        #[inline]
        pub fn init_message_id(self, size: u32) -> ::capnp::text::Builder<'a> {
            self.builder.get_pointer_field(0).init_text(size)
        }
        #[inline]
        pub fn has_message_id(&self) -> bool {
            !self.builder.is_pointer_field_null(0)
        }
        #[inline]
        pub fn get_origin(
            self,
        ) -> ::core::result::Result<crate::common_capnp::Origin, ::capnp::NotInSchema> {
            ::core::convert::TryFrom::try_from(self.builder.get_data_field::<u16>(0))
        }
        #[inline]
        pub fn set_origin(&mut self, value: crate::common_capnp::Origin) {
            self.builder.set_data_field::<u16>(0, value as u16);
        }
        #[inline]
        pub fn get_protocol_version(self) -> u16 {
            self.builder.get_data_field::<u16>(1)
        }
        #[inline]
        pub fn set_protocol_version(&mut self, value: u16) {
            self.builder.set_data_field::<u16>(1, value);
        }
        #[inline]
        pub fn get_schema_version(self) -> u16 {
            self.builder.get_data_field::<u16>(2)
        }
        #[inline]
        pub fn set_schema_version(&mut self, value: u16) {
            self.builder.set_data_field::<u16>(2, value);
        }
        #[inline]
        pub fn get_sent_at(self) -> ::capnp::Result<::capnp::text::Builder<'a>> {
            ::capnp::traits::FromPointerBuilder::get_from_pointer(
                self.builder.get_pointer_field(1),
                ::core::option::Option::None,
            )
        }
        #[inline]
        pub fn set_sent_at(
            &mut self,
            value: impl ::capnp::traits::SetterInput<::capnp::text::Owned>,
        ) {
            ::capnp::traits::SetterInput::set_pointer_builder(
                self.builder.reborrow().get_pointer_field(1),
                value,
                false,
            )
            .unwrap()
        }
        #[inline]
        pub fn init_sent_at(self, size: u32) -> ::capnp::text::Builder<'a> {
            self.builder.get_pointer_field(1).init_text(size)
        }
        #[inline]
        pub fn has_sent_at(&self) -> bool {
            !self.builder.is_pointer_field_null(1)
        }
        #[inline]
        pub fn get_channel_id(self) -> ::capnp::Result<::capnp::text::Builder<'a>> {
            ::capnp::traits::FromPointerBuilder::get_from_pointer(
                self.builder.get_pointer_field(2),
                ::core::option::Option::None,
            )
        }
        #[inline]
        pub fn set_channel_id(
            &mut self,
            value: impl ::capnp::traits::SetterInput<::capnp::text::Owned>,
        ) {
            ::capnp::traits::SetterInput::set_pointer_builder(
                self.builder.reborrow().get_pointer_field(2),
                value,
                false,
            )
            .unwrap()
        }
        #[inline]
        pub fn init_channel_id(self, size: u32) -> ::capnp::text::Builder<'a> {
            self.builder.get_pointer_field(2).init_text(size)
        }
        #[inline]
        pub fn has_channel_id(&self) -> bool {
            !self.builder.is_pointer_field_null(2)
        }
        #[inline]
        pub fn get_channel_sequence(self) -> u64 {
            self.builder.get_data_field::<u64>(1)
        }
        #[inline]
        pub fn set_channel_sequence(&mut self, value: u64) {
            self.builder.set_data_field::<u64>(1, value);
        }
        #[inline]
        pub fn get_stream_id(self) -> ::capnp::Result<::capnp::text::Builder<'a>> {
            ::capnp::traits::FromPointerBuilder::get_from_pointer(
                self.builder.get_pointer_field(3),
                ::core::option::Option::None,
            )
        }
        #[inline]
        pub fn set_stream_id(
            &mut self,
            value: impl ::capnp::traits::SetterInput<::capnp::text::Owned>,
        ) {
            ::capnp::traits::SetterInput::set_pointer_builder(
                self.builder.reborrow().get_pointer_field(3),
                value,
                false,
            )
            .unwrap()
        }
        #[inline]
        pub fn init_stream_id(self, size: u32) -> ::capnp::text::Builder<'a> {
            self.builder.get_pointer_field(3).init_text(size)
        }
        #[inline]
        pub fn has_stream_id(&self) -> bool {
            !self.builder.is_pointer_field_null(3)
        }
        #[inline]
        pub fn init_bind(mut self) -> crate::stream_capnp::stream_frame::bind::Builder<'a> {
            self.builder.set_data_field::<u16>(3, 0);
            self.builder.reborrow().get_pointer_field(4).clear();
            self.builder.into()
        }
        #[inline]
        pub fn init_ready(mut self) -> crate::stream_capnp::stream_frame::ready::Builder<'a> {
            self.builder.set_data_field::<u16>(3, 1);
            self.builder.reborrow().get_pointer_field(4).clear();
            self.builder.into()
        }
        #[inline]
        pub fn init_chunk(mut self) -> crate::stream_capnp::stream_frame::chunk::Builder<'a> {
            self.builder.set_data_field::<u16>(3, 2);
            self.builder.set_data_field::<u16>(8, 0);
            self.builder.reborrow().get_pointer_field(4).clear();
            self.builder.into()
        }
        #[inline]
        pub fn init_end(mut self) -> crate::stream_capnp::stream_frame::end::Builder<'a> {
            self.builder.set_data_field::<u16>(3, 3);
            self.builder.reborrow().get_pointer_field(4).clear();
            self.builder.into()
        }
        #[inline]
        pub fn which(self) -> ::core::result::Result<WhichBuilder<'a>, ::capnp::NotInSchema> {
            match self.builder.get_data_field::<u16>(3) {
                0 => ::core::result::Result::Ok(Bind(self.builder.into())),
                1 => ::core::result::Result::Ok(Ready(self.builder.into())),
                2 => ::core::result::Result::Ok(Chunk(self.builder.into())),
                3 => ::core::result::Result::Ok(End(self.builder.into())),
                x => ::core::result::Result::Err(::capnp::NotInSchema(x)),
            }
        }
    }

    pub struct Pipeline {
        _typeless: ::capnp::any_pointer::Pipeline,
    }
    impl ::capnp::capability::FromTypelessPipeline for Pipeline {
        fn new(typeless: ::capnp::any_pointer::Pipeline) -> Self {
            Self {
                _typeless: typeless,
            }
        }
    }
    impl Pipeline {}
    mod _private {
        pub(crate) static ENCODED_NODE: [::capnp::Word; 177] = [
            ::capnp::word(0, 0, 0, 0, 6, 0, 6, 0),
            ::capnp::word(170, 114, 251, 51, 166, 55, 70, 153),
            ::capnp::word(13, 0, 0, 0, 1, 0, 3, 0),
            ::capnp::word(87, 64, 140, 46, 61, 169, 241, 183),
            ::capnp::word(5, 0, 7, 0, 0, 0, 4, 0),
            ::capnp::word(3, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(254, 2, 0, 0, 206, 7, 0, 0),
            ::capnp::word(21, 0, 0, 0, 202, 0, 0, 0),
            ::capnp::word(33, 0, 0, 0, 7, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(29, 0, 0, 0, 167, 2, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(115, 116, 114, 101, 97, 109, 46, 99),
            ::capnp::word(97, 112, 110, 112, 58, 83, 116, 114),
            ::capnp::word(101, 97, 109, 70, 114, 97, 109, 101),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 1, 0, 1, 0),
            ::capnp::word(48, 0, 0, 0, 3, 0, 4, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(0, 0, 1, 0, 0, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(65, 1, 0, 0, 82, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(64, 1, 0, 0, 3, 0, 1, 0),
            ::capnp::word(76, 1, 0, 0, 2, 0, 1, 0),
            ::capnp::word(1, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(0, 0, 1, 0, 1, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(73, 1, 0, 0, 58, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(68, 1, 0, 0, 3, 0, 1, 0),
            ::capnp::word(80, 1, 0, 0, 2, 0, 1, 0),
            ::capnp::word(2, 0, 0, 0, 1, 0, 0, 0),
            ::capnp::word(0, 0, 1, 0, 2, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(77, 1, 0, 0, 130, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(76, 1, 0, 0, 3, 0, 1, 0),
            ::capnp::word(88, 1, 0, 0, 2, 0, 1, 0),
            ::capnp::word(3, 0, 0, 0, 2, 0, 0, 0),
            ::capnp::word(0, 0, 1, 0, 3, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(85, 1, 0, 0, 114, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(84, 1, 0, 0, 3, 0, 1, 0),
            ::capnp::word(96, 1, 0, 0, 2, 0, 1, 0),
            ::capnp::word(4, 0, 0, 0, 1, 0, 0, 0),
            ::capnp::word(0, 0, 1, 0, 4, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(93, 1, 0, 0, 58, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(88, 1, 0, 0, 3, 0, 1, 0),
            ::capnp::word(100, 1, 0, 0, 2, 0, 1, 0),
            ::capnp::word(5, 0, 0, 0, 2, 0, 0, 0),
            ::capnp::word(0, 0, 1, 0, 5, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(97, 1, 0, 0, 82, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(96, 1, 0, 0, 3, 0, 1, 0),
            ::capnp::word(108, 1, 0, 0, 2, 0, 1, 0),
            ::capnp::word(6, 0, 0, 0, 1, 0, 0, 0),
            ::capnp::word(0, 0, 1, 0, 6, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(105, 1, 0, 0, 130, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(104, 1, 0, 0, 3, 0, 1, 0),
            ::capnp::word(116, 1, 0, 0, 2, 0, 1, 0),
            ::capnp::word(7, 0, 0, 0, 3, 0, 0, 0),
            ::capnp::word(0, 0, 1, 0, 7, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(113, 1, 0, 0, 74, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(112, 1, 0, 0, 3, 0, 1, 0),
            ::capnp::word(124, 1, 0, 0, 2, 0, 1, 0),
            ::capnp::word(8, 0, 255, 255, 0, 0, 0, 0),
            ::capnp::word(1, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(212, 120, 55, 58, 120, 201, 150, 252),
            ::capnp::word(121, 1, 0, 0, 42, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(9, 0, 254, 255, 0, 0, 0, 0),
            ::capnp::word(1, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(109, 184, 129, 183, 69, 98, 230, 148),
            ::capnp::word(97, 1, 0, 0, 50, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(10, 0, 253, 255, 0, 0, 0, 0),
            ::capnp::word(1, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(45, 92, 238, 207, 8, 48, 194, 174),
            ::capnp::word(73, 1, 0, 0, 50, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(11, 0, 252, 255, 0, 0, 0, 0),
            ::capnp::word(1, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(115, 117, 146, 133, 116, 151, 3, 179),
            ::capnp::word(49, 1, 0, 0, 34, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(109, 101, 115, 115, 97, 103, 101, 73),
            ::capnp::word(100, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(12, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(12, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(111, 114, 105, 103, 105, 110, 0, 0),
            ::capnp::word(15, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(30, 57, 191, 2, 39, 105, 97, 221),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(15, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(112, 114, 111, 116, 111, 99, 111, 108),
            ::capnp::word(86, 101, 114, 115, 105, 111, 110, 0),
            ::capnp::word(7, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(7, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(115, 99, 104, 101, 109, 97, 86, 101),
            ::capnp::word(114, 115, 105, 111, 110, 0, 0, 0),
            ::capnp::word(7, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(7, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(115, 101, 110, 116, 65, 116, 0, 0),
            ::capnp::word(12, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(12, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(99, 104, 97, 110, 110, 101, 108, 73),
            ::capnp::word(100, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(12, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(12, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(99, 104, 97, 110, 110, 101, 108, 83),
            ::capnp::word(101, 113, 117, 101, 110, 99, 101, 0),
            ::capnp::word(9, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(9, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(115, 116, 114, 101, 97, 109, 73, 100),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(12, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(12, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ::capnp::word(98, 105, 110, 100, 0, 0, 0, 0),
            ::capnp::word(114, 101, 97, 100, 121, 0, 0, 0),
            ::capnp::word(99, 104, 117, 110, 107, 0, 0, 0),
            ::capnp::word(101, 110, 100, 0, 0, 0, 0, 0),
        ];
        pub(crate) fn get_field_types(index: u16) -> ::capnp::introspect::Type {
            match index {
                0 => <::capnp::text::Owned as ::capnp::introspect::Introspect>::introspect(),
                1 => <crate::common_capnp::Origin as ::capnp::introspect::Introspect>::introspect(),
                2 => <u16 as ::capnp::introspect::Introspect>::introspect(),
                3 => <u16 as ::capnp::introspect::Introspect>::introspect(),
                4 => <::capnp::text::Owned as ::capnp::introspect::Introspect>::introspect(),
                5 => <::capnp::text::Owned as ::capnp::introspect::Introspect>::introspect(),
                6 => <u64 as ::capnp::introspect::Introspect>::introspect(),
                7 => <::capnp::text::Owned as ::capnp::introspect::Introspect>::introspect(),
                8 => <crate::stream_capnp::stream_frame::bind::Owned as ::capnp::introspect::Introspect>::introspect(),
                9 => <crate::stream_capnp::stream_frame::ready::Owned as ::capnp::introspect::Introspect>::introspect(),
                10 => <crate::stream_capnp::stream_frame::chunk::Owned as ::capnp::introspect::Introspect>::introspect(),
                11 => <crate::stream_capnp::stream_frame::end::Owned as ::capnp::introspect::Introspect>::introspect(),
                _ => ::capnp::introspect::panic_invalid_field_index(index),
            }
        }
        pub(crate) fn get_annotation_types(
            child_index: Option<u16>,
            index: u32,
        ) -> ::capnp::introspect::Type {
            ::capnp::introspect::panic_invalid_annotation_indices(child_index, index)
        }
        pub(crate) static ARENA: ::capnp::private::arena::GeneratedCodeArena =
            ::capnp::private::arena::GeneratedCodeArena::new(&ENCODED_NODE);
        pub(crate) static RAW_SCHEMA: ::capnp::introspect::RawStructSchema =
            ::capnp::introspect::RawStructSchema::new(
                &ARENA,
                NONUNION_MEMBERS,
                MEMBERS_BY_DISCRIMINANT,
                MEMBERS_BY_NAME,
            );
        pub(crate) static NONUNION_MEMBERS: &[u16] = &[0, 1, 2, 3, 4, 5, 6, 7];
        pub(crate) static MEMBERS_BY_DISCRIMINANT: &[u16] = &[8, 9, 10, 11];
        pub(crate) static MEMBERS_BY_NAME: &[u16] = &[8, 5, 6, 10, 11, 0, 1, 2, 9, 3, 4, 7];
        pub(crate) const TYPE_ID: u64 = 0x9946_37a6_33fb_72aa;
    }
    pub enum Which<A0, A1, A2, A3> {
        Bind(A0),
        Ready(A1),
        Chunk(A2),
        End(A3),
    }
    pub type WhichReader<'a> = Which<
        crate::stream_capnp::stream_frame::bind::Reader<'a>,
        crate::stream_capnp::stream_frame::ready::Reader<'a>,
        crate::stream_capnp::stream_frame::chunk::Reader<'a>,
        crate::stream_capnp::stream_frame::end::Reader<'a>,
    >;
    pub type WhichBuilder<'a> = Which<
        crate::stream_capnp::stream_frame::bind::Builder<'a>,
        crate::stream_capnp::stream_frame::ready::Builder<'a>,
        crate::stream_capnp::stream_frame::chunk::Builder<'a>,
        crate::stream_capnp::stream_frame::end::Builder<'a>,
    >;

    pub mod bind {
        #[derive(Copy, Clone)]
        pub struct Owned(());
        impl ::capnp::introspect::Introspect for Owned {
            fn introspect() -> ::capnp::introspect::Type {
                ::capnp::introspect::TypeVariant::Struct(
                    ::capnp::introspect::RawBrandedStructSchema {
                        generic: &_private::RAW_SCHEMA,
                        field_types: _private::get_field_types,
                        annotation_types: _private::get_annotation_types,
                        type_id: ::core::any::TypeId::of::<Owned>(),
                    },
                )
                .into()
            }
        }
        impl ::capnp::traits::Owned for Owned {
            type Reader<'a> = Reader<'a>;
            type Builder<'a> = Builder<'a>;
        }
        impl ::capnp::traits::OwnedStruct for Owned {
            type Reader<'a> = Reader<'a>;
            type Builder<'a> = Builder<'a>;
        }
        impl ::capnp::traits::Pipelined for Owned {
            type Pipeline = Pipeline;
        }

        pub struct Reader<'a> {
            reader: ::capnp::private::layout::StructReader<'a>,
        }
        impl ::core::marker::Copy for Reader<'_> {}
        impl ::core::clone::Clone for Reader<'_> {
            fn clone(&self) -> Self {
                *self
            }
        }

        impl ::capnp::traits::HasTypeId for Reader<'_> {
            const TYPE_ID: u64 = _private::TYPE_ID;
        }
        impl<'a> ::core::convert::From<::capnp::private::layout::StructReader<'a>> for Reader<'a> {
            fn from(reader: ::capnp::private::layout::StructReader<'a>) -> Self {
                Self { reader }
            }
        }

        impl<'a> ::core::convert::From<Reader<'a>> for ::capnp::dynamic_value::Reader<'a> {
            fn from(reader: Reader<'a>) -> Self {
                Self::Struct(::capnp::dynamic_struct::Reader::new(
                    reader.reader,
                    ::capnp::schema::StructSchema::new(
                        ::capnp::introspect::RawBrandedStructSchema {
                            generic: &_private::RAW_SCHEMA,
                            field_types: _private::get_field_types,
                            annotation_types: _private::get_annotation_types,
                            type_id: ::core::any::TypeId::of::<Owned>(),
                        },
                    ),
                ))
            }
        }

        impl ::core::fmt::Debug for Reader<'_> {
            fn fmt(
                &self,
                f: &mut ::core::fmt::Formatter<'_>,
            ) -> ::core::result::Result<(), ::core::fmt::Error> {
                core::fmt::Debug::fmt(
                    &::core::convert::Into::<::capnp::dynamic_value::Reader<'_>>::into(*self),
                    f,
                )
            }
        }

        impl<'a> ::capnp::traits::FromPointerReader<'a> for Reader<'a> {
            fn get_from_pointer(
                reader: &::capnp::private::layout::PointerReader<'a>,
                default: ::core::option::Option<&'a [::capnp::Word]>,
            ) -> ::capnp::Result<Self> {
                ::core::result::Result::Ok(reader.get_struct(default)?.into())
            }
        }

        impl<'a> ::capnp::traits::IntoInternalStructReader<'a> for Reader<'a> {
            fn into_internal_struct_reader(self) -> ::capnp::private::layout::StructReader<'a> {
                self.reader
            }
        }

        impl<'a> ::capnp::traits::Imbue<'a> for Reader<'a> {
            fn imbue(&mut self, cap_table: &'a ::capnp::private::layout::CapTable) {
                self.reader
                    .imbue(::capnp::private::layout::CapTableReader::from_ref(
                        cap_table,
                    ))
            }
        }

        impl<'a> Reader<'a> {
            pub fn reborrow(&self) -> Reader<'_> {
                Self { ..*self }
            }

            pub fn total_size(&self) -> ::capnp::Result<::capnp::MessageSize> {
                self.reader.total_size()
            }
            #[inline]
            pub fn get_payload_stream_id(self) -> ::capnp::Result<::capnp::text::Reader<'a>> {
                ::capnp::traits::FromPointerReader::get_from_pointer(
                    &self.reader.get_pointer_field(4),
                    ::core::option::Option::None,
                )
            }
            #[inline]
            pub fn has_payload_stream_id(&self) -> bool {
                !self.reader.get_pointer_field(4).is_null()
            }
        }

        pub struct Builder<'a> {
            builder: ::capnp::private::layout::StructBuilder<'a>,
        }
        impl ::capnp::traits::HasStructSize for Builder<'_> {
            const STRUCT_SIZE: ::capnp::private::layout::StructSize =
                ::capnp::private::layout::StructSize {
                    data: 3,
                    pointers: 5,
                };
        }
        impl ::capnp::traits::HasTypeId for Builder<'_> {
            const TYPE_ID: u64 = _private::TYPE_ID;
        }
        impl<'a> ::core::convert::From<::capnp::private::layout::StructBuilder<'a>> for Builder<'a> {
            fn from(builder: ::capnp::private::layout::StructBuilder<'a>) -> Self {
                Self { builder }
            }
        }

        impl<'a> ::core::convert::From<Builder<'a>> for ::capnp::dynamic_value::Builder<'a> {
            fn from(builder: Builder<'a>) -> Self {
                Self::Struct(::capnp::dynamic_struct::Builder::new(
                    builder.builder,
                    ::capnp::schema::StructSchema::new(
                        ::capnp::introspect::RawBrandedStructSchema {
                            generic: &_private::RAW_SCHEMA,
                            field_types: _private::get_field_types,
                            annotation_types: _private::get_annotation_types,
                            type_id: ::core::any::TypeId::of::<Owned>(),
                        },
                    ),
                ))
            }
        }

        impl<'a> ::capnp::traits::ImbueMut<'a> for Builder<'a> {
            fn imbue_mut(&mut self, cap_table: &'a mut ::capnp::private::layout::CapTable) {
                self.builder
                    .imbue(::capnp::private::layout::CapTableBuilder::from_ref(
                        cap_table,
                    ))
            }
        }

        impl<'a> ::capnp::traits::FromPointerBuilder<'a> for Builder<'a> {
            fn init_pointer(
                builder: ::capnp::private::layout::PointerBuilder<'a>,
                _size: u32,
            ) -> Self {
                builder
                    .init_struct(<Self as ::capnp::traits::HasStructSize>::STRUCT_SIZE)
                    .into()
            }
            fn get_from_pointer(
                builder: ::capnp::private::layout::PointerBuilder<'a>,
                default: ::core::option::Option<&'a [::capnp::Word]>,
            ) -> ::capnp::Result<Self> {
                ::core::result::Result::Ok(
                    builder
                        .get_struct(
                            <Self as ::capnp::traits::HasStructSize>::STRUCT_SIZE,
                            default,
                        )?
                        .into(),
                )
            }
        }

        impl ::capnp::traits::SetterInput<Owned> for Reader<'_> {
            fn set_pointer_builder(
                mut pointer: ::capnp::private::layout::PointerBuilder<'_>,
                value: Self,
                canonicalize: bool,
            ) -> ::capnp::Result<()> {
                pointer.set_struct(&value.reader, canonicalize)
            }
        }

        impl<'a> Builder<'a> {
            pub fn into_reader(self) -> Reader<'a> {
                self.builder.into_reader().into()
            }
            pub fn reborrow(&mut self) -> Builder<'_> {
                Builder {
                    builder: self.builder.reborrow(),
                }
            }
            pub fn reborrow_as_reader(&self) -> Reader<'_> {
                self.builder.as_reader().into()
            }

            pub fn total_size(&self) -> ::capnp::Result<::capnp::MessageSize> {
                self.builder.as_reader().total_size()
            }
            #[inline]
            pub fn get_payload_stream_id(self) -> ::capnp::Result<::capnp::text::Builder<'a>> {
                ::capnp::traits::FromPointerBuilder::get_from_pointer(
                    self.builder.get_pointer_field(4),
                    ::core::option::Option::None,
                )
            }
            #[inline]
            pub fn set_payload_stream_id(
                &mut self,
                value: impl ::capnp::traits::SetterInput<::capnp::text::Owned>,
            ) {
                ::capnp::traits::SetterInput::set_pointer_builder(
                    self.builder.reborrow().get_pointer_field(4),
                    value,
                    false,
                )
                .unwrap()
            }
            #[inline]
            pub fn init_payload_stream_id(self, size: u32) -> ::capnp::text::Builder<'a> {
                self.builder.get_pointer_field(4).init_text(size)
            }
            #[inline]
            pub fn has_payload_stream_id(&self) -> bool {
                !self.builder.is_pointer_field_null(4)
            }
        }

        pub struct Pipeline {
            _typeless: ::capnp::any_pointer::Pipeline,
        }
        impl ::capnp::capability::FromTypelessPipeline for Pipeline {
            fn new(typeless: ::capnp::any_pointer::Pipeline) -> Self {
                Self {
                    _typeless: typeless,
                }
            }
        }
        impl Pipeline {}
        mod _private {
            pub(crate) static ENCODED_NODE: [::capnp::Word; 34] = [
                ::capnp::word(0, 0, 0, 0, 6, 0, 6, 0),
                ::capnp::word(212, 120, 55, 58, 120, 201, 150, 252),
                ::capnp::word(25, 0, 0, 0, 1, 0, 3, 0),
                ::capnp::word(170, 114, 251, 51, 166, 55, 70, 153),
                ::capnp::word(5, 0, 7, 0, 1, 0, 0, 0),
                ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(21, 0, 0, 0, 242, 0, 0, 0),
                ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(25, 0, 0, 0, 63, 0, 0, 0),
                ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(115, 116, 114, 101, 97, 109, 46, 99),
                ::capnp::word(97, 112, 110, 112, 58, 83, 116, 114),
                ::capnp::word(101, 97, 109, 70, 114, 97, 109, 101),
                ::capnp::word(46, 98, 105, 110, 100, 0, 0, 0),
                ::capnp::word(4, 0, 0, 0, 3, 0, 4, 0),
                ::capnp::word(0, 0, 0, 0, 4, 0, 0, 0),
                ::capnp::word(0, 0, 1, 0, 8, 0, 0, 0),
                ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(13, 0, 0, 0, 130, 0, 0, 0),
                ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(12, 0, 0, 0, 3, 0, 1, 0),
                ::capnp::word(24, 0, 0, 0, 2, 0, 1, 0),
                ::capnp::word(112, 97, 121, 108, 111, 97, 100, 83),
                ::capnp::word(116, 114, 101, 97, 109, 73, 100, 0),
                ::capnp::word(12, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(12, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ];
            pub(crate) fn get_field_types(index: u16) -> ::capnp::introspect::Type {
                match index {
                    0 => <::capnp::text::Owned as ::capnp::introspect::Introspect>::introspect(),
                    _ => ::capnp::introspect::panic_invalid_field_index(index),
                }
            }
            pub(crate) fn get_annotation_types(
                child_index: Option<u16>,
                index: u32,
            ) -> ::capnp::introspect::Type {
                ::capnp::introspect::panic_invalid_annotation_indices(child_index, index)
            }
            pub(crate) static ARENA: ::capnp::private::arena::GeneratedCodeArena =
                ::capnp::private::arena::GeneratedCodeArena::new(&ENCODED_NODE);
            pub(crate) static RAW_SCHEMA: ::capnp::introspect::RawStructSchema =
                ::capnp::introspect::RawStructSchema::new(
                    &ARENA,
                    NONUNION_MEMBERS,
                    MEMBERS_BY_DISCRIMINANT,
                    MEMBERS_BY_NAME,
                );
            pub(crate) static NONUNION_MEMBERS: &[u16] = &[0];
            pub(crate) static MEMBERS_BY_DISCRIMINANT: &[u16] = &[];
            pub(crate) static MEMBERS_BY_NAME: &[u16] = &[0];
            pub(crate) const TYPE_ID: u64 = 0xfc96_c978_3a37_78d4;
        }
    }

    pub mod ready {
        #[derive(Copy, Clone)]
        pub struct Owned(());
        impl ::capnp::introspect::Introspect for Owned {
            fn introspect() -> ::capnp::introspect::Type {
                ::capnp::introspect::TypeVariant::Struct(
                    ::capnp::introspect::RawBrandedStructSchema {
                        generic: &_private::RAW_SCHEMA,
                        field_types: _private::get_field_types,
                        annotation_types: _private::get_annotation_types,
                        type_id: ::core::any::TypeId::of::<Owned>(),
                    },
                )
                .into()
            }
        }
        impl ::capnp::traits::Owned for Owned {
            type Reader<'a> = Reader<'a>;
            type Builder<'a> = Builder<'a>;
        }
        impl ::capnp::traits::OwnedStruct for Owned {
            type Reader<'a> = Reader<'a>;
            type Builder<'a> = Builder<'a>;
        }
        impl ::capnp::traits::Pipelined for Owned {
            type Pipeline = Pipeline;
        }

        pub struct Reader<'a> {
            reader: ::capnp::private::layout::StructReader<'a>,
        }
        impl ::core::marker::Copy for Reader<'_> {}
        impl ::core::clone::Clone for Reader<'_> {
            fn clone(&self) -> Self {
                *self
            }
        }

        impl ::capnp::traits::HasTypeId for Reader<'_> {
            const TYPE_ID: u64 = _private::TYPE_ID;
        }
        impl<'a> ::core::convert::From<::capnp::private::layout::StructReader<'a>> for Reader<'a> {
            fn from(reader: ::capnp::private::layout::StructReader<'a>) -> Self {
                Self { reader }
            }
        }

        impl<'a> ::core::convert::From<Reader<'a>> for ::capnp::dynamic_value::Reader<'a> {
            fn from(reader: Reader<'a>) -> Self {
                Self::Struct(::capnp::dynamic_struct::Reader::new(
                    reader.reader,
                    ::capnp::schema::StructSchema::new(
                        ::capnp::introspect::RawBrandedStructSchema {
                            generic: &_private::RAW_SCHEMA,
                            field_types: _private::get_field_types,
                            annotation_types: _private::get_annotation_types,
                            type_id: ::core::any::TypeId::of::<Owned>(),
                        },
                    ),
                ))
            }
        }

        impl ::core::fmt::Debug for Reader<'_> {
            fn fmt(
                &self,
                f: &mut ::core::fmt::Formatter<'_>,
            ) -> ::core::result::Result<(), ::core::fmt::Error> {
                core::fmt::Debug::fmt(
                    &::core::convert::Into::<::capnp::dynamic_value::Reader<'_>>::into(*self),
                    f,
                )
            }
        }

        impl<'a> ::capnp::traits::FromPointerReader<'a> for Reader<'a> {
            fn get_from_pointer(
                reader: &::capnp::private::layout::PointerReader<'a>,
                default: ::core::option::Option<&'a [::capnp::Word]>,
            ) -> ::capnp::Result<Self> {
                ::core::result::Result::Ok(reader.get_struct(default)?.into())
            }
        }

        impl<'a> ::capnp::traits::IntoInternalStructReader<'a> for Reader<'a> {
            fn into_internal_struct_reader(self) -> ::capnp::private::layout::StructReader<'a> {
                self.reader
            }
        }

        impl<'a> ::capnp::traits::Imbue<'a> for Reader<'a> {
            fn imbue(&mut self, cap_table: &'a ::capnp::private::layout::CapTable) {
                self.reader
                    .imbue(::capnp::private::layout::CapTableReader::from_ref(
                        cap_table,
                    ))
            }
        }

        impl<'a> Reader<'a> {
            pub fn reborrow(&self) -> Reader<'_> {
                Self { ..*self }
            }

            pub fn total_size(&self) -> ::capnp::Result<::capnp::MessageSize> {
                self.reader.total_size()
            }
            #[inline]
            pub fn get_payload_stream_id(self) -> ::capnp::Result<::capnp::text::Reader<'a>> {
                ::capnp::traits::FromPointerReader::get_from_pointer(
                    &self.reader.get_pointer_field(4),
                    ::core::option::Option::None,
                )
            }
            #[inline]
            pub fn has_payload_stream_id(&self) -> bool {
                !self.reader.get_pointer_field(4).is_null()
            }
        }

        pub struct Builder<'a> {
            builder: ::capnp::private::layout::StructBuilder<'a>,
        }
        impl ::capnp::traits::HasStructSize for Builder<'_> {
            const STRUCT_SIZE: ::capnp::private::layout::StructSize =
                ::capnp::private::layout::StructSize {
                    data: 3,
                    pointers: 5,
                };
        }
        impl ::capnp::traits::HasTypeId for Builder<'_> {
            const TYPE_ID: u64 = _private::TYPE_ID;
        }
        impl<'a> ::core::convert::From<::capnp::private::layout::StructBuilder<'a>> for Builder<'a> {
            fn from(builder: ::capnp::private::layout::StructBuilder<'a>) -> Self {
                Self { builder }
            }
        }

        impl<'a> ::core::convert::From<Builder<'a>> for ::capnp::dynamic_value::Builder<'a> {
            fn from(builder: Builder<'a>) -> Self {
                Self::Struct(::capnp::dynamic_struct::Builder::new(
                    builder.builder,
                    ::capnp::schema::StructSchema::new(
                        ::capnp::introspect::RawBrandedStructSchema {
                            generic: &_private::RAW_SCHEMA,
                            field_types: _private::get_field_types,
                            annotation_types: _private::get_annotation_types,
                            type_id: ::core::any::TypeId::of::<Owned>(),
                        },
                    ),
                ))
            }
        }

        impl<'a> ::capnp::traits::ImbueMut<'a> for Builder<'a> {
            fn imbue_mut(&mut self, cap_table: &'a mut ::capnp::private::layout::CapTable) {
                self.builder
                    .imbue(::capnp::private::layout::CapTableBuilder::from_ref(
                        cap_table,
                    ))
            }
        }

        impl<'a> ::capnp::traits::FromPointerBuilder<'a> for Builder<'a> {
            fn init_pointer(
                builder: ::capnp::private::layout::PointerBuilder<'a>,
                _size: u32,
            ) -> Self {
                builder
                    .init_struct(<Self as ::capnp::traits::HasStructSize>::STRUCT_SIZE)
                    .into()
            }
            fn get_from_pointer(
                builder: ::capnp::private::layout::PointerBuilder<'a>,
                default: ::core::option::Option<&'a [::capnp::Word]>,
            ) -> ::capnp::Result<Self> {
                ::core::result::Result::Ok(
                    builder
                        .get_struct(
                            <Self as ::capnp::traits::HasStructSize>::STRUCT_SIZE,
                            default,
                        )?
                        .into(),
                )
            }
        }

        impl ::capnp::traits::SetterInput<Owned> for Reader<'_> {
            fn set_pointer_builder(
                mut pointer: ::capnp::private::layout::PointerBuilder<'_>,
                value: Self,
                canonicalize: bool,
            ) -> ::capnp::Result<()> {
                pointer.set_struct(&value.reader, canonicalize)
            }
        }

        impl<'a> Builder<'a> {
            pub fn into_reader(self) -> Reader<'a> {
                self.builder.into_reader().into()
            }
            pub fn reborrow(&mut self) -> Builder<'_> {
                Builder {
                    builder: self.builder.reborrow(),
                }
            }
            pub fn reborrow_as_reader(&self) -> Reader<'_> {
                self.builder.as_reader().into()
            }

            pub fn total_size(&self) -> ::capnp::Result<::capnp::MessageSize> {
                self.builder.as_reader().total_size()
            }
            #[inline]
            pub fn get_payload_stream_id(self) -> ::capnp::Result<::capnp::text::Builder<'a>> {
                ::capnp::traits::FromPointerBuilder::get_from_pointer(
                    self.builder.get_pointer_field(4),
                    ::core::option::Option::None,
                )
            }
            #[inline]
            pub fn set_payload_stream_id(
                &mut self,
                value: impl ::capnp::traits::SetterInput<::capnp::text::Owned>,
            ) {
                ::capnp::traits::SetterInput::set_pointer_builder(
                    self.builder.reborrow().get_pointer_field(4),
                    value,
                    false,
                )
                .unwrap()
            }
            #[inline]
            pub fn init_payload_stream_id(self, size: u32) -> ::capnp::text::Builder<'a> {
                self.builder.get_pointer_field(4).init_text(size)
            }
            #[inline]
            pub fn has_payload_stream_id(&self) -> bool {
                !self.builder.is_pointer_field_null(4)
            }
        }

        pub struct Pipeline {
            _typeless: ::capnp::any_pointer::Pipeline,
        }
        impl ::capnp::capability::FromTypelessPipeline for Pipeline {
            fn new(typeless: ::capnp::any_pointer::Pipeline) -> Self {
                Self {
                    _typeless: typeless,
                }
            }
        }
        impl Pipeline {}
        mod _private {
            pub(crate) static ENCODED_NODE: [::capnp::Word; 34] = [
                ::capnp::word(0, 0, 0, 0, 6, 0, 6, 0),
                ::capnp::word(109, 184, 129, 183, 69, 98, 230, 148),
                ::capnp::word(25, 0, 0, 0, 1, 0, 3, 0),
                ::capnp::word(170, 114, 251, 51, 166, 55, 70, 153),
                ::capnp::word(5, 0, 7, 0, 1, 0, 0, 0),
                ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(21, 0, 0, 0, 250, 0, 0, 0),
                ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(25, 0, 0, 0, 63, 0, 0, 0),
                ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(115, 116, 114, 101, 97, 109, 46, 99),
                ::capnp::word(97, 112, 110, 112, 58, 83, 116, 114),
                ::capnp::word(101, 97, 109, 70, 114, 97, 109, 101),
                ::capnp::word(46, 114, 101, 97, 100, 121, 0, 0),
                ::capnp::word(4, 0, 0, 0, 3, 0, 4, 0),
                ::capnp::word(0, 0, 0, 0, 4, 0, 0, 0),
                ::capnp::word(0, 0, 1, 0, 9, 0, 0, 0),
                ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(13, 0, 0, 0, 130, 0, 0, 0),
                ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(12, 0, 0, 0, 3, 0, 1, 0),
                ::capnp::word(24, 0, 0, 0, 2, 0, 1, 0),
                ::capnp::word(112, 97, 121, 108, 111, 97, 100, 83),
                ::capnp::word(116, 114, 101, 97, 109, 73, 100, 0),
                ::capnp::word(12, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(12, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ];
            pub(crate) fn get_field_types(index: u16) -> ::capnp::introspect::Type {
                match index {
                    0 => <::capnp::text::Owned as ::capnp::introspect::Introspect>::introspect(),
                    _ => ::capnp::introspect::panic_invalid_field_index(index),
                }
            }
            pub(crate) fn get_annotation_types(
                child_index: Option<u16>,
                index: u32,
            ) -> ::capnp::introspect::Type {
                ::capnp::introspect::panic_invalid_annotation_indices(child_index, index)
            }
            pub(crate) static ARENA: ::capnp::private::arena::GeneratedCodeArena =
                ::capnp::private::arena::GeneratedCodeArena::new(&ENCODED_NODE);
            pub(crate) static RAW_SCHEMA: ::capnp::introspect::RawStructSchema =
                ::capnp::introspect::RawStructSchema::new(
                    &ARENA,
                    NONUNION_MEMBERS,
                    MEMBERS_BY_DISCRIMINANT,
                    MEMBERS_BY_NAME,
                );
            pub(crate) static NONUNION_MEMBERS: &[u16] = &[0];
            pub(crate) static MEMBERS_BY_DISCRIMINANT: &[u16] = &[];
            pub(crate) static MEMBERS_BY_NAME: &[u16] = &[0];
            pub(crate) const TYPE_ID: u64 = 0x94e6_6245_b781_b86d;
        }
    }

    pub mod chunk {
        pub use self::Which::{Bytes, Text};

        #[derive(Copy, Clone)]
        pub struct Owned(());
        impl ::capnp::introspect::Introspect for Owned {
            fn introspect() -> ::capnp::introspect::Type {
                ::capnp::introspect::TypeVariant::Struct(
                    ::capnp::introspect::RawBrandedStructSchema {
                        generic: &_private::RAW_SCHEMA,
                        field_types: _private::get_field_types,
                        annotation_types: _private::get_annotation_types,
                        type_id: ::core::any::TypeId::of::<Owned>(),
                    },
                )
                .into()
            }
        }
        impl ::capnp::traits::Owned for Owned {
            type Reader<'a> = Reader<'a>;
            type Builder<'a> = Builder<'a>;
        }
        impl ::capnp::traits::OwnedStruct for Owned {
            type Reader<'a> = Reader<'a>;
            type Builder<'a> = Builder<'a>;
        }
        impl ::capnp::traits::Pipelined for Owned {
            type Pipeline = Pipeline;
        }

        pub struct Reader<'a> {
            reader: ::capnp::private::layout::StructReader<'a>,
        }
        impl ::core::marker::Copy for Reader<'_> {}
        impl ::core::clone::Clone for Reader<'_> {
            fn clone(&self) -> Self {
                *self
            }
        }

        impl ::capnp::traits::HasTypeId for Reader<'_> {
            const TYPE_ID: u64 = _private::TYPE_ID;
        }
        impl<'a> ::core::convert::From<::capnp::private::layout::StructReader<'a>> for Reader<'a> {
            fn from(reader: ::capnp::private::layout::StructReader<'a>) -> Self {
                Self { reader }
            }
        }

        impl<'a> ::core::convert::From<Reader<'a>> for ::capnp::dynamic_value::Reader<'a> {
            fn from(reader: Reader<'a>) -> Self {
                Self::Struct(::capnp::dynamic_struct::Reader::new(
                    reader.reader,
                    ::capnp::schema::StructSchema::new(
                        ::capnp::introspect::RawBrandedStructSchema {
                            generic: &_private::RAW_SCHEMA,
                            field_types: _private::get_field_types,
                            annotation_types: _private::get_annotation_types,
                            type_id: ::core::any::TypeId::of::<Owned>(),
                        },
                    ),
                ))
            }
        }

        impl ::core::fmt::Debug for Reader<'_> {
            fn fmt(
                &self,
                f: &mut ::core::fmt::Formatter<'_>,
            ) -> ::core::result::Result<(), ::core::fmt::Error> {
                core::fmt::Debug::fmt(
                    &::core::convert::Into::<::capnp::dynamic_value::Reader<'_>>::into(*self),
                    f,
                )
            }
        }

        impl<'a> ::capnp::traits::FromPointerReader<'a> for Reader<'a> {
            fn get_from_pointer(
                reader: &::capnp::private::layout::PointerReader<'a>,
                default: ::core::option::Option<&'a [::capnp::Word]>,
            ) -> ::capnp::Result<Self> {
                ::core::result::Result::Ok(reader.get_struct(default)?.into())
            }
        }

        impl<'a> ::capnp::traits::IntoInternalStructReader<'a> for Reader<'a> {
            fn into_internal_struct_reader(self) -> ::capnp::private::layout::StructReader<'a> {
                self.reader
            }
        }

        impl<'a> ::capnp::traits::Imbue<'a> for Reader<'a> {
            fn imbue(&mut self, cap_table: &'a ::capnp::private::layout::CapTable) {
                self.reader
                    .imbue(::capnp::private::layout::CapTableReader::from_ref(
                        cap_table,
                    ))
            }
        }

        impl<'a> Reader<'a> {
            pub fn reborrow(&self) -> Reader<'_> {
                Self { ..*self }
            }

            pub fn total_size(&self) -> ::capnp::Result<::capnp::MessageSize> {
                self.reader.total_size()
            }
            #[inline]
            pub fn has_text(&self) -> bool {
                if self.reader.get_data_field::<u16>(8) != 0 {
                    return false;
                }
                !self.reader.get_pointer_field(4).is_null()
            }
            #[inline]
            pub fn has_bytes(&self) -> bool {
                if self.reader.get_data_field::<u16>(8) != 1 {
                    return false;
                }
                !self.reader.get_pointer_field(4).is_null()
            }
            #[inline]
            pub fn which(self) -> ::core::result::Result<WhichReader<'a>, ::capnp::NotInSchema> {
                match self.reader.get_data_field::<u16>(8) {
                    0 => ::core::result::Result::Ok(Text(
                        ::capnp::traits::FromPointerReader::get_from_pointer(
                            &self.reader.get_pointer_field(4),
                            ::core::option::Option::None,
                        ),
                    )),
                    1 => ::core::result::Result::Ok(Bytes(
                        ::capnp::traits::FromPointerReader::get_from_pointer(
                            &self.reader.get_pointer_field(4),
                            ::core::option::Option::None,
                        ),
                    )),
                    x => ::core::result::Result::Err(::capnp::NotInSchema(x)),
                }
            }
        }

        pub struct Builder<'a> {
            builder: ::capnp::private::layout::StructBuilder<'a>,
        }
        impl ::capnp::traits::HasStructSize for Builder<'_> {
            const STRUCT_SIZE: ::capnp::private::layout::StructSize =
                ::capnp::private::layout::StructSize {
                    data: 3,
                    pointers: 5,
                };
        }
        impl ::capnp::traits::HasTypeId for Builder<'_> {
            const TYPE_ID: u64 = _private::TYPE_ID;
        }
        impl<'a> ::core::convert::From<::capnp::private::layout::StructBuilder<'a>> for Builder<'a> {
            fn from(builder: ::capnp::private::layout::StructBuilder<'a>) -> Self {
                Self { builder }
            }
        }

        impl<'a> ::core::convert::From<Builder<'a>> for ::capnp::dynamic_value::Builder<'a> {
            fn from(builder: Builder<'a>) -> Self {
                Self::Struct(::capnp::dynamic_struct::Builder::new(
                    builder.builder,
                    ::capnp::schema::StructSchema::new(
                        ::capnp::introspect::RawBrandedStructSchema {
                            generic: &_private::RAW_SCHEMA,
                            field_types: _private::get_field_types,
                            annotation_types: _private::get_annotation_types,
                            type_id: ::core::any::TypeId::of::<Owned>(),
                        },
                    ),
                ))
            }
        }

        impl<'a> ::capnp::traits::ImbueMut<'a> for Builder<'a> {
            fn imbue_mut(&mut self, cap_table: &'a mut ::capnp::private::layout::CapTable) {
                self.builder
                    .imbue(::capnp::private::layout::CapTableBuilder::from_ref(
                        cap_table,
                    ))
            }
        }

        impl<'a> ::capnp::traits::FromPointerBuilder<'a> for Builder<'a> {
            fn init_pointer(
                builder: ::capnp::private::layout::PointerBuilder<'a>,
                _size: u32,
            ) -> Self {
                builder
                    .init_struct(<Self as ::capnp::traits::HasStructSize>::STRUCT_SIZE)
                    .into()
            }
            fn get_from_pointer(
                builder: ::capnp::private::layout::PointerBuilder<'a>,
                default: ::core::option::Option<&'a [::capnp::Word]>,
            ) -> ::capnp::Result<Self> {
                ::core::result::Result::Ok(
                    builder
                        .get_struct(
                            <Self as ::capnp::traits::HasStructSize>::STRUCT_SIZE,
                            default,
                        )?
                        .into(),
                )
            }
        }

        impl ::capnp::traits::SetterInput<Owned> for Reader<'_> {
            fn set_pointer_builder(
                mut pointer: ::capnp::private::layout::PointerBuilder<'_>,
                value: Self,
                canonicalize: bool,
            ) -> ::capnp::Result<()> {
                pointer.set_struct(&value.reader, canonicalize)
            }
        }

        impl<'a> Builder<'a> {
            pub fn into_reader(self) -> Reader<'a> {
                self.builder.into_reader().into()
            }
            pub fn reborrow(&mut self) -> Builder<'_> {
                Builder {
                    builder: self.builder.reborrow(),
                }
            }
            pub fn reborrow_as_reader(&self) -> Reader<'_> {
                self.builder.as_reader().into()
            }

            pub fn total_size(&self) -> ::capnp::Result<::capnp::MessageSize> {
                self.builder.as_reader().total_size()
            }
            #[inline]
            pub fn set_text(
                &mut self,
                value: impl ::capnp::traits::SetterInput<::capnp::text::Owned>,
            ) {
                self.builder.set_data_field::<u16>(8, 0);
                ::capnp::traits::SetterInput::set_pointer_builder(
                    self.builder.reborrow().get_pointer_field(4),
                    value,
                    false,
                )
                .unwrap()
            }
            #[inline]
            pub fn init_text(self, size: u32) -> ::capnp::text::Builder<'a> {
                self.builder.set_data_field::<u16>(8, 0);
                self.builder.get_pointer_field(4).init_text(size)
            }
            #[inline]
            pub fn has_text(&self) -> bool {
                if self.builder.get_data_field::<u16>(8) != 0 {
                    return false;
                }
                !self.builder.is_pointer_field_null(4)
            }
            #[inline]
            pub fn set_bytes(&mut self, value: ::capnp::data::Reader<'_>) {
                self.builder.set_data_field::<u16>(8, 1);
                self.builder.reborrow().get_pointer_field(4).set_data(value);
            }
            #[inline]
            pub fn init_bytes(self, size: u32) -> ::capnp::data::Builder<'a> {
                self.builder.set_data_field::<u16>(8, 1);
                self.builder.get_pointer_field(4).init_data(size)
            }
            #[inline]
            pub fn has_bytes(&self) -> bool {
                if self.builder.get_data_field::<u16>(8) != 1 {
                    return false;
                }
                !self.builder.is_pointer_field_null(4)
            }
            #[inline]
            pub fn which(self) -> ::core::result::Result<WhichBuilder<'a>, ::capnp::NotInSchema> {
                match self.builder.get_data_field::<u16>(8) {
                    0 => ::core::result::Result::Ok(Text(
                        ::capnp::traits::FromPointerBuilder::get_from_pointer(
                            self.builder.get_pointer_field(4),
                            ::core::option::Option::None,
                        ),
                    )),
                    1 => ::core::result::Result::Ok(Bytes(
                        ::capnp::traits::FromPointerBuilder::get_from_pointer(
                            self.builder.get_pointer_field(4),
                            ::core::option::Option::None,
                        ),
                    )),
                    x => ::core::result::Result::Err(::capnp::NotInSchema(x)),
                }
            }
        }

        pub struct Pipeline {
            _typeless: ::capnp::any_pointer::Pipeline,
        }
        impl ::capnp::capability::FromTypelessPipeline for Pipeline {
            fn new(typeless: ::capnp::any_pointer::Pipeline) -> Self {
                Self {
                    _typeless: typeless,
                }
            }
        }
        impl Pipeline {}
        mod _private {
            pub(crate) static ENCODED_NODE: [::capnp::Word; 48] = [
                ::capnp::word(0, 0, 0, 0, 6, 0, 6, 0),
                ::capnp::word(45, 92, 238, 207, 8, 48, 194, 174),
                ::capnp::word(25, 0, 0, 0, 1, 0, 3, 0),
                ::capnp::word(170, 114, 251, 51, 166, 55, 70, 153),
                ::capnp::word(5, 0, 7, 0, 1, 0, 2, 0),
                ::capnp::word(8, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(21, 0, 0, 0, 250, 0, 0, 0),
                ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(25, 0, 0, 0, 119, 0, 0, 0),
                ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(115, 116, 114, 101, 97, 109, 46, 99),
                ::capnp::word(97, 112, 110, 112, 58, 83, 116, 114),
                ::capnp::word(101, 97, 109, 70, 114, 97, 109, 101),
                ::capnp::word(46, 99, 104, 117, 110, 107, 0, 0),
                ::capnp::word(8, 0, 0, 0, 3, 0, 4, 0),
                ::capnp::word(0, 0, 255, 255, 4, 0, 0, 0),
                ::capnp::word(0, 0, 1, 0, 10, 0, 0, 0),
                ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(41, 0, 0, 0, 42, 0, 0, 0),
                ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(36, 0, 0, 0, 3, 0, 1, 0),
                ::capnp::word(48, 0, 0, 0, 2, 0, 1, 0),
                ::capnp::word(1, 0, 254, 255, 4, 0, 0, 0),
                ::capnp::word(0, 0, 1, 0, 11, 0, 0, 0),
                ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(45, 0, 0, 0, 50, 0, 0, 0),
                ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(40, 0, 0, 0, 3, 0, 1, 0),
                ::capnp::word(52, 0, 0, 0, 2, 0, 1, 0),
                ::capnp::word(116, 101, 120, 116, 0, 0, 0, 0),
                ::capnp::word(12, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(12, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(98, 121, 116, 101, 115, 0, 0, 0),
                ::capnp::word(13, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(13, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ];
            pub(crate) fn get_field_types(index: u16) -> ::capnp::introspect::Type {
                match index {
                    0 => <::capnp::text::Owned as ::capnp::introspect::Introspect>::introspect(),
                    1 => <::capnp::data::Owned as ::capnp::introspect::Introspect>::introspect(),
                    _ => ::capnp::introspect::panic_invalid_field_index(index),
                }
            }
            pub(crate) fn get_annotation_types(
                child_index: Option<u16>,
                index: u32,
            ) -> ::capnp::introspect::Type {
                ::capnp::introspect::panic_invalid_annotation_indices(child_index, index)
            }
            pub(crate) static ARENA: ::capnp::private::arena::GeneratedCodeArena =
                ::capnp::private::arena::GeneratedCodeArena::new(&ENCODED_NODE);
            pub(crate) static RAW_SCHEMA: ::capnp::introspect::RawStructSchema =
                ::capnp::introspect::RawStructSchema::new(
                    &ARENA,
                    NONUNION_MEMBERS,
                    MEMBERS_BY_DISCRIMINANT,
                    MEMBERS_BY_NAME,
                );
            pub(crate) static NONUNION_MEMBERS: &[u16] = &[];
            pub(crate) static MEMBERS_BY_DISCRIMINANT: &[u16] = &[0, 1];
            pub(crate) static MEMBERS_BY_NAME: &[u16] = &[1, 0];
            pub(crate) const TYPE_ID: u64 = 0xaec2_3008_cfee_5c2d;
        }
        pub enum Which<A0, A1> {
            Text(A0),
            Bytes(A1),
        }
        pub type WhichReader<'a> = Which<
            ::capnp::Result<::capnp::text::Reader<'a>>,
            ::capnp::Result<::capnp::data::Reader<'a>>,
        >;
        pub type WhichBuilder<'a> = Which<
            ::capnp::Result<::capnp::text::Builder<'a>>,
            ::capnp::Result<::capnp::data::Builder<'a>>,
        >;
    }

    pub mod end {
        #[derive(Copy, Clone)]
        pub struct Owned(());
        impl ::capnp::introspect::Introspect for Owned {
            fn introspect() -> ::capnp::introspect::Type {
                ::capnp::introspect::TypeVariant::Struct(
                    ::capnp::introspect::RawBrandedStructSchema {
                        generic: &_private::RAW_SCHEMA,
                        field_types: _private::get_field_types,
                        annotation_types: _private::get_annotation_types,
                        type_id: ::core::any::TypeId::of::<Owned>(),
                    },
                )
                .into()
            }
        }
        impl ::capnp::traits::Owned for Owned {
            type Reader<'a> = Reader<'a>;
            type Builder<'a> = Builder<'a>;
        }
        impl ::capnp::traits::OwnedStruct for Owned {
            type Reader<'a> = Reader<'a>;
            type Builder<'a> = Builder<'a>;
        }
        impl ::capnp::traits::Pipelined for Owned {
            type Pipeline = Pipeline;
        }

        pub struct Reader<'a> {
            reader: ::capnp::private::layout::StructReader<'a>,
        }
        impl ::core::marker::Copy for Reader<'_> {}
        impl ::core::clone::Clone for Reader<'_> {
            fn clone(&self) -> Self {
                *self
            }
        }

        impl ::capnp::traits::HasTypeId for Reader<'_> {
            const TYPE_ID: u64 = _private::TYPE_ID;
        }
        impl<'a> ::core::convert::From<::capnp::private::layout::StructReader<'a>> for Reader<'a> {
            fn from(reader: ::capnp::private::layout::StructReader<'a>) -> Self {
                Self { reader }
            }
        }

        impl<'a> ::core::convert::From<Reader<'a>> for ::capnp::dynamic_value::Reader<'a> {
            fn from(reader: Reader<'a>) -> Self {
                Self::Struct(::capnp::dynamic_struct::Reader::new(
                    reader.reader,
                    ::capnp::schema::StructSchema::new(
                        ::capnp::introspect::RawBrandedStructSchema {
                            generic: &_private::RAW_SCHEMA,
                            field_types: _private::get_field_types,
                            annotation_types: _private::get_annotation_types,
                            type_id: ::core::any::TypeId::of::<Owned>(),
                        },
                    ),
                ))
            }
        }

        impl ::core::fmt::Debug for Reader<'_> {
            fn fmt(
                &self,
                f: &mut ::core::fmt::Formatter<'_>,
            ) -> ::core::result::Result<(), ::core::fmt::Error> {
                core::fmt::Debug::fmt(
                    &::core::convert::Into::<::capnp::dynamic_value::Reader<'_>>::into(*self),
                    f,
                )
            }
        }

        impl<'a> ::capnp::traits::FromPointerReader<'a> for Reader<'a> {
            fn get_from_pointer(
                reader: &::capnp::private::layout::PointerReader<'a>,
                default: ::core::option::Option<&'a [::capnp::Word]>,
            ) -> ::capnp::Result<Self> {
                ::core::result::Result::Ok(reader.get_struct(default)?.into())
            }
        }

        impl<'a> ::capnp::traits::IntoInternalStructReader<'a> for Reader<'a> {
            fn into_internal_struct_reader(self) -> ::capnp::private::layout::StructReader<'a> {
                self.reader
            }
        }

        impl<'a> ::capnp::traits::Imbue<'a> for Reader<'a> {
            fn imbue(&mut self, cap_table: &'a ::capnp::private::layout::CapTable) {
                self.reader
                    .imbue(::capnp::private::layout::CapTableReader::from_ref(
                        cap_table,
                    ))
            }
        }

        impl<'a> Reader<'a> {
            pub fn reborrow(&self) -> Reader<'_> {
                Self { ..*self }
            }

            pub fn total_size(&self) -> ::capnp::Result<::capnp::MessageSize> {
                self.reader.total_size()
            }
            #[inline]
            pub fn get_reason(self) -> ::capnp::Result<::capnp::text::Reader<'a>> {
                ::capnp::traits::FromPointerReader::get_from_pointer(
                    &self.reader.get_pointer_field(4),
                    ::core::option::Option::None,
                )
            }
            #[inline]
            pub fn has_reason(&self) -> bool {
                !self.reader.get_pointer_field(4).is_null()
            }
        }

        pub struct Builder<'a> {
            builder: ::capnp::private::layout::StructBuilder<'a>,
        }
        impl ::capnp::traits::HasStructSize for Builder<'_> {
            const STRUCT_SIZE: ::capnp::private::layout::StructSize =
                ::capnp::private::layout::StructSize {
                    data: 3,
                    pointers: 5,
                };
        }
        impl ::capnp::traits::HasTypeId for Builder<'_> {
            const TYPE_ID: u64 = _private::TYPE_ID;
        }
        impl<'a> ::core::convert::From<::capnp::private::layout::StructBuilder<'a>> for Builder<'a> {
            fn from(builder: ::capnp::private::layout::StructBuilder<'a>) -> Self {
                Self { builder }
            }
        }

        impl<'a> ::core::convert::From<Builder<'a>> for ::capnp::dynamic_value::Builder<'a> {
            fn from(builder: Builder<'a>) -> Self {
                Self::Struct(::capnp::dynamic_struct::Builder::new(
                    builder.builder,
                    ::capnp::schema::StructSchema::new(
                        ::capnp::introspect::RawBrandedStructSchema {
                            generic: &_private::RAW_SCHEMA,
                            field_types: _private::get_field_types,
                            annotation_types: _private::get_annotation_types,
                            type_id: ::core::any::TypeId::of::<Owned>(),
                        },
                    ),
                ))
            }
        }

        impl<'a> ::capnp::traits::ImbueMut<'a> for Builder<'a> {
            fn imbue_mut(&mut self, cap_table: &'a mut ::capnp::private::layout::CapTable) {
                self.builder
                    .imbue(::capnp::private::layout::CapTableBuilder::from_ref(
                        cap_table,
                    ))
            }
        }

        impl<'a> ::capnp::traits::FromPointerBuilder<'a> for Builder<'a> {
            fn init_pointer(
                builder: ::capnp::private::layout::PointerBuilder<'a>,
                _size: u32,
            ) -> Self {
                builder
                    .init_struct(<Self as ::capnp::traits::HasStructSize>::STRUCT_SIZE)
                    .into()
            }
            fn get_from_pointer(
                builder: ::capnp::private::layout::PointerBuilder<'a>,
                default: ::core::option::Option<&'a [::capnp::Word]>,
            ) -> ::capnp::Result<Self> {
                ::core::result::Result::Ok(
                    builder
                        .get_struct(
                            <Self as ::capnp::traits::HasStructSize>::STRUCT_SIZE,
                            default,
                        )?
                        .into(),
                )
            }
        }

        impl ::capnp::traits::SetterInput<Owned> for Reader<'_> {
            fn set_pointer_builder(
                mut pointer: ::capnp::private::layout::PointerBuilder<'_>,
                value: Self,
                canonicalize: bool,
            ) -> ::capnp::Result<()> {
                pointer.set_struct(&value.reader, canonicalize)
            }
        }

        impl<'a> Builder<'a> {
            pub fn into_reader(self) -> Reader<'a> {
                self.builder.into_reader().into()
            }
            pub fn reborrow(&mut self) -> Builder<'_> {
                Builder {
                    builder: self.builder.reborrow(),
                }
            }
            pub fn reborrow_as_reader(&self) -> Reader<'_> {
                self.builder.as_reader().into()
            }

            pub fn total_size(&self) -> ::capnp::Result<::capnp::MessageSize> {
                self.builder.as_reader().total_size()
            }
            #[inline]
            pub fn get_reason(self) -> ::capnp::Result<::capnp::text::Builder<'a>> {
                ::capnp::traits::FromPointerBuilder::get_from_pointer(
                    self.builder.get_pointer_field(4),
                    ::core::option::Option::None,
                )
            }
            #[inline]
            pub fn set_reason(
                &mut self,
                value: impl ::capnp::traits::SetterInput<::capnp::text::Owned>,
            ) {
                ::capnp::traits::SetterInput::set_pointer_builder(
                    self.builder.reborrow().get_pointer_field(4),
                    value,
                    false,
                )
                .unwrap()
            }
            #[inline]
            pub fn init_reason(self, size: u32) -> ::capnp::text::Builder<'a> {
                self.builder.get_pointer_field(4).init_text(size)
            }
            #[inline]
            pub fn has_reason(&self) -> bool {
                !self.builder.is_pointer_field_null(4)
            }
        }

        pub struct Pipeline {
            _typeless: ::capnp::any_pointer::Pipeline,
        }
        impl ::capnp::capability::FromTypelessPipeline for Pipeline {
            fn new(typeless: ::capnp::any_pointer::Pipeline) -> Self {
                Self {
                    _typeless: typeless,
                }
            }
        }
        impl Pipeline {}
        mod _private {
            pub(crate) static ENCODED_NODE: [::capnp::Word; 33] = [
                ::capnp::word(0, 0, 0, 0, 6, 0, 6, 0),
                ::capnp::word(115, 117, 146, 133, 116, 151, 3, 179),
                ::capnp::word(25, 0, 0, 0, 1, 0, 3, 0),
                ::capnp::word(170, 114, 251, 51, 166, 55, 70, 153),
                ::capnp::word(5, 0, 7, 0, 1, 0, 0, 0),
                ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(21, 0, 0, 0, 234, 0, 0, 0),
                ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(25, 0, 0, 0, 63, 0, 0, 0),
                ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(115, 116, 114, 101, 97, 109, 46, 99),
                ::capnp::word(97, 112, 110, 112, 58, 83, 116, 114),
                ::capnp::word(101, 97, 109, 70, 114, 97, 109, 101),
                ::capnp::word(46, 101, 110, 100, 0, 0, 0, 0),
                ::capnp::word(4, 0, 0, 0, 3, 0, 4, 0),
                ::capnp::word(0, 0, 0, 0, 4, 0, 0, 0),
                ::capnp::word(0, 0, 1, 0, 12, 0, 0, 0),
                ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(13, 0, 0, 0, 58, 0, 0, 0),
                ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(8, 0, 0, 0, 3, 0, 1, 0),
                ::capnp::word(20, 0, 0, 0, 2, 0, 1, 0),
                ::capnp::word(114, 101, 97, 115, 111, 110, 0, 0),
                ::capnp::word(12, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(12, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
                ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
            ];
            pub(crate) fn get_field_types(index: u16) -> ::capnp::introspect::Type {
                match index {
                    0 => <::capnp::text::Owned as ::capnp::introspect::Introspect>::introspect(),
                    _ => ::capnp::introspect::panic_invalid_field_index(index),
                }
            }
            pub(crate) fn get_annotation_types(
                child_index: Option<u16>,
                index: u32,
            ) -> ::capnp::introspect::Type {
                ::capnp::introspect::panic_invalid_annotation_indices(child_index, index)
            }
            pub(crate) static ARENA: ::capnp::private::arena::GeneratedCodeArena =
                ::capnp::private::arena::GeneratedCodeArena::new(&ENCODED_NODE);
            pub(crate) static RAW_SCHEMA: ::capnp::introspect::RawStructSchema =
                ::capnp::introspect::RawStructSchema::new(
                    &ARENA,
                    NONUNION_MEMBERS,
                    MEMBERS_BY_DISCRIMINANT,
                    MEMBERS_BY_NAME,
                );
            pub(crate) static NONUNION_MEMBERS: &[u16] = &[0];
            pub(crate) static MEMBERS_BY_DISCRIMINANT: &[u16] = &[];
            pub(crate) static MEMBERS_BY_NAME: &[u16] = &[0];
            pub(crate) const TYPE_ID: u64 = 0xb303_9774_8592_7573;
        }
    }
}
