import { Rpc, RpcGroup } from "effect/unstable/rpc";
import { Schema } from "effect";

import * as Control from "./control";

const ControlRpc = <
	const Tag extends string,
	Payload extends import("effect").Schema.Top,
	Success extends import("effect").Schema.Top,
>(
	tag: Tag,
	payload: Payload,
	success: Success,
) =>
	Rpc.make(tag, {
		error: Control.ProtocolErrorDetail,
		payload,
		success,
	});

/**
 * Declares every correlated control-channel operation once. The existing
 * authenticated MessagePack WebSocket remains the carrier; this group owns the
 * request, success, and protocol-error relationship used by both peers.
 */
export const ControlRpcGroup = RpcGroup.make(
	ControlRpc("command", Control.CommandEnvelope, Control.CommandReceiptEnvelope),
	ControlRpc(
		"thread.create.request",
		Control.ThreadCreateEnvelope,
		Control.ThreadCreateResultEnvelope,
	),
	ControlRpc(
		"artisan.tool.registry.list.query",
		Control.ArtisanToolRegistryListQueryEnvelope,
		Control.ArtisanToolRegistryListQueryResultEnvelope,
	),
	ControlRpc(
		"artisan.tool.execute",
		Control.ArtisanToolExecuteEnvelope,
		Control.CommandReceiptEnvelope,
	),
	ControlRpc(
		"artisan.approval.resolve",
		Control.ArtisanApprovalResolveEnvelope,
		Control.CommandReceiptEnvelope,
	),
	ControlRpc(
		"artisan.tool.invocation.list.query",
		Control.ArtisanToolInvocationListQueryEnvelope,
		Control.ArtisanToolInvocationListQueryResultEnvelope,
	),
	ControlRpc(
		"artisan.approval.list.query",
		Control.ArtisanApprovalListQueryEnvelope,
		Control.ArtisanApprovalListQueryResultEnvelope,
	),
	ControlRpc("git.diff.query", Control.GitDiffQueryEnvelope, Control.GitDiffQueryResultEnvelope),
	ControlRpc(
		"git.workspace.query",
		Control.GitWorkspaceQueryEnvelope,
		Control.GitWorkspaceQueryResultEnvelope,
	),
	ControlRpc(
		"guidance.query",
		Control.GlobalGuidanceQueryEnvelope,
		Control.GlobalGuidanceQueryResultEnvelope,
	),
	ControlRpc(
		"model_behaviour.query",
		Control.ModelBehaviourQueryEnvelope,
		Control.ModelBehaviourQueryResultEnvelope,
	),
	ControlRpc(
		"marketplace.routine.list.query",
		Control.RoutineRegistryQueryEnvelope,
		Control.RoutineRegistryQueryResultEnvelope,
	),
	ControlRpc(
		"marketplace.routine.detail.query",
		Control.RoutineDetailQueryEnvelope,
		Control.RoutineDetailQueryResultEnvelope,
	),
	ControlRpc(
		"marketplace.routine.install.preview",
		Control.RoutineInstallPreviewEnvelope,
		Control.RoutineInstallPreviewResultEnvelope,
	),
	ControlRpc(
		"marketplace.routine.invoke",
		Control.RoutineInvokeEnvelope,
		Control.RoutineInvokeResultEnvelope,
	),
	ControlRpc(
		"marketplace.npx_skills.discover",
		Control.NpxSkillsDiscoverEnvelope,
		Control.NpxSkillsDiscoverResultEnvelope,
	),
	ControlRpc(
		"marketplace.capability.list.query",
		Control.CapabilityRegistryQueryEnvelope,
		Control.CapabilityRegistryQueryResultEnvelope,
	),
	ControlRpc(
		"marketplace.capability.detail.query",
		Control.CapabilityDetailQueryEnvelope,
		Control.CapabilityDetailQueryResultEnvelope,
	),
	ControlRpc(
		"marketplace.capability.connect.preview",
		Control.CapabilityConnectPreviewEnvelope,
		Control.CapabilityConnectPreviewResultEnvelope,
	),
	ControlRpc(
		"marketplace.capability.invoke.request",
		Control.CapabilityInvocationApprovalRequestEnvelope,
		Control.CapabilityInvokeResultEnvelope,
	),
	ControlRpc(
		"marketplace.capability.invoke.decision",
		Control.CapabilityInvocationApprovalDecisionEnvelope,
		Control.CapabilityInvokeResultEnvelope,
	),
	ControlRpc(
		"marketplace.capability.invoke",
		Control.CapabilityInvokeEnvelope,
		Control.CapabilityInvokeResultEnvelope,
	),
	ControlRpc(
		"marketplace.capability.oauth.begin",
		Control.CapabilityOAuthBeginEnvelope,
		Control.CapabilityOAuthBeginResultEnvelope,
	),
	ControlRpc(
		"marketplace.capability.oauth.status.query",
		Control.CapabilityOAuthTokenStatusEnvelope,
		Control.CapabilityOAuthTokenStatusResultEnvelope,
	),
	ControlRpc(
		"orchestration.graph.query",
		Control.OrchestrationGraphQueryEnvelope,
		Control.OrchestrationGraphQueryResultEnvelope,
	),
	ControlRpc(
		"orchestration.group.list.query",
		Control.OrchestrationGroupListQueryEnvelope,
		Control.OrchestrationGroupListQueryResultEnvelope,
	),
	ControlRpc(
		"conversation.query",
		Control.ConversationQueryEnvelope,
		Control.ConversationQueryResultEnvelope,
	),
	ControlRpc(
		"message.image_attachment.query",
		Control.MessageImageAttachmentQueryEnvelope,
		Control.MessageImageAttachmentQueryResultEnvelope,
	),
	ControlRpc(
		"preview.asset.metadata.query",
		Control.PreviewAssetMetadataQueryEnvelope,
		Control.PreviewAssetMetadataQueryResultEnvelope,
	),
	ControlRpc(
		"preview.browser.launch",
		Control.PreviewBrowserLaunchEnvelope,
		Control.PreviewBrowserLaunchResultEnvelope,
	),
	ControlRpc(
		"preview.inspection.close",
		Control.PreviewInspectionSessionCloseEnvelope,
		Control.PreviewInspectionSessionCloseResultEnvelope,
	),
	ControlRpc(
		"preview.inspection.inspect",
		Control.PreviewInspectionEnvelope,
		Control.PreviewInspectionResultEnvelope,
	),
	ControlRpc(
		"preview.inspection.open",
		Control.PreviewInspectionSessionOpenEnvelope,
		Control.PreviewInspectionSessionOpenResultEnvelope,
	),
	ControlRpc(
		"preview.rich_link.resolve.query",
		Control.RichLinkResolveQueryEnvelope,
		Control.RichLinkResolveQueryResultEnvelope,
	),
	ControlRpc(
		"preview.target.get.query",
		Control.PreviewTargetGetQueryEnvelope,
		Control.PreviewTargetGetQueryResultEnvelope,
	),
	ControlRpc(
		"preview.target.list.query",
		Control.PreviewTargetListQueryEnvelope,
		Control.PreviewTargetListQueryResultEnvelope,
	),
	ControlRpc(
		"project.directory.list.query",
		Control.ProjectDirectoryListQueryEnvelope,
		Control.ProjectDirectoryListQueryResultEnvelope,
	),
	ControlRpc(
		"project.directory.pick",
		Control.ProjectDirectoryPickEnvelope,
		Control.ProjectDirectoryPickResultEnvelope,
	),
	ControlRpc(
		"project.directory.select",
		Control.ProjectDirectorySelectEnvelope,
		Control.ProjectDirectorySelectResultEnvelope,
	),
	ControlRpc(
		"project.directory.create",
		Control.ProjectDirectoryCreateEnvelope,
		Control.ProjectDirectoryCreateResultEnvelope,
	),
	ControlRpc(
		"project.list.query",
		Control.ProjectListQueryEnvelope,
		Control.ProjectListQueryResultEnvelope,
	),
	ControlRpc(
		"project.detach",
		Control.ProjectDetachEnvelope,
		Control.ProjectDetachResultEnvelope,
	),
	ControlRpc(
		"runtime.catalog.query",
		Control.RuntimeCatalogQueryEnvelope,
		Control.RuntimeCatalogQueryResultEnvelope,
	),
	ControlRpc(
		"thread.session.query",
		Control.ThreadSessionQueryEnvelope,
		Control.ThreadSessionQueryResultEnvelope,
	),
	ControlRpc(
		"surface.list.query",
		Control.SurfaceListQueryEnvelope,
		Control.SurfaceListQueryResultEnvelope,
	),
	ControlRpc(
		"surface.usage.aggregate.query",
		Control.SurfaceUsageAggregateQueryEnvelope,
		Control.SurfaceUsageAggregateQueryResultEnvelope,
	),
	ControlRpc(
		"surface.usage.daily.query",
		Control.SurfaceUsageDailyQueryEnvelope,
		Control.SurfaceUsageDailyQueryResultEnvelope,
	),
	ControlRpc(
		"host.identity.query",
		Control.HostIdentityQueryEnvelope,
		Control.HostIdentityQueryResultEnvelope,
	),
	ControlRpc(
		"project.repository.query",
		Control.ProjectRepositoryQueryEnvelope,
		Control.ProjectRepositoryQueryResultEnvelope,
	),
	ControlRpc(
		"project.diff.query",
		Control.ProjectDiffQueryEnvelope,
		Control.ProjectDiffQueryResultEnvelope,
	),
	ControlRpc(
		"session.defaults.query",
		Control.SessionDefaultsQueryEnvelope,
		Control.SessionDefaultsQueryResultEnvelope,
	),
	ControlRpc(
		"engine.usage.query",
		Control.EngineUsageQueryEnvelope,
		Control.EngineUsageQueryResultEnvelope,
	),
	ControlRpc(
		"thread.usage.series.query",
		Control.ThreadUsageSeriesQueryEnvelope,
		Control.ThreadUsageSeriesQueryResultEnvelope,
	),
	ControlRpc(
		"terminal.list.query",
		Control.TerminalListQueryEnvelope,
		Control.TerminalListQueryResultEnvelope,
	),
	ControlRpc(
		"thread.list.query",
		Control.ThreadListQueryEnvelope,
		Control.ThreadListQueryResultEnvelope,
	),
	ControlRpc(
		"thread.transcript.query",
		Control.ThreadTranscriptQueryEnvelope,
		Control.ThreadTranscriptQueryResultEnvelope,
	),
	ControlRpc(
		"thread.retention.query",
		Control.ThreadRetentionQueryEnvelope,
		Control.ThreadRetentionQueryResultEnvelope,
	),
	ControlRpc(
		"model.favorites.query",
		Control.ModelFavoritesQueryEnvelope,
		Control.ModelFavoritesQueryResultEnvelope,
	),
	ControlRpc(
		"thread.work.query",
		Control.ThreadWorkQueryEnvelope,
		Control.ThreadWorkQueryResultEnvelope,
	),
	ControlRpc(
		"workspace.file.read.query",
		Control.WorkspaceFileReadQueryEnvelope,
		Control.WorkspaceFileReadQueryResultEnvelope,
	),
	ControlRpc(
		"workspace.file.discovery.query",
		Control.WorkspaceFileDiscoveryQueryEnvelope,
		Control.WorkspaceFileDiscoveryQueryResultEnvelope,
	),
	ControlRpc(
		"workspace.language.capabilities.query",
		Control.WorkspaceLanguageCapabilitiesQueryEnvelope,
		Control.WorkspaceLanguageCapabilitiesQueryResultEnvelope,
	),
	ControlRpc(
		"workspace.change.list.query",
		Control.WorkspaceChangeListQueryEnvelope,
		Control.WorkspaceChangeListQueryResultEnvelope,
	),
	ControlRpc(
		"workspace.conflict.list.query",
		Control.WorkspaceConflictListQueryEnvelope,
		Control.WorkspaceConflictListQueryResultEnvelope,
	),
	ControlRpc(
		"workspace.change.diff.query",
		Control.WorkspaceChangeDiffQueryEnvelope,
		Control.WorkspaceChangeDiffQueryResultEnvelope,
	),
	ControlRpc(
		"preview.target.register",
		Control.PreviewTargetRegisterEnvelope,
		Control.PreviewTargetMutationResultEnvelope,
	),
	ControlRpc(
		"preview.target.probe",
		Control.PreviewTargetProbeEnvelope,
		Control.PreviewTargetMutationResultEnvelope,
	),
	ControlRpc(
		"preview.target.state",
		Control.PreviewTargetStateEnvelope,
		Control.PreviewTargetMutationResultEnvelope,
	),
	ControlRpc(
		"preview.target.remove",
		Control.PreviewTargetRemoveEnvelope,
		Control.PreviewTargetMutationResultEnvelope,
	),
	ControlRpc(
		"git.index.stage.request",
		Control.GitIndexStageRequestEnvelope,
		Control.CommandReceiptEnvelope,
	),
	ControlRpc(
		"git.index.unstage.request",
		Control.GitIndexUnstageRequestEnvelope,
		Control.CommandReceiptEnvelope,
	),
	ControlRpc(
		"git.mutation.resolve",
		Control.GitMutationResolveEnvelope,
		Control.CommandReceiptEnvelope,
	),
	ControlRpc(
		"guidance.drift.resolve",
		Control.GlobalGuidanceDriftResolutionEnvelope,
		Control.CommandReceiptEnvelope,
	),
	ControlRpc(
		"guidance.selection",
		Control.GlobalGuidanceSelectionEnvelope,
		Control.CommandReceiptEnvelope,
	),
	ControlRpc(
		"guidance.sync.retry",
		Control.GlobalGuidanceRetryEnvelope,
		Control.CommandReceiptEnvelope,
	),
	ControlRpc(
		"guidance.update",
		Control.GlobalGuidanceUpdateEnvelope,
		Control.CommandReceiptEnvelope,
	),
	ControlRpc(
		"model_behaviour.drift.resolve",
		Control.ModelBehaviourDriftResolutionEnvelope,
		Control.CommandReceiptEnvelope,
	),
	ControlRpc(
		"model_behaviour.sync.retry",
		Control.ModelBehaviourRetryEnvelope,
		Control.CommandReceiptEnvelope,
	),
	ControlRpc(
		"model_behaviour.update",
		Control.ModelBehaviourUpdateEnvelope,
		Control.CommandReceiptEnvelope,
	),
	ControlRpc(
		"thread.retention.update",
		Control.ThreadRetentionUpdateEnvelope,
		Control.CommandReceiptEnvelope,
	),
	ControlRpc(
		"session.defaults.update",
		Control.SessionDefaultsUpdateEnvelope,
		Control.CommandReceiptEnvelope,
	),
	ControlRpc(
		"model.favorite.update",
		Control.ModelFavoriteUpdateEnvelope,
		Control.CommandReceiptEnvelope,
	),
	ControlRpc(
		"workspace.file.replace",
		Control.WorkspaceFileReplaceEnvelope,
		Control.CommandReceiptEnvelope,
	),
	ControlRpc(
		"workspace.change.review",
		Control.WorkspaceChangeReviewEnvelope,
		Control.CommandReceiptEnvelope,
	),
	ControlRpc(
		"workspace.change.rollback",
		Control.WorkspaceChangeRollbackEnvelope,
		Control.CommandReceiptEnvelope,
	),
	ControlRpc(
		"marketplace.routine.install.request",
		Control.RoutineInstallRequestEnvelope,
		Control.CommandReceiptEnvelope,
	),
	ControlRpc(
		"marketplace.routine.install.decision",
		Control.RoutineApprovalDecisionEnvelope,
		Control.CommandReceiptEnvelope,
	),
	ControlRpc(
		"marketplace.routine.enable",
		Control.RoutineEnableEnvelope,
		Control.CommandReceiptEnvelope,
	),
	ControlRpc(
		"marketplace.routine.disable",
		Control.RoutineDisableEnvelope,
		Control.CommandReceiptEnvelope,
	),
	ControlRpc(
		"marketplace.routine.remove",
		Control.RoutineRemoveEnvelope,
		Control.CommandReceiptEnvelope,
	),
	ControlRpc(
		"marketplace.routine.sync",
		Control.RoutineSyncEnvelope,
		Control.CommandReceiptEnvelope,
	),
	ControlRpc(
		"marketplace.routine.drift.resolve",
		Control.RoutineDriftResolutionEnvelope,
		Control.CommandReceiptEnvelope,
	),
	ControlRpc(
		"marketplace.routine.drift.overwrite.request",
		Control.RoutineDriftOverwriteRequestEnvelope,
		Control.CommandReceiptEnvelope,
	),
	ControlRpc(
		"marketplace.routine.drift.overwrite.decision",
		Control.RoutineDriftOverwriteDecisionEnvelope,
		Control.CommandReceiptEnvelope,
	),
	ControlRpc(
		"marketplace.routine.rollback",
		Control.RoutineRollbackEnvelope,
		Control.CommandReceiptEnvelope,
	),
	ControlRpc(
		"marketplace.npx_skills.import.request",
		Control.NpxSkillsImportEnvelope,
		Control.CommandReceiptEnvelope,
	),
	ControlRpc(
		"marketplace.capability.connect.request",
		Control.CapabilityConnectRequestEnvelope,
		Control.CommandReceiptEnvelope,
	),
	ControlRpc(
		"marketplace.capability.connect.decision",
		Control.CapabilityApprovalDecisionEnvelope,
		Control.CommandReceiptEnvelope,
	),
	ControlRpc(
		"marketplace.capability.start",
		Control.CapabilityStartEnvelope,
		Control.CommandReceiptEnvelope,
	),
	ControlRpc(
		"marketplace.capability.reconnect",
		Control.CapabilityReconnectEnvelope,
		Control.CommandReceiptEnvelope,
	),
	ControlRpc(
		"marketplace.capability.health",
		Control.CapabilityHealthEnvelope,
		Control.CommandReceiptEnvelope,
	),
	ControlRpc(
		"marketplace.capability.disconnect",
		Control.CapabilityDisconnectEnvelope,
		Control.CommandReceiptEnvelope,
	),
	ControlRpc(
		"marketplace.capability.restart",
		Control.CapabilityRestartEnvelope,
		Control.CommandReceiptEnvelope,
	),
	ControlRpc(
		"marketplace.capability.uninstall",
		Control.CapabilityUninstallEnvelope,
		Control.CommandReceiptEnvelope,
	),
	ControlRpc(
		"marketplace.capability.enable",
		Control.CapabilityEnableEnvelope,
		Control.CommandReceiptEnvelope,
	),
	ControlRpc(
		"marketplace.capability.disable",
		Control.CapabilityDisableEnvelope,
		Control.CommandReceiptEnvelope,
	),
	ControlRpc(
		"marketplace.capability.remove",
		Control.CapabilityRemoveEnvelope,
		Control.CommandReceiptEnvelope,
	),
	ControlRpc(
		"marketplace.capability.sync",
		Control.CapabilitySyncEnvelope,
		Control.CommandReceiptEnvelope,
	),
	ControlRpc(
		"marketplace.capability.drift.resolve",
		Control.CapabilityDriftResolutionEnvelope,
		Control.CommandReceiptEnvelope,
	),
	ControlRpc(
		"marketplace.capability.drift.overwrite.request",
		Control.CapabilityDriftOverwriteRequestEnvelope,
		Control.CommandReceiptEnvelope,
	),
	ControlRpc(
		"marketplace.capability.drift.overwrite.decision",
		Control.CapabilityDriftOverwriteDecisionEnvelope,
		Control.CommandReceiptEnvelope,
	),
	ControlRpc(
		"marketplace.capability.oauth.complete",
		Control.CapabilityOAuthCompleteEnvelope,
		Control.CommandReceiptEnvelope,
	),
	ControlRpc(
		"marketplace.capability.oauth.refresh",
		Control.CapabilityOAuthRefreshEnvelope,
		Control.CommandReceiptEnvelope,
	),
	ControlRpc(
		"marketplace.capability.oauth.revoke",
		Control.CapabilityOAuthRevokeEnvelope,
		Control.CommandReceiptEnvelope,
	),
);

export type ControlRpc = RpcGroup.Rpcs<typeof ControlRpcGroup>;
export type ControlRpcRequest = import("effect/unstable/rpc").Rpc.Payload<ControlRpc>;
export type ControlRpcSuccess = import("effect/unstable/rpc").Rpc.Success<ControlRpc>;
export type ControlRpcSuccessFor<Request extends ControlRpcRequest> =
	import("effect/unstable/rpc").Rpc.Success<
		Extract<ControlRpc, { readonly _tag: Request["kind"] }>
	>;

/** Resolves the canonical procedure for an already schema-decoded request. */
export const GetControlRpc = (tag: ControlRpc["_tag"]) => {
	const rpc = ControlRpcGroup.requests.get(tag);
	if (rpc === undefined) {
		throw new Error(`Missing canonical control RPC for ${tag}`);
	}
	return rpc;
};

const control_rpc_success_schemas = Array.from(
	ControlRpcGroup.requests.values(),
	(rpc) => rpc.successSchema,
);

/** Identifies correlated successes without duplicating their wire kinds. */
export const IsControlRpcSuccess = (
	envelope: Control.OutboundControlEnvelope,
): envelope is ControlRpcSuccess =>
	control_rpc_success_schemas.some((schema) => Schema.is(schema)(envelope));
