//! Application protocol schemas, generated bindings, and owned conversions.

pub use artisan_domain::WorkspaceId;

/// Phase 1 feasibility fixture.
///
/// Bindings generated by `//modules/protocol:phase1_proof_codegen` from
/// `schema/phase1_proof.capnp`. This module encodes no product API decisions;
/// the Phase 2 protocol design replaces or removes it. Lint allowances are
/// scoped to this module because its contents are machine-generated.
#[allow(clippy::all)]
#[allow(clippy::pedantic)]
pub mod phase1_proof_capnp;

/// Product application protocol (Phase 2).
///
/// Bindings generated by `//modules/protocol:artisan_protocol_codegen` from
/// `schema/artisan.capnp`; the schema header documents version negotiation,
/// correlation, ordinal-stability, and bound policies. Machine-generated
/// contents stay behind scoped lint allowances. Application code uses the
/// owned values and total conversion functions exported below; direct binding
/// access remains available for schema conformance and malformed-input tests.
#[allow(clippy::all)]
#[allow(clippy::pedantic)]
pub mod artisan_capnp;

mod codec;
mod types;

pub use codec::{
    CAPNP_NESTING_LIMIT, CAPNP_TRAVERSAL_LIMIT_WORDS, ProtocolDecodeError, ProtocolEncodeError,
    decode_envelope, encode_envelope,
};
pub use types::{
    APPLICATION_PROTOCOL_VERSION, ClientRequest, ConnectionId, ConversationSubscriptionStarted,
    ConversationSubscriptionStopped, DispatchFailure, ERROR_DETAIL_MAX_BYTES, ErrorCode,
    ErrorDetail, EventCursor, FirstMessageReceipt, FrameId, HELLO_VERSION_MAX_ENTRIES, Hello,
    HelloCredential, LOCAL_CAPABILITY_BYTES, LocalCapability, LocalCapabilityError,
    ProtocolFailure, ProtocolValueError, ProtocolVersion, RECONNECT_CAPABILITY_BYTES,
    ReconnectCapability, ReconnectCapabilityError, ResponsePayload, ServerEvent, ServerResponse,
    VersionOffer, VersionOfferError, Welcome, WireEnvelope, WireEnvelopeBody,
};
