//! Application protocol schemas, generated bindings, and owned conversions.

pub use artisan_domain::WorkspaceId;

/// Phase 1 feasibility fixture.
///
/// Bindings generated by `nix run .#codegen` from
/// `schema/phase1_proof.capnp`. This module encodes no product API decisions;
/// the Phase 2 protocol design replaces or removes it. Lint allowances are
/// scoped to this module because its contents are machine-generated.
/// Regenerate the checked-in bindings with `nix run .#codegen`.
/// `#[rustfmt::skip]` excludes generated bindings from formatting.
#[allow(clippy::all)]
#[allow(clippy::pedantic)]
#[rustfmt::skip]
pub mod phase1_proof_capnp;

/// Product application protocol (Phase 2).
///
/// Bindings generated by `nix run .#codegen` from
/// `schema/artisan.capnp`; the schema header documents version negotiation,
/// correlation, ordinal-stability, and bound policies. Machine-generated
/// contents stay behind scoped lint allowances. Application code uses the
/// owned values and total conversion functions exported below; direct binding
/// access remains available for schema conformance and malformed-input tests.
/// Regenerate the checked-in bindings with `nix run .#codegen`.
/// `#[rustfmt::skip]` excludes generated bindings from formatting.
#[allow(clippy::all)]
#[allow(clippy::pedantic)]
#[rustfmt::skip]
pub mod artisan_capnp;

/// Dependency-free classification and presentation for conversation activity rows.
pub mod conversation_activity;

/// Owned project-repository facts for the native protocol.
pub mod repository;

mod codec;
mod types;

pub use codec::{
    CAPNP_NESTING_LIMIT, CAPNP_TRAVERSAL_LIMIT_WORDS, ProtocolDecodeError, ProtocolEncodeError,
    decode_envelope, encode_envelope,
};
pub use repository::{
    PROJECT_REPOSITORY_MAXIMUM_PROJECTS, ProjectRepository, ProjectRepositoryEntry,
    ProjectRepositoryQuery, ProjectRepositoryQueryResult, REPOSITORY_REMOTE_MAXIMUM,
    REPOSITORY_TEXT_MAX_BYTES, RepositoryBranchState, RepositoryHost, RepositoryRemote,
    RepositorySnapshot,
};
pub use types::{
    APPLICATION_PROTOCOL_VERSION, ActiveRunResult, CATALOG_SNAPSHOT_MAX_BYTES, CatalogSnapshotWire,
    CatalogSnapshotWireError, ClientRequest, ComposerCatalogResult, ConnectionId,
    ConversationSubscriptionStarted, ConversationSubscriptionStopped, DirectoryPickOutcome,
    DispatchFailure, ERROR_DETAIL_MAX_BYTES, ErrorCode, ErrorDetail, EventCursor,
    FirstMessageReceipt, FrameId, HELLO_VERSION_MAX_ENTRIES, Hello, HelloCredential,
    LOCAL_CAPABILITY_BYTES, LifecycleRequest, LifecycleResponse, LifecycleState, LifecycleStatus,
    LifecycleStopDisposition, LifecycleStopReceipt, LocalCapability, LocalCapabilityError,
    MessageImageResult, ModelFavoritesSnapshot, ProtocolFailure, ProtocolValueError,
    ProtocolVersion, QueueMessageReceipt, RECONNECT_CAPABILITY_BYTES,
    RICH_LINK_PAGE_NAME_MAX_BYTES, RICH_LINK_URL_MAX_BYTES, ReconnectCapability,
    ReconnectCapabilityError, RegisteredEngineProfilesResult, ResolveRichLinkRequest,
    RespondApprovalReceipt, RespondQuestionReceipt, ResponsePayload, RichLinkPageMetadata,
    RunInteractionOutcome, RunLiveStatus, ServerEvent, ServerResponse, SetModelFavoriteReceipt,
    SetThreadEngineConfigResult, StopRunDisposition, StopRunReceipt, ThreadEngineSettingsResult,
    VersionOffer, VersionOfferError, Welcome, WireEnvelope, WireEnvelopeBody,
};

#[allow(clippy::all)]
#[allow(clippy::pedantic)]
#[rustfmt::skip]
pub mod composer_state_capnp;
pub mod composer_state;
#[path = "codec/composer_state.rs"]
pub(crate) mod composer_state_codec;
