//! Application protocol schemas, generated bindings, and owned conversions.

pub use artisan_domain::WorkspaceId;

/// Phase 1 feasibility fixture.
///
/// Bindings generated by `//modules/protocol:phase1_proof_codegen` from
/// `schema/phase1_proof.capnp`. This module encodes no product API decisions;
/// the Phase 2 protocol design replaces or removes it. Lint allowances are
/// scoped to this module because its contents are machine-generated.
#[allow(clippy::all)]
#[allow(clippy::pedantic)]
pub mod phase1_proof_capnp;
