//! Phase 1 feasibility fixture.
//!
//! Proves that a real Cap'n Proto type generated by Bazel-owned codegen
//! (`//modules/protocol:phase1_proof_codegen`) can be serialized and
//! deserialized from an external integration test using the normal Rust test
//! harness. Encodes no product API decisions.

use capnp::message::{HeapAllocator, ReaderOptions};
use capnp::serialize;

use artisan_protocol::phase1_proof_capnp::phase1_proof_envelope;

const CORRELATION_ID: u64 = 0x0123_4567_89ab_cdef;
const PAYLOAD: &str = "phase-one-capnp-proof";
const ATTEMPT_NUMBERS: [u32; 3] = [7, 13, 42];

fn build_proof_message() -> capnp::message::Builder<HeapAllocator> {
    let mut message = capnp::message::Builder::new(HeapAllocator::new());
    {
        let mut envelope = message.init_root::<phase1_proof_envelope::Builder>();
        envelope.set_correlation_id(CORRELATION_ID);
        envelope.set_payload(PAYLOAD);
        let attempt_count = u32::try_from(ATTEMPT_NUMBERS.len()).expect("fixture length fits u32");
        let mut attempts = envelope.init_attempt_numbers(attempt_count);
        for (index, value) in ATTEMPT_NUMBERS.iter().enumerate() {
            let index = u32::try_from(index).expect("fixture index fits u32");
            attempts.set(index, *value);
        }
    }
    message
}

#[test]
fn round_trips_phase1_proof_envelope() -> capnp::Result<()> {
    let message = build_proof_message();

    let bytes = serialize::write_message_to_words(&message);
    let mut encoded = bytes.as_slice();
    let decoded = serialize::read_message_from_flat_slice(&mut encoded, ReaderOptions::new())?;
    let envelope: phase1_proof_envelope::Reader = decoded.get_root()?;

    assert_eq!(envelope.get_correlation_id(), CORRELATION_ID);
    assert_eq!(envelope.get_payload()?, PAYLOAD);

    let attempts = envelope.get_attempt_numbers()?;
    let received: Vec<u32> = attempts.iter().collect();
    assert_eq!(received, ATTEMPT_NUMBERS.to_vec());

    Ok(())
}

#[test]
fn serializes_identical_messages_to_identical_bytes() {
    let first = serialize::write_message_to_words(&build_proof_message());
    let second = serialize::write_message_to_words(&build_proof_message());

    // Deterministic framing keeps Bazel-side caching and wire comparisons sane.
    assert!(!first.is_empty());
    assert_eq!(first, second);
}
