import type { ModelDefinition } from "../schema";
import {
	anthropic_context_window,
	anthropic_fast_speed,
	anthropic_standard_speed,
	exceptional,
	standard,
	unavailable,
} from "./options";

export const anthropic_models = [
	{
		id: "claude-fable",
		name: "Claude Fable 5",
		native_model_id: "claude-fable-5",
		description: "Most capable for your hardest and longest-running tasks.",
		harness: "claude",
		provider: "anthropic",
		routing: { kind: "default" },
		status: "prototype",
		capabilities: {
			thinking: {
				availability: "supported",
				default: "high",
				options: [
					standard("light", "low"),
					standard("medium", "medium"),
					standard("high", "high"),
					standard("xhigh", "xhigh"),
					exceptional("max", "max"),
				],
			},
			context_window: anthropic_context_window,
			speed_options: [anthropic_standard_speed("Claude Fable 5", false)],
			image_input: true,
			local_tools: true,
			mcp: true,
			web_search: true,
		},
	},
	{
		id: "claude-opus",
		name: "Claude Opus 5",
		native_model_id: "claude-opus-5",
		description: "Best for everyday, complex tasks.",
		harness: "claude",
		provider: "anthropic",
		routing: { kind: "default" },
		status: "prototype",
		capabilities: {
			thinking: {
				availability: "supported",
				default: "high",
				options: [
					standard("light", "low"),
					standard("medium", "medium"),
					standard("high", "high"),
					standard("xhigh", "xhigh"),
					exceptional("max", "max"),
				],
			},
			context_window: anthropic_context_window,
			speed_options: [
				anthropic_standard_speed("Claude Opus 5", true),
				anthropic_fast_speed("Claude Opus 5"),
			],
			image_input: true,
			local_tools: true,
			mcp: true,
			web_search: true,
		},
	},
	{
		id: "claude-sonnet",
		name: "Claude Sonnet 5",
		native_model_id: "claude-sonnet-5",
		description: "Efficient for routine tasks; recommended for most coding.",
		harness: "claude",
		provider: "anthropic",
		routing: { kind: "default" },
		status: "prototype",
		capabilities: {
			thinking: {
				availability: "supported",
				default: "high",
				options: [
					standard("light", "low"),
					standard("medium", "medium"),
					standard("high", "high"),
					standard("xhigh", "xhigh"),
					exceptional("max", "max"),
				],
			},
			context_window: anthropic_context_window,
			speed_options: [anthropic_standard_speed("Claude Sonnet 5", false)],
			image_input: true,
			local_tools: true,
			mcp: true,
			web_search: true,
		},
	},
	{
		id: "claude-haiku",
		name: "Claude Haiku 4.5",
		native_model_id: "claude-haiku-4-5",
		description: "Fastest for quick answers at lower cost.",
		harness: "claude",
		provider: "anthropic",
		routing: { kind: "default" },
		status: "prototype",
		capabilities: {
			thinking: unavailable,
			speed_options: [anthropic_standard_speed("Claude Haiku 4.5", false)],
			image_input: true,
			local_tools: true,
			mcp: true,
			web_search: true,
		},
	},
] satisfies ReadonlyArray<ModelDefinition>;
