import type { ModelDefinition } from "../schema";
import { cursor_native_speed, standard } from "./options";

export const cursor_openai_models = [
	{
		id: "cursor-gpt-5-6-sol",
		name: "GPT 5.6 Sol",
		native_model_id: "gpt-5.6-sol",
		description: "OpenAI's frontier agentic coding model.",
		harness: "cursor",
		provider: "openai",
		routing: { kind: "default" },
		status: "prototype",
		capabilities: {
			thinking: {
				availability: "supported",
				default: "high",
				options: [
					standard("light", "low"),
					standard("medium", "medium"),
					standard("high", "high"),
					standard("xhigh", "xhigh"),
				],
			},
			speed_options: [cursor_native_speed("GPT 5.6 Sol", true)],
			image_input: false,
			local_tools: true,
			mcp: true,
			web_search: false,
		},
	},
	{
		id: "cursor-gpt-5-6-terra",
		name: "GPT 5.6 Terra",
		native_model_id: "gpt-5.6-terra",
		description: "Balanced agentic coding model for everyday work.",
		harness: "cursor",
		provider: "openai",
		routing: { kind: "default" },
		status: "prototype",
		capabilities: {
			thinking: {
				availability: "supported",
				default: "high",
				options: [
					standard("light", "low"),
					standard("medium", "medium"),
					standard("high", "high"),
					standard("xhigh", "xhigh"),
				],
			},
			speed_options: [cursor_native_speed("GPT 5.6 Terra", true)],
			image_input: false,
			local_tools: true,
			mcp: true,
			web_search: false,
		},
	},
	{
		id: "cursor-gpt-5-6-luna",
		name: "GPT 5.6 Luna",
		native_model_id: "gpt-5.6-luna",
		description: "Fast and affordable agentic coding model.",
		harness: "cursor",
		provider: "openai",
		routing: { kind: "default" },
		status: "prototype",
		capabilities: {
			thinking: {
				availability: "supported",
				default: "medium",
				options: [
					standard("light", "low"),
					standard("medium", "medium"),
					standard("high", "high"),
					standard("xhigh", "xhigh"),
				],
			},
			speed_options: [cursor_native_speed("GPT 5.6 Luna", true)],
			image_input: false,
			local_tools: true,
			mcp: true,
			web_search: false,
		},
	},
	{
		id: "cursor-gpt-5-5",
		name: "GPT 5.5",
		native_model_id: "gpt-5.5",
		description: "Strong all-round model for complex coding, research, and real-world work.",
		harness: "cursor",
		provider: "openai",
		routing: { kind: "default" },
		status: "prototype",
		capabilities: {
			thinking: {
				availability: "supported",
				default: "high",
				options: [
					standard("light", "low"),
					standard("medium", "medium"),
					standard("high", "high"),
					standard("xhigh", "xhigh"),
				],
			},
			speed_options: [cursor_native_speed("GPT 5.5", true)],
			image_input: false,
			local_tools: true,
			mcp: true,
			web_search: false,
		},
	},
	{
		id: "cursor-gpt-5-4",
		name: "GPT 5.4",
		native_model_id: "gpt-5.4",
		description: "Strong model for everyday coding.",
		harness: "cursor",
		provider: "openai",
		routing: { kind: "default" },
		status: "prototype",
		capabilities: {
			thinking: {
				availability: "supported",
				default: "high",
				options: [
					standard("light", "low"),
					standard("medium", "medium"),
					standard("high", "high"),
					standard("xhigh", "xhigh"),
				],
			},
			speed_options: [cursor_native_speed("GPT 5.4", true)],
			image_input: false,
			local_tools: true,
			mcp: true,
			web_search: false,
		},
	},
	{
		id: "cursor-gpt-5-4-mini",
		name: "GPT 5.4 Mini",
		native_model_id: "gpt-5.4-mini",
		description: "Small, fast, and cost-efficient model for simpler coding tasks.",
		harness: "cursor",
		provider: "openai",
		routing: { kind: "default" },
		status: "prototype",
		capabilities: {
			thinking: {
				availability: "supported",
				default: "medium",
				options: [
					standard("light", "low"),
					standard("medium", "medium"),
					standard("high", "high"),
					standard("xhigh", "xhigh"),
				],
			},
			speed_options: [cursor_native_speed("GPT 5.4 Mini", false)],
			image_input: false,
			local_tools: true,
			mcp: true,
			web_search: false,
		},
	},
	{
		id: "cursor-gpt-5-3-codex",
		name: "GPT 5.3 Codex",
		native_model_id: "gpt-5.3-codex",
		description: "Previous-generation agentic coding model.",
		harness: "cursor",
		provider: "openai",
		routing: { kind: "default" },
		status: "prototype",
		capabilities: {
			thinking: {
				availability: "supported",
				default: "medium",
				options: [
					standard("light", "low"),
					standard("medium", "medium"),
					standard("high", "high"),
					standard("xhigh", "xhigh"),
				],
			},
			speed_options: [cursor_native_speed("GPT 5.3 Codex", false)],
			image_input: false,
			local_tools: true,
			mcp: true,
			web_search: false,
		},
	},
] satisfies ReadonlyArray<ModelDefinition>;
