import type { ModelDefinition } from "../schema";
import { cursor_native_speed, exceptional, standard, unavailable } from "./options";

export const cursor_anthropic_models = [
	{
		id: "cursor-claude-fable-5",
		name: "Claude Fable 5",
		native_model_id: "claude-fable-5",
		description: "Most capable for your hardest and longest-running tasks.",
		harness: "cursor",
		provider: "anthropic",
		routing: { kind: "default" },
		status: "prototype",
		capabilities: {
			thinking: {
				availability: "supported",
				default: "high",
				options: [
					standard("light", "low"),
					standard("medium", "medium"),
					standard("high", "high"),
					standard("xhigh", "xhigh"),
					exceptional("max", "max"),
				],
			},
			speed_options: [cursor_native_speed("Claude Fable 5", false)],
			image_input: false,
			local_tools: true,
			mcp: true,
			web_search: false,
		},
	},
	{
		id: "cursor-claude-opus-5",
		name: "Claude Opus 5",
		native_model_id: "claude-opus-5",
		description: "Best for everyday, complex tasks.",
		harness: "cursor",
		provider: "anthropic",
		routing: { kind: "default" },
		status: "prototype",
		capabilities: {
			thinking: {
				availability: "supported",
				default: "high",
				options: [
					standard("light", "low"),
					standard("medium", "medium"),
					standard("high", "high"),
					standard("xhigh", "xhigh"),
					exceptional("max", "max"),
				],
			},
			speed_options: [cursor_native_speed("Claude Opus 5", true)],
			image_input: false,
			local_tools: true,
			mcp: true,
			web_search: false,
		},
	},
	{
		id: "cursor-claude-sonnet-5",
		name: "Claude Sonnet 5",
		native_model_id: "claude-sonnet-5",
		description: "Efficient for routine tasks; recommended for most coding.",
		harness: "cursor",
		provider: "anthropic",
		routing: { kind: "default" },
		status: "prototype",
		capabilities: {
			thinking: {
				availability: "supported",
				default: "high",
				options: [
					standard("light", "low"),
					standard("medium", "medium"),
					standard("high", "high"),
					standard("xhigh", "xhigh"),
					exceptional("max", "max"),
				],
			},
			speed_options: [cursor_native_speed("Claude Sonnet 5", false)],
			image_input: false,
			local_tools: true,
			mcp: true,
			web_search: false,
		},
	},
	{
		id: "cursor-claude-haiku-4-5",
		name: "Claude Haiku 4.5",
		native_model_id: "claude-haiku-4-5",
		description: "Fastest for quick answers at lower cost.",
		harness: "cursor",
		provider: "anthropic",
		routing: { kind: "default" },
		status: "prototype",
		capabilities: {
			thinking: unavailable,
			speed_options: [cursor_native_speed("Claude Haiku 4.5", false)],
			image_input: false,
			local_tools: true,
			mcp: true,
			web_search: false,
		},
	},
] satisfies ReadonlyArray<ModelDefinition>;
