import type { ModelDefinition } from "../schema";
import {
	exceptional,
	harness_orchestration,
	openai_fast_speed,
	openai_standard_speed,
	standard,
} from "./options";

export const openai_models = [
	{
		id: "codex-sol",
		name: "GPT 5.6 Sol",
		native_model_id: "gpt-5.6-sol",
		description: "OpenAI's frontier agentic coding model.",
		harness: "codex",
		provider: "openai",
		routing: { kind: "default" },
		status: "prototype",
		capabilities: {
			thinking: {
				availability: "supported",
				default: "high",
				options: [
					standard("light", "low"),
					standard("medium", "medium"),
					standard("high", "high"),
					standard("xhigh", "xhigh"),
					exceptional("max", "max"),
					harness_orchestration("ultra", "ultra"),
				],
			},
			speed_options: [
				openai_standard_speed("GPT 5.6 Sol", true),
				openai_fast_speed("GPT 5.6 Sol", 2.5),
			],
			image_input: true,
			local_tools: true,
			mcp: true,
			web_search: true,
		},
	},
	{
		id: "codex-terra",
		name: "GPT 5.6 Terra",
		native_model_id: "gpt-5.6-terra",
		description: "Balanced agentic coding model for everyday work.",
		harness: "codex",
		provider: "openai",
		routing: { kind: "default" },
		status: "prototype",
		capabilities: {
			thinking: {
				availability: "supported",
				default: "high",
				options: [
					standard("light", "low"),
					standard("medium", "medium"),
					standard("high", "high"),
					standard("xhigh", "xhigh"),
					exceptional("max", "max"),
					harness_orchestration("ultra", "ultra"),
				],
			},
			speed_options: [
				openai_standard_speed("GPT 5.6 Terra", true),
				openai_fast_speed("GPT 5.6 Terra", 2.5),
			],
			image_input: true,
			local_tools: true,
			mcp: true,
			web_search: true,
		},
	},
	{
		id: "codex-luna",
		name: "GPT 5.6 Luna",
		native_model_id: "gpt-5.6-luna",
		description: "Fast and affordable agentic coding model.",
		harness: "codex",
		provider: "openai",
		routing: { kind: "default" },
		status: "prototype",
		capabilities: {
			thinking: {
				availability: "supported",
				default: "medium",
				options: [
					standard("light", "low"),
					standard("medium", "medium"),
					standard("high", "high"),
					standard("xhigh", "xhigh"),
					exceptional("max", "max"),
					harness_orchestration("ultra", "ultra"),
				],
			},
			speed_options: [
				openai_standard_speed("GPT 5.6 Luna", true),
				openai_fast_speed("GPT 5.6 Luna", 2.5),
			],
			image_input: true,
			local_tools: true,
			mcp: true,
			web_search: true,
		},
	},
	{
		id: "codex-gpt-5-5",
		name: "GPT 5.5",
		native_model_id: "gpt-5.5",
		description: "Strong all-round model for complex coding, research, and real-world work.",
		harness: "codex",
		provider: "openai",
		routing: { kind: "default" },
		status: "prototype",
		capabilities: {
			thinking: {
				availability: "supported",
				default: "high",
				options: [
					standard("light", "low"),
					standard("medium", "medium"),
					standard("high", "high"),
					standard("xhigh", "xhigh"),
				],
			},
			speed_options: [
				openai_standard_speed("GPT 5.5", true),
				openai_fast_speed("GPT 5.5", 2.5),
			],
			image_input: true,
			local_tools: true,
			mcp: true,
			web_search: true,
		},
	},
	{
		id: "codex-gpt-5-4",
		name: "GPT 5.4",
		native_model_id: "gpt-5.4",
		description: "Strong model for everyday coding.",
		harness: "codex",
		provider: "openai",
		routing: { kind: "default" },
		status: "prototype",
		capabilities: {
			thinking: {
				availability: "supported",
				default: "high",
				options: [
					standard("light", "low"),
					standard("medium", "medium"),
					standard("high", "high"),
					standard("xhigh", "xhigh"),
				],
			},
			speed_options: [
				openai_standard_speed("GPT 5.4", true),
				openai_fast_speed("GPT 5.4", 2),
			],
			image_input: true,
			local_tools: true,
			mcp: true,
			web_search: true,
		},
	},
	{
		id: "codex-gpt-5-4-mini",
		name: "GPT 5.4 Mini",
		native_model_id: "gpt-5.4-mini",
		description: "Small, fast, and cost-efficient model for simpler coding tasks.",
		harness: "codex",
		provider: "openai",
		routing: { kind: "default" },
		status: "prototype",
		capabilities: {
			thinking: {
				availability: "supported",
				default: "medium",
				options: [
					standard("light", "low"),
					standard("medium", "medium"),
					standard("high", "high"),
					standard("xhigh", "xhigh"),
				],
			},
			speed_options: [openai_standard_speed("GPT 5.4 Mini", false)],
			image_input: true,
			local_tools: true,
			mcp: true,
			web_search: true,
		},
	},
	{
		id: "codex-spark",
		name: "GPT 5.3 Codex Spark",
		native_model_id: "gpt-5.3-codex-spark",
		description: "Ultra-fast coding model.",
		harness: "codex",
		provider: "openai",
		routing: { kind: "default" },
		status: "prototype",
		capabilities: {
			thinking: {
				availability: "supported",
				default: "medium",
				options: [
					standard("light", "low"),
					standard("medium", "medium"),
					standard("high", "high"),
					standard("xhigh", "xhigh"),
				],
			},
			speed_options: [openai_standard_speed("GPT 5.3 Codex Spark", false)],
			image_input: false,
			local_tools: true,
			mcp: true,
			web_search: true,
		},
	},
] satisfies ReadonlyArray<ModelDefinition>;
