import type { ModelDefinition } from "../schema";
import {
	exceptional,
	harness_orchestration,
	openai_context_window,
	openai_fast_speed,
	openai_standard_speed,
	standard,
} from "./options";

export const openai_models = [
	{
		id: "codex-astra",
		name: "GPT 6 Astra",
		native_model_id: "gpt-6-astra",
		description: "OpenAI's most capable model for complex, demanding work.",
		harness: "codex",
		provider: "openai",
		routing: { kind: "default" },
		status: "prototype",
		capabilities: {
			thinking: {
				availability: "supported",
				default: "medium",
				options: [
					standard("light", "low"),
					standard("medium", "medium"),
					standard("high", "high"),
					standard("xhigh", "xhigh"),
					exceptional("max", "max"),
					harness_orchestration("ultra", "ultra"),
				],
			},
			speed_options: [
				openai_standard_speed("GPT 6 Astra", true),
				openai_fast_speed("GPT 6 Astra", 2.5),
			],
			context_window: openai_context_window,
			image_input: true,
			local_tools: true,
			mcp: true,
			web_search: true,
		},
	},
	{
		id: "codex-sol",
		name: "GPT 5.6 Sol",
		native_model_id: "gpt-5.6-sol",
		description: "Reliable agentic workhorse for everyday tasks.",
		harness: "codex",
		provider: "openai",
		routing: { kind: "default" },
		status: "prototype",
		capabilities: {
			thinking: {
				availability: "supported",
				default: "light",
				options: [
					standard("light", "low"),
					standard("medium", "medium"),
					standard("high", "high"),
					standard("xhigh", "xhigh"),
					exceptional("max", "max"),
					harness_orchestration("ultra", "ultra"),
				],
			},
			speed_options: [
				openai_standard_speed("GPT 5.6 Sol", true),
				openai_fast_speed("GPT 5.6 Sol", 2.5),
			],
			context_window: openai_context_window,
			image_input: true,
			local_tools: true,
			mcp: true,
			web_search: true,
		},
	},
	{
		id: "codex-terra",
		name: "GPT 5.6 Terra",
		native_model_id: "gpt-5.6-terra",
		description: "Balanced agentic coding model for everyday work.",
		harness: "codex",
		provider: "openai",
		routing: { kind: "default" },
		status: "prototype",
		capabilities: {
			thinking: {
				availability: "supported",
				default: "medium",
				options: [
					standard("light", "low"),
					standard("medium", "medium"),
					standard("high", "high"),
					standard("xhigh", "xhigh"),
					exceptional("max", "max"),
					harness_orchestration("ultra", "ultra"),
				],
			},
			speed_options: [
				openai_standard_speed("GPT 5.6 Terra", true),
				openai_fast_speed("GPT 5.6 Terra", 2.5),
			],
			context_window: openai_context_window,
			image_input: true,
			local_tools: true,
			mcp: true,
			web_search: true,
		},
	},
	{
		id: "codex-luna",
		name: "GPT 5.6 Luna",
		native_model_id: "gpt-5.6-luna",
		description: "Fast and affordable agentic coding model.",
		harness: "codex",
		provider: "openai",
		routing: { kind: "default" },
		status: "prototype",
		capabilities: {
			thinking: {
				availability: "supported",
				default: "medium",
				options: [
					standard("light", "low"),
					standard("medium", "medium"),
					standard("high", "high"),
					standard("xhigh", "xhigh"),
					exceptional("max", "max"),
				],
			},
			speed_options: [
				openai_standard_speed("GPT 5.6 Luna", true),
				openai_fast_speed("GPT 5.6 Luna", 2.5),
			],
			context_window: openai_context_window,
			image_input: true,
			local_tools: true,
			mcp: true,
			web_search: true,
		},
	},
	{
		id: "codex-gpt-5-5",
		name: "GPT 5.5",
		native_model_id: "gpt-5.5",
		description: "Proven previous-generation model for coding and general work.",
		harness: "codex",
		provider: "openai",
		routing: { kind: "default" },
		status: "prototype",
		capabilities: {
			thinking: {
				availability: "supported",
				default: "medium",
				options: [
					standard("light", "low"),
					standard("medium", "medium"),
					standard("high", "high"),
					standard("xhigh", "xhigh"),
				],
			},
			speed_options: [
				openai_standard_speed("GPT 5.5", true),
				openai_fast_speed("GPT 5.5", 2.5),
			],
			image_input: true,
			local_tools: true,
			mcp: true,
			web_search: true,
		},
	},
	{
		id: "codex-spark",
		name: "GPT 5.3 Codex Spark",
		native_model_id: "gpt-5.3-codex-spark",
		description: "Ultra-fast coding model.",
		harness: "codex",
		provider: "openai",
		routing: { kind: "default" },
		status: "prototype",
		capabilities: {
			thinking: {
				availability: "supported",
				default: "high",
				options: [
					standard("light", "low"),
					standard("medium", "medium"),
					standard("high", "high"),
					standard("xhigh", "xhigh"),
				],
			},
			speed_options: [openai_standard_speed("GPT 5.3 Codex Spark", false)],
			image_input: false,
			local_tools: true,
			mcp: true,
			web_search: true,
		},
	},
] satisfies ReadonlyArray<ModelDefinition>;
