load(
    "@rules_rust//rust:defs.bzl",
    "rust_binary",
    "rust_clippy",
    "rust_library",
    "rustfmt_test",
)

exports_files(["Cargo.toml"])

rust_library(
    name = "native_dev",
    srcs = ["src/lib.rs"],
    crate_name = "native_dev",
    deps = [
        "//modules/cli:cli",
        "@crates//:serde_json",
        "@crates//:sha2-0.10.9",
        "@crates//:thiserror",
    ],
    edition = "2024",
    lint_config = "//:workspace_lints",
    visibility = [
        "//tests/native_dev:__pkg__",
    ],
)

rust_binary(
    name = "dev",
    srcs = ["src/main.rs"],
    crate_name = "dev",
    data = [
        "//modules/backend:forge",
        "//modules/cli:ae",
        "//modules/frontend:editor",
        "//modules/installer:installer",
    ],
    deps = [":native_dev"],
    edition = "2024",
    lint_config = "//:workspace_lints",
    visibility = ["//visibility:public"],
)

rust_clippy(
    name = "clippy",
    testonly = True,
    deps = [
        ":dev",
        ":native_dev",
    ],
)

rustfmt_test(
    name = "format_test",
    size = "small",
    targets = [
        ":dev",
        ":native_dev",
    ],
    transitive = True,
)

test_suite(
    name = "tests",
    tests = [":format_test"],
)
